### PR TITLE
avm1: Fix target clip behavior in SWF5

### LINKED ISSUE #2580: avm1: target_clip behavior difference depending on SWF version
On SWF6, calling a function changes the active `target_clip` according to the *callee's* definition location.
Currently Ruffle handles this behavior as expected:
https://github.com/ruffle-rs/ruffle/blob/9df7facdb8d37a5d007a13c25efcc176ed4675e0/core/src/avm1/function.rs#L324

However SWF5 seems to behave differently. Instead of changing the active `target_clip`, it remains unchanged and same as the *caller's* `target_clip`.
Ruffle doesn't handle this behavior and always behaves like SWF6.

The attached examples are identical except for their SWF version (5 vs. 6).
Notice that only the yellow circle moves in `target_clip_swf5.zip`, but both the yellow circle and the green square move in `target_clip_swf6.zip`.

[target_clip_swf5.zip](https://github.com/ruffle-rs/ruffle/files/5824916/target_clip_swf5.zip)
[target_clip_swf6.zip](https://github.com/ruffle-rs/ruffle/files/5824918/target_clip_swf6.zip)

Changing the line mentioned above from `af.base_clip,` to `activation.base_clip,` (plus making it `pub`) seem to change the behavior from SWF6 to SWF5. I feel like selecting either `af.base_clip` or `activation.base_clip` depending on the SWF version is the proper fix, but I'm not 100% sure about it.

### PR DESCRIPTION
**Pull request by relrelb**
Fixes #2580.

### CODE REVIEW

**Comment by Toad06** [comment]
FWIW, I've tested the PR and observed a few issues on a couple of files:
- [Crazy Hunters](https://github.com/ruffle-rs/ruffle/files/5720894/crazyhunters.zip): When you shoot the first bird bird, the next one appears in the top left corner. The next ones are likely off screen.
- [Zizzo Challenge](https://github.com/ruffle-rs/ruffle/files/5826495/zizzochallenge.zip): The game softlocks after the first mini game.

**Comment by relrelb** [comment]
Thank you for testing!
I think it should be okay now. Can you please confirm it on your side?

**Comment by Toad06** [comment]
All good! 👍 Thanks a lot for your work.

File: core/src/avm1/function.rs [hunk 1]
```diff
@@ -315,13 +315,18 @@ impl<'gc> Executable<'gc> {
                 };
 
                 let max_recursion_depth = activation.context.avm1.max_recursion_depth();
+                let base_clip = if effective_ver > 5 {
+                    af.base_clip
+                } else {
+                    this.as_display_object().unwrap()
```
Comment (Herschel) [inline core/src/avm1/function.rs:321]: This unwrap panics on an SWF5 swf:
```

var o = {
	f: function() {
		trace("f");
		this.g();
	},
	g: function() {
		trace("g");
	}
};
o.f();
```

**Review by Herschel — CHANGES_REQUESTED** [review]

File: core/src/avm1/function.rs (hunk 1 above)
Comment (Toad06) [reply core/src/avm1/function.rs:321]: Tested this (`af.base_clip.avm1_root().unwrap()`) but this is causing a regression in [Spike Boy](https://www.y8.com/games/spike_boy) (by the way, the game also needs #2636): pressing the arrow keys moves the GUI instead of moving the character.

Comment (relrelb) [reply core/src/avm1/function.rs]: It now fallbacks to `activation.base_clip()`.
I think that `af.base_clip.avm1_root()` (and `af.base_clip`) are incorrect because [test.zip](https://github.com/ruffle-rs/ruffle/files/5852172/test.zip) shows a different behavior.

**Comment by Toad06** [comment]
Yikes, I've tested a game (SWF version 5) that regressed because of this. For some reason, collisions don't work because code inside `\DefineSprite (120: oeufs)\frame 4\DoAction` is no longer executed.

FWIW, the game works when `base_clip` is either `af.base_clip` or `af.base_clip.avm1_root().unwrap()`.

The game is unfortunately no longer available online and I own no rights on the file, but I can upload it for a short time if you want to take a look at it.
