### PR TITLE
web: Don't polyfill YouTube Flash embeds

### LINKED ISSUE #4030: Ruffle overwrites Flash-era YouTube embeds even though they load the HTML5 player
**Describe the bug**
Old YouTube embeds that were meant to load the Flash player are being replaced by the Ruffle canvas (which obviously doesn't work). However, Google has put in place code that overwrites these embeds with an iframe containing the modern player, meaning there is no reason for Ruffle to intervene.

Examples:
[Case 1](http://www.gershonkingsley.com/popcorn.html)
[Case 2](https://answers.microsoft.com/en-us/xbox/forum/xba_wowpc-xba_gowcc/why-is-windows-10-not-installed-on-xbox-series-x/98498b7d-8461-40f2-8380-1cc1d1622fe9)

**Expected behavior**
The modern HTML5 player should be loaded despite the embed expecting Flash content.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension (tested with latest nightly on Firefox Developer Edition)

**What platform are you using?**
Windows 10

### LINKED ISSUE #6504: Youtube Videos Don't play
### Describe the bug

Screenshot 2022-03-21 at 09-49-17 About Buddy Personal Testimony
Youtube videos that were embedded using Flash won't play with Ruffle. I am using today's version. Here is a link to a page with this problem: https://sarahbethonline.com/buddydavis/aboutbuddy/testimony.html
The Youtube video still exists but won't play.

### Expected behavior

I expected the youtube video to play.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 98.0.1

### Additional information

It says 'Ruffle wasn't able to run the Flash embedded in this page. You can try to open the file in a separate tab, to sidestep this issue. Open in new tab

### PR DESCRIPTION
**Pull request by danielhjacobs**
More accurate alternative to #6520. Fix #4030 and fix #6504.

This behavior is explained by https://wiki.mozilla.org/QA/Youtube_Embedded_Rewrite. See https://bugzilla.mozilla.org/attachment.cgi?id=8707266&action=diff and https://hg.mozilla.org/mozilla-central/rev/5125dbdcbcb2 for implementation in Firefox. See https://chromium.googlesource.com/chromium/src.git/+/e0135598f6bf547463bc943100da4574c5f89930%5E!/ for implementation in Chromium.

~~Edit: My 2nd commit is because this only happen for embeds.~~

Edit: I now change the src for Youtube Flash embeds on http to https if the window is on https and upgradeToHttps is not false, which is technically inaccurate behavior, but I thought was better anyway.

### CODE REVIEW

**Comment by danielhjacobs** [comment]
Second commit is basically a duplicate of https://hg.mozilla.org/integration/autoland/rev/5125dbdcbcb2

**Comment by danielhjacobs** [comment]
I'm not sure objects are supposed to do this same thing, on only embeds.

**Comment by Herschel** [comment]
Thanks for taking the time to research this!

So I understand correctly, it seems like YouTube does indeed serve HTML5 when requesting a Flash embed (I did a get from `curl` to check), but all of the browsers already have a hard-coded replacement for these embeds?

Could you add a test case in web/packages/selfhosted/test? Or I could try to add one if you'd like.

**Comment by Herschel** [comment]
I also wonder if upgrading the YouTube URL to `https` should be based on the `upgradeToHttps` config setting.

**Comment by danielhjacobs** [comment]
The problem is that browsers automatically replace /v/ with /embed/.  And in just this one specific case they ignore the type. If you check the network tab on any of the pages in the issues without Ruffle, the request goes to /embed/, despite the src.

Settings aren't checked until after the polyfill I think, so I'd need to move some logic in the code to base it on that setting

**Comment by danielhjacobs** [comment]
I can look into adding the test when I can but I can't right now.

**Comment by danielhjacobs** [comment]
Actually I'm not quite sure what the test would be.  The network tab requests a different resource but the embed src in the page's actual source remains the same.

**Comment by Toad06** [comment]
It seems like `<object>` tags can actually have this workaround, at least when the tag uses the `data` attribute:

```
<object type="application/x-shockwave-flash" data="https://www.youtube.com/v/ENumi96Btj0" width="425" height="350" wmode="transparent">
   <param name="movie" value="https://www.youtube.com/v/ENumi96Btj0"/>
</object>
```

**Comment by danielhjacobs** [comment]
> It seems like `<object>` tags can actually have this workaround, at least when the tag uses the `data` attribute:

Interesting, this works on both Firefox and Chrome with the data attribute, but without the data attribute it only works on Chrome. Chrome almost certainly has the preferred behavior, so I'll revert commit 2.

**Comment by danielhjacobs** [comment]
> I also wonder if upgrading the YouTube URL to `https` should be based on the `upgradeToHttps` config setting.

The config is not checked in ruffle-embed.ts or ruffle-object.ts currently. I don't think it needs to be. I imagine this code will generally take effect with the extension, which doesn't have a config value for upgradeToHttps. Even in the self-hosted version, I can't imagine a scenario where this behavior wouldn't be desired. Normally, it may not be desired because the https site may not exist, but https://www.youtube.com definitely exists.

**Comment by danielhjacobs** [comment]
Barring a true desire to base the https upgrade on the config value, I'd say this is ready for review.

**Comment by danielhjacobs** [comment]
I use the `upgradeToHttps` config value now. I also workaround mixed content YouTube objects.

File: web/packages/core/src/ruffle-player.ts [hunk 1]
```diff
@@ -1475,6 +1475,65 @@ export function isBuiltInContextMenuVisible(menu: string | null): boolean {
...
+            pathname = url.pathname;
+            hostname = url.hostname;
+        } catch (err) {
+            // Some invalid filenames, like `///`, could raise a TypeError. Let's fail silently in this situation.
+        }
+        // See https://wiki.mozilla.org/QA/Youtube_Embedded_Rewrite
+        if (
+            pathname.startsWith("/v/") &&
+            (hostname.endsWith("youtube.com") ||
+                hostname.endsWith("youtube-nocookie.com"))
```
Comment (Herschel) [inline web/packages/core/src/ruffle-player.ts:1500]: A little paranoid, but this will match with `notreallyyoutube.com/v/`.

Comment (danielhjacobs) [reply web/packages/core/src/ruffle-player.ts]: First commit of two new ones addressed this. The second one makes things work on Firefox the same way they work on Chrome, despite a discovered browser bug.

Comment (danielhjacobs) [reply web/packages/core/src/ruffle-player.ts]: Second new commit is to make this work on Firefox as well: https://github.com/ruffle-rs/ruffle/pull/6553#issuecomment-1086958924

**Comment by Herschel** [comment]
Thank you!
