### PR TITLE
avm2: Fixes to Vector call handler

### LINKED ISSUE #21615: Error on https://game231564.konggames.com/games/PegasGames/wheely-4-time-travel/frame/87f2441e-04d6-4a0e-84f5-7a015c614aee/
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/value.rs:1562:17:
internal error: entered unreachable code: Should not have Undefined or Null in `instance_class`
Error stack:
```
Error: panicked at core/src/avm2/value.rs:1562:17:
internal error: entered unreachable code: Should not have Undefined or Null in `instance_class`
    at Le.e.wbg.__wbg_new_c68d7209be747379 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b9039dd2c7413e716333.js:1:57597)
    at ruffle_web.wasm.js_sys::Error::new::hcb407689aec3a1ee (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[12791]:0x9226cf)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffa2eed206524d4 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[9867]:0x8d5da4)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h4fa3daead9c4e0a7 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[6377]:0x808b95)
    at ruffle_web.wasm.core::panicking::panic_fmt::hd3052a3662d50c95 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[10742]:0x8ef69a)
    at ruffle_web.wasm.ruffle_core::avm2::globals::vector::call_handler::h35fec77d1a42bb05 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[1430]:0x3aee9d)
    at ruffle_web.wasm.ruffle_core::avm2::object::class_object::ClassObject::call::h2138e6869af4ff78 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[2961]:0x6071f6)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::call::hf40223a21bce579a (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[6470]:0x80e10f)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h26a3ca10c4d906b9 (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[1563]:0x4093f0)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::call_method_with_args::h7890e7c60241f0ac (wasm://wasm/ruffle_web.wasm-030257fa:wasm-function[2959]:0x606d1f)
```
AVM2 stack:
```
    at General::GameData$/LoadGame()
    at Gameplay::Game()
    at Main/init()
    at flash.display::DisplayObjectContainer/addChild()
    at Preloader/StartGame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA RTX A2000 (0x00002531) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features { features_wgpu: FeaturesWGPU(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES), features_webgpu: FeaturesWebGPU(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE) }
Available features: Features { features_wgpu: FeaturesWGPU(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW), features_webgpu: FeaturesWebGPU(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D) }
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_binding_array_elements_per_shader_stage: 0, max_binding_array_sampler_elements_per_shader_stage: 0, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game231564.konggames.com/games/PegasGames/wheely-4-time-travel/frame/87f2441e-04d6-4a0e-84f5-7a015c614aee/?kongregate_host=www.kongregate.com
SWF URL: https://game231564.konggames.com/gamez/0023/1564/live/Wheely4.swf?kongregate_game_version=1423040859

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.2.0-nightly.2025.9.10
Name: 0.2.0-nightly.2025.9.10
Channel: nightly
Built: 2025-09-10T00:07:37.410Z
Commit: e3b52d14b864b20dcfef1ed714c7475a5abba00f
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 35
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 16659037

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
This should fix #21615, though I haven't been able to reproduce the panic myself

### CODE REVIEW

File: core/src/avm2/globals/array.rs [hunk 1]
```diff
@@ -246,12 +246,18 @@ impl<'gc> ArrayIter<'gc> {
 
             let val = self.array_object.get_index_property(i as usize);
 
-            let val = if let Some(storage) = self.array_object.as_vector_storage() {
+            let val = if let Some(val) = val {
```
Comment (evilpie) [inline core/src/avm2/globals/array.rs]:
```suggestion
            let val = if let Some(val) = self.array_object.get_index_property(i as usize) {
```

Comment (Lord-McSweeney) [reply core/src/avm2/globals/array.rs]: This makes the line too long, but it works when adding a `let array_object = self.array_object;`
