### PR TITLE
core: Display image load when using Loader.loadBytes

### LINKED ISSUE #14791: Regression: black screen in Jet Velocity
### Describe the bug

In the latest nightly release (2024-01-17), [Jet Velocity](https://www.newgrounds.com/portal/view/553350/format/flash?emulate=flash) now shows nothing but a black screen. It worked in previous nightly releases. This seems to be a regression caused by #14671.

### Expected behavior

The game should be playable as it was in previous versions of Ruffle.

### Content Location

[jetvelocity_decrypted.zip](https://github.com/ruffle-rs/ruffle/files/12265048/jetvelocity_decrypted.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Aaron1011**
The handling of images in Loader.loaderBytes is similar to the handling of SWFs - some of the data is exposed immediately following the 'Loader.loadBytes' call, but the DisplayObject isn't loaded until later.

Fixes #14791

### CODE REVIEW

File: core/src/player.rs [hunk 1]
```diff
@@ -177,9 +177,17 @@ struct GcRootData<'gc> {
     /// Dynamic root for allowing handles to GC objects to exist outside of the GC.
     dynamic_root: DynamicRootSet<'gc>,
 
+    #[allow(clippy::type_complexity)]
```
Comment (Lord-McSweeney) [inline core/src/player.rs:180]: Is this allow really needed up here? `Vec<PostFrameCallback<'gc>>` is a very simple type

**Review by Lord-McSweeney — APPROVED** [review]
