### PR TITLE
desktop: Make shortcuts work in fullscreen and no-gui mode

### LINKED ISSUE #15637: Ctrl+Q dont work when ruffle desktop at Fullscreen
### Describe the bug

when ruffle desktop is at Fullscreen i want to Exit directly using Ctrl+Q but don't work 
it works when i quit Fullscreen by Alt+Enter then Ctrl+Q works 

### Expected behavior

Ctrl+Q exit me (close ruffle completely)  when ruffle is  at Fullscreen state

### Content Location

[lingot08 exo5167.zip](https://github.com/ruffle-rs/ruffle/files/14643831/lingot08.exo5167.zip)

### Affected platform

Desktop app

### Operating system

windows 10

### Browser

_No response_

### Additional information

thank you for reading this, hoping to be  fixed  soon

### LINKED ISSUE #17383: CTRL + P Doesn't Work in Fullscreen
### Describe the bug

The CTRL + P pause/unpause hotkey doesn't do anything while in fullscreen mode (but pauses/unpauses without issue in windowed mode).

### Expected behavior

The CTRL + P command successfully pausing/unpausing flash content in fullscreen mode

### Content Location

[vicious pnm kitty sound.zip](https://github.com/user-attachments/files/16503103/vicious.pnm.kitty.sound.zip)

### Affected platform

Desktop app

### Operating system

Windows 11 Pro 22H2

### Browser

_No response_

### Additional information

Occurring in Ruffle Windows nightly version 2024-08-04

### PR DESCRIPTION
**Pull request by sleepycatcoding**
Fixes #15637
Fixes #17383

### CODE REVIEW

File: desktop/src/gui/menu_bar.rs [hunk 1]
```diff
@@ -43,45 +43,42 @@ impl MenuBar {
...
-            if ui.ctx().input_mut(|input| {
-                input.consume_shortcut(&Self::SHORTCUT_FULLSCREEN)
-            }) {
-                if let Some(player) = &mut player {
-                    player.set_fullscreen(true);
-                }
+        }
+        if egui_ctx.input_mut(|input| input.consume_shortcut(&Self::SHORTCUT_FULLSCREEN)) {
+            if let Some(player) = &mut player {
+                player.set_fullscreen(true);
```
Comment (kjarosh) [inline desktop/src/gui/menu_bar.rs:69]: If now this shortcut works in full screen, it would perhaps be better to toggle full screen here so that pressing F11 will exit full screen.

**Review by kjarosh — APPROVED** [review]

File: desktop/src/gui/menu_bar.rs (hunk 1 above)
Comment (sleepycatcoding) [reply desktop/src/gui/menu_bar.rs:69]: Good idea, I'll wait for #17592 to get merged and then I will make this toggle instead.

Comment (sleepycatcoding) [reply desktop/src/gui/menu_bar.rs]: Changed.

**Review by kjarosh — APPROVED** [review]

**Comment by torokati44** [comment]
Huhm: https://github.com/ruffle-rs/ruffle/issues/17617
