### PR TITLE
core: Use fixed-point types for color transforms

### LINKED ISSUE #193: Matrix and other structures should match Flash's internal representation
Currently our Matrix uses float, but this causes some inaccuracies compared to Flash, which uses twips and fixed point values for its internal representation. For example, the value of `_x` will be slightly different between Ruffle and Flash Player due to this.

Color transforms are another area we should try to match, IIRC they use 8.8 fixed point values. For example, _alpha only increments in units of 1/256.

### PR DESCRIPTION
**Pull request by Herschel**
Adds fixed-point types to SWF:
 * `Fixed8`, an 8.8 signed fixed-point type
 * `Fixed16`, and 16.16 signed fixed-point type (not used in this PR).
This is meant to be tailored toward the uses of Flash/Ruffle. Specifically there is no rounding adjustment done; all calculations are truncated, matching Flash's behavior. (More precise libraries may do proper rounding by considering the last bit that was shifted off in a calculation).

Changes `swf::ColorTransform` to use `Fixed8` for the multiply component and `i16` for the add component. This matches Flash's behavior, and is important because, for example, `_alpha` changes only in increments of 1/256, and many games check for `_alpha` being some specific value.

This allows [Redder](https://www.newgrounds.com/portal/view/529992) to get past the intro cutscene. Previously it would soft lock waiting for the gems to fade in.

TODO (future PRs):
 * Add `Fixed16` to tests (unused currently)
 * Could add a few more methods & `To`/`From` impls to fixed types
 * Move most low-level types (`Fixed`, `Color`, `Rectangle` etc.) to a `ruffle_types` subcrate
 * Use `Fixed8`/`Fixed16` in a few more places (namely filters and possibly `swf::Matrix`)

Fixes #193.

### CODE REVIEW

File: swf/src/types/fixed.rs [hunk 1]
```diff
@@ -0,0 +1,643 @@
...
+
+        impl Default for $type_name {
+            /// Returns the default value of `0.0`.
+            #[inline]
+            fn default() -> Self {
+                Self(0)
+            }
+        }
+
+        impl std::fmt::Display for $type_name {
```
Comment (torokati44) [inline swf/src/types/fixed.rs:181]: Would it make sense to `impl` `Debug` differently, to show the raw integer inside?
Well, probably not...

Comment (Herschel) [reply swf/src/types/fixed.rs:181]: It has `#[derive(Debug)]` which does that for us.

File: swf/src/types/fixed.rs [hunk 2]
```diff
@@ -0,0 +1,643 @@
...
+            #[inline]
+            fn mul(self, other: Self) -> Self {
+                let n = <$intermediate_type>::from(self.0) * <$intermediate_type>::from(other.0)
+                    >> Self::FRACTIONAL_BITS;
+                if cfg!(debug_assertions) {
+                    Self(<$underlying_type>::try_from(n).expect("Attempted to multiply with overflow"))
+                } else {
+                    Self(n as $underlying_type)
+                }
+            }
```
Comment (torokati44) [inline swf/src/types/fixed.rs:244]: Should this delegate to `mul_int`?
It's not that much code, so not big deal, but the body looks completely identical to that.
Same for `div` and `div_int`.

Maybe it would be just confusing, because the same amount of right shift (for `mul` that is) is needed for a different reason?
I mean, in `mul_int`, it converts the result to "regular integer"; while in here, it "undoes" one of the two incoming "shifted representations". I hope it's clear what I'm trying to say.

**Review by torokati44 — COMMENTED** [review]
Apart from those little notes inline, LGTM.

File: swf/src/types/fixed.rs (hunk 2 above)
Comment (Herschel) [reply swf/src/types/fixed.rs:244]: Yea, that makes sense. It's slightly awkward as I'd have to to do `self.mul(Fixed8::from_bits(other)).0` which isn't super obvious. More generally we could probably have a single method for each op that both the normal and wrapping methods defer to. I'll leave it as is for now.
