### PR TITLE
web: Fix enter key + add input tests

### LINKED ISSUE #9636: Write in the Death Note: Pressing the Return key will not do the animation that is supposed to happen
### Describe the bug

Tested on Ruffle Nightly 2023-02-19
Write in the Death Note SWF used: [Write in the Death Note.zip](https://github.com/ruffle-rs/ruffle/files/10776445/Write.in.the.Death.Note.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/219937762-2b651a51-eaaa-4944-9efe-d5570bf7cb2e.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/219937823-31b7da67-81a6-4e6d-b040-8bada66d4030.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

### Additional information

_No response_

### LINKED ISSUE #13849: Cannot submit chat message by hitting enter on text input
### Describe the bug

Game URL - http://www.gaiaonline.com/launch/towns2

To reproduce bug:
1) login to Gaia https://www.gaiaonline.com (registration required)
2) access game http://www.gaiaonline.com/launch/towns2
3) Select any chat room (eg Alpha)
4) mouse click on the white text input field
5) type in any text and hit enter to submit text

Screen Shot 2023-11-03 at 12 02 15 AM

### Expected behavior

Text in the text input field should disappear upon hitting enter.  Submitted text will then appear as a speech bubble above your own character, as well as text in the chat log accessed by clicking on the speech bubble on the bottom left corner of screen.

### Affected platform

Self-hosted version

### Operating system

macOS

### Browser

Chrome Version 118.0.5993.88 (Official Build) (x86_64)

### Additional information

_No response_

### LINKED ISSUE #13929: You can't send messages by pressing enter in Habbo.swf
### Describe the bug

You can't send messages by pressing enter, which is mostly used for chatting in rooms and chatting via the console.

Steps to reproduce:

1. [Create an account here](https://habbolegacy.com/register)
2. Enter the [Flash client](https://habbolegacy.com/flash_client)
3. Use the navigator to go to any room and try to chat.

image

### Expected behavior

You should be able to send messages by pressing enter.

It's worth noting that this does actually work in the desktop version of Ruffle.

### Content Location

https://habbolegacy.com/flash_client

Here's the files from the base location: [r38.zip](https://github.com/ruffle-rs/ruffle/files/13310204/r38.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 119

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dinnerbone**
Fixes #9636
Fixes #13929
Fixes #13849

### CODE REVIEW

File: web/packages/selfhosted/test/utils.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const path = require("path");
-const {expect} = require("chai");
+const { expect } = require("chai");
```
Comment (torokati44) [inline web/packages/selfhosted/test/utils.js:2]: nit: Shouldn't this change be in the previous commit?

**Review by torokati44 — APPROVED** [review]
