### PR TITLE
core: Use correct embedded font lookup order

### LINKED ISSUE #13602: Letters missing on https://content.dnalc.org/content/1719/1719_fruitfly.swf
### Describe the bug

Text in the animation is missing the following letters, numbers, and punctuation:
- A C H I M S T U (all that appear except D)
- b c d k q v w x z
- 0 1 2 9 (all that appear)
- . , – - “ ” ! (all that appear except opening and closing parentheses)

Page is https://dnalc.cshl.edu/view/1719-Fruit-fly-Drosophila-melanogaster

SWF is https://content.dnalc.org/content/1719/1719_fruitfly.swf
Screenshot from 2023-10-18 10-04-39

### Expected behavior

The full text corresponding to the transcript should appear in the animation.
Screenshot from 2023-10-18 10-16-46

### Affected platform

Self-hosted version

### Operating system

Linux Fedora 37

### Browser

Mozilla Firefox 117

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dinnerbone**
Embedded fonts should properly fall back to the correct font for the style they have - and check for fonts case insensitive.

Also fixes that `<font>` in text should change the style to Regular.

This fixes #13602
This fixes Plazma Burst credits text

### CODE REVIEW

File: core/src/html/layout.rs [hunk 1]
```diff
@@ -470,11 +470,15 @@ impl<'a, 'gc> LayoutContext<'a, 'gc> {
...
             if let Some(font) = library
-                .get_font_by_name(&font_name, span.bold, span.italic)
+                .get_embedded_font_by_name(&font_name, span.bold, span.italic)
                 .filter(|f| f.has_glyphs())
             {
                 return Some(font);
             }
+            // TODO: If set to use embedded fonts and we couldn't find any matching font, show nothing
+            // However - at time of writing, we don't support DefineFont4. If we matched this behaviour,
+            // then a bunch of SWFs would just show no text suddenly.
```
Comment (Lord-McSweeney) [inline core/src/html/layout.rs:480]: That's weird- I remember removing `DefineFont4` tags and the `Font.registerFont` calls, and TLF text still showed up.

**Review by Aaron1011 — APPROVED** [review]

File: core/src/html/layout.rs (hunk 1 above)
Comment (Dinnerbone) [reply core/src/html/layout.rs:480]: I'd have to check that swf and find out 😅 in his path it shouldn't use fallback fonts at all, and there's a test to confirm it
