### PR TITLE
web: allow entering fullscreen after using escape to exit

### LINKED ISSUE #5698: Re-entering fullscreen after exiting fullscreen with the escape button does nothing
### Describe the bug

Pretty self-explanatory in the title, right click the game. Click "Enter fullscreen". Then press escape to exit fullscreen.

Re-entering fullscreen will do nothing

### Expected behavior

The Enter fullscreen button will stop functioning

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Opera GX 81

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by midgleyc**
Fixes #5698.

Ruffle does a React-style property check using the State to determine whether it's full screen or not, and using escape (or a manual `document.exitFullscreen()`) can cause that to go out of sync with reality, and the fix here is to listen to the `fullscreenchange` event and set Ruffle's fullscreen setting accordingly if it's exiting full screen.

### CODE REVIEW

**Comment by danielhjacobs** [comment]
I had created this exact change but didn't create a PR with it because of an error in the console. When you use escape to exit fullscreen, you'll see the console says "TypeError: Not in fullscreen mode". If we think that's fine, this did seem like the simplest option to me as well.

**Comment by danielhjacobs** [comment]
> or a manual document.exitFullscreen()

Would a similar issue occur with a manual call to enterFullscreen()? If so, maybe we should put an else with             this.instance?.set_fullscreen(true);

**Comment by midgleyc** [comment]
> TypeError: Not in fullscreen mode

That's what you get when you call `document.exitFullscreen()` without being in full screen. We could make the code check whether it thinks it's in full screen before trying. Alternatively we could catch the error, which we don't care about.

> Would a similar issue occur with a manual call to enterFullscreen()?

If you can figure out how to call `enterFullscreen()` manually, probably? It's much harder to do though -- has to be called from "a short-lived user-generated event handler".

**Comment by Toad06** [comment]
Safari still implements the fullscreen API with a vendor prefix, so unfortunately we also need to use `webkitfullscreenchange` and `webkitFullscreenElement`.

**Comment by danielhjacobs** [comment]
Might it be better to combine the 2 functions into one?
    if (document.fullscreenElement === null && document.webkitFullscreenElement === null) {
    ...

**Comment by midgleyc** [comment]
They're listening to different events: Safari wants the `webkitfullscreenchange` while everything else looks for the `fullscreenchange` event.

Because of this I think it's better to keep each function focused on only the elements that exist for it. Combining the functions would save some lines but I think make it less clearer what's going on.

File: web/packages/core/src/ruffle-player.ts [hunk 1]
```diff
@@ -677,6 +685,26 @@ export class RufflePlayer extends HTMLElement {
         }
     }
 
+    /**
+     * Called when entering / leaving fullscreen on non-Safari
+     */
+    private fullScreenChange(): void {
+        // check if we have just stopped being full screen
+        if (document.fullscreenElement === null) {
```
Comment (relrelb) [inline web/packages/core/src/ruffle-player.ts:693]: Sorry for the delay. I'm worried this doesn't cover cases where the user forcibly enters fullscreen (e.g. typing `player.requestFullscreen()` in DevTools). We can change this to a two-way update:
```ts
this.instance?.set_fullscreen(document.fullscreenElement !== null);
```

File: web/packages/core/src/ruffle-player.ts [hunk 2]
```diff
@@ -677,6 +685,26 @@ export class RufflePlayer extends HTMLElement {
...
+            this.instance?.set_fullscreen(false);
+        }
+    }
+
+    /**
+     * Called when entering / leaving fullscreen on Safari
+     */
+    private webKitFullScreenChange(): void {
```
Comment (relrelb) [inline web/packages/core/src/ruffle-player.ts:701]: This is a bit of code duplication.
It could be done using a single event listener that handles both `document.fullscreenElement` and `document.webkitFullscreenElement`.

File: web/packages/core/src/ruffle-player.ts (hunk 1 above)
Comment (midgleyc) [reply web/packages/core/src/ruffle-player.ts:693]: Not if we combine this and the Safari one.

The possibilities are:

|  | Safari | Other |
| --- | --- | --- |
| fullscreenElement | undefined | null or object |
| webkitFullscreenElement | null or object | undefined |

so if fullscreenElement isn't null, either we have a full screen element or we're in Safari.

You can try something like:
```
this.instance?.set_fullscreen((document.fullscreenElement !== null && document.webkitFullscreenElement === undefined) || (document.webkitFullscreenElement !== null && document.fullscreenElement === undefined));
```

but I think the code deduplication is outweighed by the additional complexity.

I'd prefer to do this change, but not deduplicate. What do you think?

Comment (relrelb) [reply web/packages/core/src/ruffle-player.ts:693]: This could be simplified based on the fact that `null` and `undefined` are falsy:
```ts
this.instance?.set_fullscreen(document.fullscreenElement || document.webkitFullscreenElement);
```
So if this is doable I still prefer deduplicating the methods.

Comment (midgleyc) [reply web/packages/core/src/ruffle-player.ts]: That's nice: seems like it should work for all cases and looks simple too. Thanks.

File: web/packages/core/src/ruffle-player.ts [hunk 3]
```diff
@@ -677,6 +685,17 @@ export class RufflePlayer extends HTMLElement {
         }
     }
 
+    /**
+     * Called when entering / leaving fullscreen
+     */
+    private fullScreenChange(): void {
+        this.instance?.set_fullscreen(
+            Boolean(
```
Comment (relrelb) [inline web/packages/core/src/ruffle-player.ts:693]: Actually there already exists a `this.isFullscreen` property that does exactly this. Didn't notice it before...

**Review by relrelb — APPROVED** [review]
Thanks! Going to merge as this indeed fixes the problem, but I think the fullscreen mechanism needs some cleanup since currently it's somewhat entangled (a fullscreen request goes all the way through `ruffle-player.ts` -> `web/src/lib.rs` -> core `Player` -> core `Stage` -> UI backend, and then back to `ruffle-player.ts`...). I think we need to call `enterFullscreen()` and `exitFullscreen()` directly from `ruffle-player.ts`, make them notify Rust, and break that very confusing cycle.
