### PR TITLE
avm2: Implement Font.enumerateFonts and Font.registerFont

### LINKED ISSUE #8830: Air Transporter - Black Screen
### Describe the bug

`ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x212255f83b0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x2120b778638 }))) : RustError("Font.enumerateFonts is a stub")`

### Expected behavior

should work

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

stub is a stub, but this will need to be implemented
[546844_2965.zip](https://github.com/ruffle-rs/ruffle/files/10254725/546844_2965.zip)

### PR DESCRIPTION
**Pull request by Dinnerbone**
Fixes #8830 (and possibly some others)

Probably makes some movies use their proper fonts, but none spring to mind at the moment (likely anything that logged about the `registerFont` stub would start looking better, at least)

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Confirmed that this makes the fonts in Habbo go from totally unreadable to perfect

**Review by sleepycatcoding — APPROVED** [review]
Looks good to me

File: core/src/avm2/globals/flash/text/font.rs [hunk 1]
```diff
@@ -103,23 +64,9 @@ pub fn has_glyphs<'gc>(
...
-            .library
-            .library_for_movie_mut(movie)
-            .character_by_id(character_id)
-        {
-            return Ok(font.has_glyphs_for_str(&my_str).into());
-        }
+        return Ok(font.has_glyphs_for_str(&my_str).into());
     }
 
     Ok(Value::Undefined)
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/flash/text/font.rs:78]: This would be better returning `false.into()` to be more clear about the return value (`hasGlyphs` returns a `bool`)

File: core/src/avm2/globals/flash/text/font.rs [hunk 2]
```diff
@@ -129,18 +82,66 @@ pub fn has_glyphs<'gc>(
...
+            "enumerateFonts",
+            "with device fonts"
+        );
+    }
+
+    for font in activation.context.library.global_fonts() {
+        storage.push(FontObject::for_font(activation.context.gc_context, font_class, font).into());
+    }
+
+    if let Some(movie) = activation.caller_movie() {
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/flash/text/font.rs:104]: This should always be `Some`- if it isn't, we have a bug. With #13492 it should always be set except in the strangest of cases (no SWF should be calling those cases).

**Review by Lord-McSweeney — APPROVED** [review]
Approved with a few minor nits

File: core/src/avm2/globals/flash/text/font.rs (hunk 1 above)
Comment (Dinnerbone) [reply core/src/avm2/globals/flash/text/font.rs:78]: Sure, it's existing code so I didn't consider it. Changing!
