### PR TITLE
core: Fix characters being cut off (close #4051)

### LINKED ISSUE #4051: Watermark doesn't unroll completely in aBowman gadgets
**Describe the bug**
Some gadgets at abowman.com such as [this one](https://cdn.abowman.com/widgets/fish/fish.swf) contain a watermark that unrolls when hovered over. When played in Ruffle, the "N" gets cut off.

**Expected behavior**
The watermark is supposed to fully unroll while hovering.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension

**What platform are you using?**
Firefox Developer Edition on Windows 10

### PR DESCRIPTION
**Pull request by yellow-shrimp**

### CODE REVIEW

File: core/src/display_object/edit_text.rs [hunk 1]
```diff
@@ -938,6 +952,18 @@ impl<'gc> EditText<'gc> {
         if let Some((text, _tf, font, params, color)) =
             lbox.as_renderable_text(edit_text.text_spans.displayed_text())
         {
+            // Whether the glyph should be scaled due to padding
+            // see: https://github.com/ruffle-rs/ruffle/issues/4051
+            context.transform_stack.push(&Transform {
+                matrix: Matrix::scale(
+                    1.0 - ((Self::INTERNAL_PADDING - edit_text.hscroll)
```
Comment (kmeisthax) [inline core/src/display_object/edit_text.rs:959]: I'm a little confused by this line. If I'm reading this correctly, the glyph gets more squished when the text box is scrolled to the right more?

Comment (yellow-shrimp) [reply core/src/display_object/edit_text.rs:959]: thanks！ I misunderstood the hscroll and scroll_offset fields. The reason I'm looking for auto-sized text is because the PADDING pixel translation is done when rendering the glyphs. Can I re-modify like below to do PADDING pixel scaling to glyphs. I tested some text and it works fine. I'm not sure I understand that correctly.
`            let glyph_scale = (1.0 - Self::INTERNAL_PADDING / edit_text.bounds.width().to_pixels() ) as f32;
            context.transform_stack.push(&Transform {
                matrix: Matrix::scale(glyph_scale, glyph_scale),
                ..Default::default()
            });`

**Review by Herschel — CHANGES_REQUESTED** [review]
Thank you, and welcome!

This change means the text would change size as a text field shrinks or grows, which isn't correct -- the text should always be a consistent size regardless of the dimensions of the text field. `autoSize` only affects the dimensions of the text field, not the size of the font itself. Here's an example SWF that decrement a textfield's `_width`:
[tf_width.zip](https://github.com/ruffle-rs/ruffle/files/8310510/tf_width.zip)
Notice with this change in Ruffle, the text suddenly becomes smaller as the text field shrinks.

I suspect the issue with #4051 is cause by either the glyph positioning being slightly incorrect, or by autoSize resulting in textfield dimension's being slightly too small.

**Comment by adrian17** [comment]
(personally I think `INTERNAL_PADDING` is applied wrongly - maybe it's too big, or maybe it should be different horizontally and vertically - I didn't get to test it though. See: several approx tests being off by a multiple of INTERNAL_PADDING.)

**Comment by Herschel** [comment]
Padding was not being added to the autosize calculations.

**Comment by yellow-shrimp** [comment]
I checked the text font width calculation process again today and found that the calculation process is correct, the reason is due to PADDING. Prepare to increase the width of the text edit box of the PADDING size. Thank you for doing this.
