### PR TITLE
avm2: Use an empty string as the prefix for xmlns=

### LINKED ISSUE #16340: express delivery - can't enter the level
### Describe the bug

black screen

https://github.com/ruffle-rs/ruffle/assets/98996990/cfbd77ca-99b8-445f-b2fb-9b6d78f052d9

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/a7c4cf97-a139-47fe-865c-c8fc7baeb0a2

### Content Location

[express-delivery.zip](https://github.com/ruffle-rs/ruffle/files/15324097/express-delivery.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by evilpie**
Fixes #16340

### CODE REVIEW

File: core/src/avm2/e4x.rs [hunk 1]
```diff
@@ -1019,7 +1019,7 @@ impl<'gc> E4XNode<'gc> {
                     if &*name == b"xmlns" {
                         namespaces.push(E4XNamespace {
                             uri: value,
-                            prefix: None,
+                            prefix: Some(AvmString::default()),
```
Comment (adrian17) [inline core/src/avm2/e4x.rs:1022]: `"".into()`?

**Review by adrian17 — APPROVED** [review]
