### PR TITLE
avm1: Implement XMLSocket + Subsystem fixes

### LINKED ISSUE #288: Actionscript Tracking: XMLSocket
This is the tracking issue for **XMLSocket** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
## "Property Exists"
This means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# XMLSocket
### `setTimeout()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `XMLSocket()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `timeout : Number`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `close()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `connect(url, port)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `send(data)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `onClose()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `onConnect(success)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `onData(src)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `onXML(src)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### PR DESCRIPTION
**Pull request by sleepycatcoding**
This PR implements XMLSocket for AVM1.

Supersedes #8188, #5160

Closes #288

~~This is a draft, because I haven't added tests and haven't tested this yet.~~

- [x] Add tests

### CODE REVIEW

File: core/src/socket.rs [hunk 1]
```diff
@@ -14,15 +22,22 @@ use std::{
 
 pub type SocketHandle = Index;
 
+#[derive(Copy, Clone, Collect)]
+#[collect(no_drop)]
+enum SocketKind<'gc> {
+    Avm2(SocketObject<'gc>),
+    Avm1(Object<'gc>),
```
Comment (Lord-McSweeney) [inline core/src/socket.rs:29]: It might be nice to import `Object` as `Avm1Object`, to avoid confusion in other parts of this file.

**Comment by sleepycatcoding** [comment]
Ready for review, I added some tests and they pass, but this has not been tested on any real content.

**Review by Dinnerbone — APPROVED** [review]
Looks good to me! Thank you!

File: core/src/socket.rs [hunk 2]
```diff
@@ -111,100 +160,218 @@ impl<'gc> Sockets<'gc> {
...
+
+                                let message = AvmString::new_utf8_bytes(activation.gc(), &message);
+
+                                let _ = target.call_method(
+                                    "onData".into(),
+                                    &[message.into()],
+                                    &mut activation,
+                                    ExecutionReason::Special,
+                                );
+                            }
```
Comment (Minigugus) [inline core/src/socket.rs:336]: If more than 1 null byte arrives in the same message, you'll miss it until the next message from the server. In my change request I didn't had this issue because I was polling the socket back-end, I did it that way to have at most 1 message fired per update, but in your case this code runs only once per chunk of data received so you risk to miss some messages in some racy conditions.

```suggestion
                            let mut buffer = xml_socket.read_buffer();
                            buffer.extend(data);

                            // Check for a message.
                            while let Some((index, _)) =
                                buffer.iter().enumerate().find(|(_, &b)| b == 0)
                            {
                                let message = buffer.drain(..index).collect::<Vec<_>>();
                                // Remove null byte.
                                let _ = buffer.drain(..1);

                                let message = AvmString::new_utf8_bytes(activation.gc(), &message);

                                let _ = target.call_method(
                                    "onData".into(),
                                    &[message.into()],
                                    &mut activation,
                                    ExecutionReason::Special,
                                );
                            }
```

**Review by Minigugus — COMMENTED** [review]
Well done, you clearly did better than me! :grin:

File: core/src/socket.rs [hunk 3]
```diff
@@ -111,100 +160,218 @@ impl<'gc> Sockets<'gc> {
...
                         // Socket must have been closed before we could send event.
                         None => continue,
                     };
 
-                    let connect_evt =
-                        EventObject::bare_default_event(&mut activation.context, "connect");
-                    Avm2::dispatch_event(&mut activation.context, connect_evt, target.into());
+                    match target {
+                        SocketKind::Avm2(target) => {
+                            let mut activation = Avm2Activation::from_nothing(context.reborrow());
```
[the remark this answers is not in the document]
Comment (sleepycatcoding) [reply core/src/socket.rs:193]: It is used in multiple places in Ruffle for constructing events and firing them. For example: https://github.com/ruffle-rs/ruffle/blob/5f200dc2a9fd992575c4bb5c49973f203cccf43a/core/src/loader.rs#L1317 and https://github.com/ruffle-rs/ruffle/blob/5f200dc2a9fd992575c4bb5c49973f203cccf43a/core/src/loader.rs#L1714

File: core/src/socket.rs [hunk 4]
```diff
@@ -111,100 +160,218 @@ impl<'gc> Sockets<'gc> {
...
-        if let Some(Socket { sender, .. }) = self.sockets.remove(handle) {
+        if let Some(Socket { sender, target }) = self.sockets.remove(handle) {
             drop(sender); // NOTE: By dropping the sender, the reading task will close automatically.
+
+            // Clear the read buffer if the connection was closed.
+            if let SocketKind::Avm1(target) = target {
+                let target = XmlSocket::cast(target.into()).expect("target should be XmlSocket");
+
+                target.read_buffer().clear();
+            }
```
[the remark this answers is not in the document]
Comment (sleepycatcoding) [reply core/src/socket.rs:171]: That is a oversight. Good catch!

File: core/src/socket.rs (hunk 2 above)
Comment (sleepycatcoding) [reply core/src/socket.rs:336]: Good catch!

File: core/src/socket.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Minigugus) [reply core/src/socket.rs:193]: Does that mean the documentation is wrong, or theses samples should be fixed too? (Or I'm miss interpreting the documentation :sweat_smile:)

[the remark this answers is not in the document]
Comment (sleepycatcoding) [reply core/src/socket.rs:193]: To be honest, I don't know.

File: core/src/socket.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (sleepycatcoding) [reply core/src/socket.rs]: Fixed in latest commit!

**Comment by sleepycatcoding** [comment]
I found a bug myself where connected was returning `true` after server closed the connection, and it was because the socket was not removed from the Arena. I added a test case for this.

File: core/src/socket.rs (hunk 2 above)
Comment (sleepycatcoding) [reply core/src/socket.rs]: Fixed in the latest commit.

File: core/src/socket.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (sleepycatcoding) [reply core/src/socket.rs]: The same bug also existed in AVM2 XMLSocket.

File: core/src/avm1/globals/xml_socket.rs [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+    args: &[Value<'gc>],
+) -> Result<Value<'gc>, Error<'gc>> {
+    if let Some(xml_socket) = XmlSocket::cast(this.into()) {
+        let timeout = args
+            .get(0)
+            .unwrap_or(&Value::Undefined)
+            .coerce_to_u32(activation)?;
+
+        // FIXME: Check if flash player clamps this to 250 like AS3 sockets.
+        xml_socket.0.timeout.set(timeout);
```
Comment (Minigugus) [inline core/src/avm1/globals/xml_socket.rs:88]: Consistency: there's a `socket.set_timeout()` in Avm2 code and a `timeout()` on `XmlSocket` just above, maybe a `xml_socket.set_timeout()` makes sens? By the way the clamping could be added in this function in the future if needed :slightly_smiling_face: 

```suggestion
        xml_socket.set_timeout(timeout);
```

File: core/src/socket.rs [hunk 6]
```diff
@@ -111,100 +160,229 @@ impl<'gc> Sockets<'gc> {
...
+                SocketKind::Avm1(target) => {
+                    let target =
+                        XmlSocket::cast(target.into()).expect("target should be XmlSocket");
+
+                    target.read_buffer().clear();
+                }
+                SocketKind::Avm2(target) => {
+                    target.read_buffer().clear();
+                    target.write_buffer().clear();
+                }
```
Comment (Minigugus) [inline core/src/socket.rs:177]: It first I thought `target.write_buffer().clear()` was missing, but it's actually on purpose as the write buffer isn't used by the Avm1 XML socket. Is it worth trying to move this buffer to the Avm2-only code? Or to add a comment to explain the purpose of the writer buffer? I don't know if it's how much Ruffle team cares about that

**Review by Minigugus — APPROVED** [review]
Nice, thanks!

LGTM even with theses 2 comments :slightly_smiling_face:

File: core/src/socket.rs (hunk 6 above)
Comment (sleepycatcoding) [reply core/src/socket.rs:177]: The reason that Avm2 Socket has a write buffer is because generally data is not sent out until the flush() method is called and at that point we empty out the buffer and send it out. But with XMLSocket we send the data out immediately, so there is no need to buffer the data.

**Comment by Minigugus** [comment]
If found a panic while trying this PR:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', core/src/avm1/globals/xml_socket.rs:40:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5core/src/avm1/globals/xml_socket.rs:40:28
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: ruffle_core::socket::Sockets::close
   4: ruffle_core::avm1::globals::xml_socket::close
   5: ruffle_core::avm1::function::Executable::exec
   6: ruffle_core::avm1::object::TObject::call_method
   7: <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method
```

The problematic code is

https://github.com/sleepycatcoding/ruffle/blob/0864967b0d613dfbcaedf26a2694c6275b343484/core/src/avm1/globals/xml_socket.rs#L39-L41

I guess the swf I tried used to close the socket in the onData or onXML event, which can be quite frequent when using sockets. You should probably drop mutable references before running Avm code. I haven't looked at the code but Avm2 might be affected too :confused:

**Comment by sleepycatcoding** [comment]
I think I understand where the issue is. Going to fix it later.

**Comment by sleepycatcoding** [comment]
> I guess the swf I tried used to close the socket in the onData or onXML event, which can be quite frequent when using sockets. You should probably drop mutable references before running Avm code. I haven't looked at the code but Avm2 might be affected too :confused: 

AVM2 should not be affected, as the Socket API there only dispatches one socketData event with how many bytes were received. The event handler then must read the bytes manually with readByte, readBytes and etc

**Comment by sleepycatcoding** [comment]
> If found a panic while trying this PR:

Can you try again with latest commit. It should be fixed.

**Comment by Minigugus** [comment]
No panic this time, seams fixed, thanks :+1:

File: core/src/socket.rs [hunk 7]
```diff
@@ -111,100 +160,238 @@ impl<'gc> Sockets<'gc> {
...
+                            drop(buffer);
+
+                            for message in messages {
+                                let _ = target.call_method(
+                                    "onData".into(),
+                                    &[message.into()],
+                                    &mut activation,
+                                    ExecutionReason::Special,
+                                );
+                            }
```
Comment (Minigugus) [inline core/src/socket.rs:352]: I was think of a better way to process messages without using 2 loops and an extra Vec, what about this code? I think it is more efficient as it only consider null bytes in `data`, in order to have a complexity of `O(data.len())` instead of `O(read_buffer.len())`

```suggestion
                            let mut data = data;

                            if let Some((index, _)) = data.iter().enumerate().find(|(_, &b)| b == 0)
                            {
                                // There's no null byte in the read buffer so we can be sure
                                // all remaining bytes will be consumed by the next message.
                                let mut buffer = xml_socket
                                    .read_buffer()
                                    .drain(..)
                                    .chain(data.drain(..index))
                                    .collect::<Vec<_>>();

                                loop {
                                    // Remove null byte.
                                    let _ = data.drain(..1);

                                    let message =
                                        AvmString::new_utf8_bytes(activation.gc(), &buffer);

                                    let _ = target.call_method(
                                        "onData".into(),
                                        &[message.into()],
                                        &mut activation,
                                        ExecutionReason::Special,
                                    );

                                    if let Some((index, _)) =
                                        data.iter().enumerate().find(|(_, &b)| b == 0)
                                    {
                                        // We already consumed everything in the buffer so arriving here
                                        // means the next message is fully in data only, no need to access
                                        // the buffer again then.
                                        buffer = data.drain(..index).collect::<Vec<_>>();
                                    } else {
                                        // No full message left in data, we'll wait for the next chunk
                                        // from the server.
                                        break;
                                    }
                                }
                            };

                            // Append what remain to XmlSocket read buffer.
                            // Since we consumed all null byes above, we can be sure
                            // the read buffer will never contain one.
                            if !data.is_empty() {
                                xml_socket.read_buffer().extend(data);
                            }

```

Obviously it's just a suggestion, your code works too :+1:

Comment (Minigugus) [inline core/src/socket.rs:352]: If the socket gets closed when multiple messages are still pending in `messages`, we'll still call `onData` even if user's code asked to close the socket.

```suggestion
                            for message in messages {
                                let _ = target.call_method(
                                    "onData".into(),
                                    &[message.into()],
                                    &mut activation,
                                    ExecutionReason::Special,
                                );
                                
                                // Drop remaining messages if the socket was closed.
                                if !context.sockets.sockets.contains(handle) {
                                    break;
                                }
                            }
```

**Review by Minigugus — COMMENTED** [review]
I would have been happy to contribute myself but I don't have time yet :disappointed: Anyway you did an amazing job, thanks again! :slightly_smiling_face:

File: core/src/socket.rs (hunk 7 above)
Comment (sleepycatcoding) [reply core/src/socket.rs:352]: Not sure what Flash's behavior here is at this point, but I think we can leave it like this for now and change it in the future if it becomes a problem.

Comment (sleepycatcoding) [reply core/src/socket.rs:352]: It does hinder code readability, but I think the  current way is performant enough.

Comment (sleepycatcoding) [reply core/src/socket.rs]: I thought about this, for a bit and implemented your suggestion in [8037eff](https://github.com/ruffle-rs/ruffle/pull/12489/commits/8037eff6e3755ed88dcfa9e164b29765cfbc6046)

**Review by Dinnerbone — APPROVED** [review]
Thanks for adding tests too!
