### PR TITLE
web: Fix compatibility with Rocket Loader

### LINKED ISSUE #2254: Incompatible With Cloudflare's Rocket Loader?
This seems like it probably isn't a Ruffle issue _as such_, but I'm afraid I don't know enough about what's going on to say for sure (and a Ruffle developer may be better placed to report the issue to Cloudflare if the problem is on their end).

Basically, when Ruffle is used on a site with Cloudflare's "Rocket Loader" feature enabled, it doesn't work; the script appears to download without issue (no errors), but it doesn't load the .wasm file and polyfill as expected.

In case it helps, I've left my test files in place so you can try this for yourself. The first URL has Rocket Loader disabled and works as expected, the second has Rocket Loader enabled and should demonstrate the SWF failing to load as expected:
https://wartorngalaxy.com/ruffle_test/index.html
https://wartorngalaxy.com/ruffle_test_rocket/index.html

The domain isn't important, it's just an old domain I never got rid of and was convenient for testing on.

### PR DESCRIPTION
**Pull request by n0samu**
Cloudflare's Rocket Loader script [prevents the DOMContentLoaded event from firing](https://dev.to/hollowman6/solution-to-missing-domcontentloaded-event-when-enabling-both-html-auto-minify-and-rocket-loader-in-cloudflare-5ch8), which was preventing Ruffle's public API from initializing. Work around this by listening for the `readystatechange` event instead.

Fixes #2254 and #6583.

### CODE REVIEW

**Review by Herschel — APPROVED** [review]
LGTM, thank you! Could someone a little more savvy with web things review this as well?

**Comment by danielhjacobs** [comment]
It might be worth noting there is a loading state between loading and complete: interactive. See https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState. Still, doing the immediate initialization only when the document's readyState is complete is probably better anyway.

File: web/packages/core/src/public-api.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class PublicAPI {
         }
 
         if (document.readyState === "loading") {
-            window.addEventListener("DOMContentLoaded", this.init.bind(this));
+            document.addEventListener("readystatechange", this.init.bind(this));
```
Comment (relrelb) [inline web/packages/core/src/public-api.ts:86]: Maybe worth meintioning in a comment that `DOMContentLoaded` isn't used because of Rocket Loader (as you did in earlier commits)?

**Review by relrelb — APPROVED** [review]
LGTM!

**Comment by Herschel** [comment]
Thank you!
