### PR TITLE
 avm2: Stub DisplayObject.metaData 

### LINKED ISSUE #15473: Hazel Eyes
### Describe the bug

The game is loading correctly, but after pressing "EASY" or any other game mode, it will return an error:

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x17d1ce0 }) to handler FunctionObject(FunctionObject { ptr: 0x1150e650, name: Ok("hoolib.fx::ScreenFader/continueFade()") }) : ReferenceError: Error #1056: Cannot create property metaData on flash.display.Sprite.`

### Expected behavior

To load and run the game correctly.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=archive/4/LittleCharmers/hazelEyes.swf&params=&name=Hazel%20Eyes)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

No flash file online.

### PR DESCRIPTION
**Pull request by evilpie**
Fixes #15473. This is still marked as a stub because I didn't add support for actually using the AMF data from the PlaceObject4 tag.

### CODE REVIEW

File: core/src/display_object.rs [hunk 1]
```diff
@@ -225,6 +225,8 @@ pub struct DisplayObjectBase<'gc> {
     /// The display object we are currently masking.
     maskee: Option<DisplayObject<'gc>>,
 
+    meta_data: Option<Avm2Object<'gc>>,
```
Comment (Lord-McSweeney) [inline core/src/display_object.rs:228]: For the future, are we sure that this isn't `Avm2Value` and not `Avm2Object`?

**Review by Lord-McSweeney — APPROVED** [review]
