### PR TITLE
avm2: Partial implementation of Loader.unload

### LINKED ISSUE #9901: How To Raise A Dragon: Infinitely looping Armor Games intro
### Describe the bug

Tested on Ruffle Nightly 2023-03-07
How To Raise A Dragon SWF used: [502747_dragon202c.zip](https://github.com/ruffle-rs/ruffle/files/10906447/502747_dragon202c.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/223351566-72bceee9-0591-4e8b-b7a4-5d7075378370.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/223352548-67ca9e51-68e8-49d8-82b5-8fb0389c93a3.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

### Additional information

_No response_

### LINKED ISSUE #10960: Texas Hold'em Poker Heads Up - Intro Loop with Error
### Describe the bug

https://www.spiele-umsonst.de/azad/downloads/flashgames/texasholdempokerheadsup.swf - See here to get this error and intro loop 

Error dispatching event EventObject(EventObject { type: "timer", class: flash.events::TimerEvent, ptr: 0x14ac074 }) to handler FunctionObject(FunctionObject { ptr: 0x14ac304 }) : Error: flash.display.Loader.unload - not yet implemented

### Expected behavior

Load and Run

### Affected platform

Online demo

### Operating system

All

### Browser

All

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Progresses #10960 and #9901- the clips now get unloaded, but sound continues playing because <s>the AS2 code to stop the sound never gets executed (mixed AVM).</s>the clips continue looping, even when being orphans.

### CODE REVIEW

**Comment by n0samu** [comment]
This doesn't fully fix either issue; the intro sounds continue to loop after the clips are no longer visible. But it's an improvement so I'll take it! 👍

File: core/src/avm2/globals/flash/display/loader.rs [hunk 1]
```diff
@@ -190,3 +190,17 @@ pub fn load_bytes<'gc>(
...
     Ok(Value::Undefined)
 }
+
+pub fn unload<'gc>(
+    activation: &mut Activation<'_, 'gc>,
+    this: Option<Object<'gc>>,
+    _args: &[Value<'gc>],
+) -> Result<Value<'gc>, Error<'gc>> {
+    // TODO: Broadcast an "unload" event on the LoaderInfo and reset LoaderInfo properties
+    let _ = crate::avm2::globals::flash::display::display_object_container::remove_child_at(
```
Comment (Aaron1011) [inline core/src/avm2/globals/flash/display/loader.rs:200]: Can you add a `stub_method` call?

**Comment by Lord-McSweeney** [comment]
The sound remaining occurs because the AS2 code that is supposed to `stop()` the frames doesn't get called (since the outer SWF is AVM2 but the inner one of AVM1).

**Comment by n0samu** [comment]
That's not accurate, at least for #10960. Its only `stop()` action is on frame 60 of sprite 9, and all that does is prevent the "Free Internet Games to the Max" text clip from repeating. It doesn't affect the main clip (or the sound) at all.

**Review by Aaron1011 — APPROVED** [review]
