### PR TITLE
web: Avoid triggering cloudflare checks

### LINKED ISSUE #10037: Extension conflicts with Cloudflare site protection
### Describe the bug

When Ruffle extension is enabled in a browser, it breaks "Verify that you are human" bot blocker on some sites (e.g. `chat.openai.com`).

The verification process is stuck in an infinite loop of `"Click 'Verify'" -> "Wait for page to reload" -> "Click it again"`

### Expected behavior

1. Enable Ruffle
2. Go to Cloudflare-protected site
3. Verification passes, site works

### Affected platform

Browser's extension

### Operating system

Ubuntu 20.04

### Browser

Google Chrome 108.0

### Additional information

Checked in every possible case (e.g. with or without other extensions, with or without strict privacy browser prefrences, with or without chrome flags), everything leads to Ruffle extension breaking Cloudflare protected sites.

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
This should fix #10037 (at least, for cloudflare protection).

### CODE REVIEW

File: web/packages/core/src/plugin-polyfill.ts [hunk 1]
```diff
@@ -46,7 +46,9 @@ class RuffleMimeTypeArray implements MimeTypeArray {
     }
 
     item(index: number): MimeType {
-        return this.__mimeTypes[index]!;
+        // This weird modulo behavior is done to emulate
+        // the behavior of browsers.
+        return this.__mimeTypes[index % 2 ** 32]!;
```
Comment (Herschel) [inline web/packages/core/src/plugin-polyfill.ts:51]: I wonder if this would be more accurate as `index>>>0` to more closelt match the 32-bit int behavior.

**Comment by Herschel** [comment]
Thanks for looking into this!

File: web/packages/core/src/plugin-polyfill.ts (hunk 1 above)
Comment (n0samu) [reply web/packages/core/src/plugin-polyfill.ts:51]: Hmm... testing this out, `navigator.plugins[-(2**32) + 1]` returns `undefined`, but if it behaved how you suggest, it would return the second element of the PluginArray.

Comment (Herschel) [reply web/packages/core/src/plugin-polyfill.ts:51]: `navigator.plugins.items[-(2**32) + 1]` returns the second element on my end -- raw access of the array `navigator.plugins[2**32]` does not work

Comment (n0samu) [reply web/packages/core/src/plugin-polyfill.ts:51]: Ah, makes sense! 👍

**Review by Herschel — APPROVED** [review]
