### PR TITLE
web: Allow extra MIME types in the polyfill

### LINKED ISSUE #11050: Ruffle extension does not work on Tooli's Classic Games site
### Describe the bug

Example game page: https://www.tooli.co.kr/flash/472106

The Ruffle extension does not load on pages of the Tooli's Classic Games site. It seems like some JavaScript on the page is interfering, but I have not been able to confirm/diagnose this yet.

### Expected behavior

Flash games should load and play like they do on other sites.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Edge 113

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Toad06**
Closes #11050, by making the polyfill more lenient with the "application/octet-stream" and "binary/octet-stream" MIME types, as suggested by @n0samu in https://github.com/ruffle-rs/ruffle/issues/11050#issuecomment-1547507019.

### CODE REVIEW

File: web/packages/core/src/ruffle-embed.ts [hunk 1]
```diff
@@ -133,31 +133,36 @@ export class RuffleEmbed extends RufflePlayer {
...
         // Check for MIME type.
-        const type = elem.getAttribute("type");
+        const isSwf = isSwfFilename(src);
         if (!type) {
             // If no MIME type is specified, polyfill if movie is an SWF file.
-            return isSwfFilename(elem.getAttribute("src"));
+            return isSwf;
         } else {
-            return isSwfMimeType(type);
+            return isSwfMimeType(type, isSwf);
```
Comment (relrelb) [inline web/packages/core/src/ruffle-embed.ts:165]: Looks like `isSwfMimeType()` is always called as `isSwfMimeType(mimeType, isSwfFilename(url))`. 

Does it make sense to simply unify them to a single function? Something like:
```ts
export function isSwf(url: string, mimeType?: string): boolean { ... }
```
Under the hoods there still can exist 2 separate functions, I talk about the exported interface.

**Review by n0samu — APPROVED** [review]
Looks perfect, thank you!
