### PR TITLE
avm2: Implement Dxns and DxnsLate opcodes

### LINKED ISSUE #13807: Free Kicks Striker: Unknown AVM2 opcode: DxnsLate
### Describe the bug

The game is stuck on loading. Current error:

```
ERROR ruffle_core::avm2::activation: Unknown AVM2 opcode: DxnsLate
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "context3DCreate", class: flash.events::Event, ptr: 0x18e916c0560 }) to handler FunctionObject(FunctionObject { ptr: 0x18e916928a0 }) : RustError("Unknown op")
```

SWF URL - https://www.gamesflare.com/games/2013-1/free-kicks-striker.swf

Test - https://github.com/ruffle-rs/ruffle/issues/12355

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Another specimen from the graveyard.

Fixes #13807, supersedes #21014

### CODE REVIEW

File: core/src/avm2/function.rs [hunk 1]
```diff
@@ -209,6 +211,9 @@ pub fn exec<'gc>(
                 caller_domain,
                 caller_movie,
             );
+            // Native methods always inherit the caller's default XML namespace,
+            // since they can't set their own via dxns opcodes.
+            activation.set_default_xml_namespace(caller_dxns);
```
Comment (adrian17) [inline core/src/avm2/function.rs]: Why not pass `caller_dxns` to `Activation::from_builtin` directly?

(and same below in `init_from_method`)

File: core/src/avm2/activation.rs [hunk 2]
```diff
@@ -2574,14 +2601,26 @@ impl<'a, 'gc> Activation<'a, 'gc> {
...
+        let value = self.pop_stack();
+        let uri = value.coerce_to_string(self)?;
+
+        self.set_dxns(uri);
+
+        Ok(())
+    }
+
+    fn set_dxns(&mut self, uri: AvmString<'gc>) {
+        self.default_xml_namespace = Some(uri);
```
Comment (adrian17) [inline core/src/avm2/activation.rs:2616]: this can probably be inlined now :D

**Review by adrian17 — APPROVED** [review]

**Comment by SuchAFuriousDeath** [comment]
I messed up the authorship when working on addressing the review. Don't merge this yet, give me a sec.
EDIT: It's fine now

**Comment by SuchAFuriousDeath** [comment]
Jeez.
image

**Comment by torokati44** [comment]
Thanks for taking care of that too!
