### PR TITLE
avm1: Don't allow for looking up with an empty name when children don't have an explicit name set

### LINKED ISSUE #12253: Bubble Dive: Stage scrolling issues after 2023-07-20 build
### Describe the bug

In **Bubble Dive**(Korean game, originally titled '버블 다이브'), When a stage begins, the goal of the game is for the character to step on a scaffold to descend down the stage. However, the moment the character descends, the interface and all game screens move upward instead of remaining stationary.

[bubble-dive.zip](https://github.com/ruffle-rs/ruffle/files/12138136/bubble-dive.zip)

This issue is very similar to the following issue that was resolved in the past: https://github.com/ruffle-rs/ruffle/issues/4117

This worked fine until Ruffle Nightly 2023-07-19, but started to break on [2023-07-20](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-07-20) build.

### (Working) Ruffle Nightly ~2023-07-19
https://github.com/ruffle-rs/ruffle/assets/75052171/37504eba-4926-4789-9a23-ec7189a92deb

### (Not Working) Ruffle Nightly 2023-07-20~
https://github.com/ruffle-rs/ruffle/assets/75052171/6c45083f-217f-49f1-95c3-15b6ac220a34

### Expected behavior

The game interface shouldn't affect the game.

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Google Chrome 115

### Additional information

_No response_

### LINKED ISSUE #12877: Amorphous+ not playable
### Describe the bug

Game is not playable because it doesn't respond to mouse movement or clicks once in a game (the menu is navigable with a mouse).  https://jayisgames.com/games/amorphous/

### Expected behavior

the character follows the mouse cursor in the game and swings the weapon when you click

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Chrome 116

### Additional information

_No response_

### LINKED ISSUE #12961: Regression? - Fishdom - Goes black throws GameFont error
### Describe the bug

This game worked fine before but now some errors appear and the game goes black after the loading screen. Dunno what caused it but must have been with the latest built since around 1 week.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/fishdom.swf
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character MGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character CGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character YGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character YGameFont
ruffle_web-wasm_extensions.js:719

### Expected behavior

Run again

### Affected platform

Desktop app

### Operating system

All

### Browser

All

### Additional information

_No response_

### LINKED ISSUE #13210: Inspector Wombat: after 2023-07-20 nightly, the main menu is not clickable.
### Describe the bug

[inspector-wombat.zip](https://github.com/ruffle-rs/ruffle/files/12640301/inspector-wombat.zip)

In the game **'Inspector Wombat'**, the main menu is not clickable.  As a result, i can't start the game.
This was not an issue up until Ruffle Nightly `2023-07-19`, but since the `2023-07-20` build it has been a problem.
(Tested on desktop build, self-hosted build)

In Adobe Flash Player, the mouse cursor appears as a regular cursor, and clicking on a menu takes you to that screen without any problems.

However, in Ruffle, the mouse cursor looks like the photo below. When you hover over the menu, a weird blue square appears, which is not visible in the original. Subsequent clicks on the menu are unresponsive.

image

Here are the changes from Nightly `2023-07-20`:

image

### Expected behavior

Clicking on the main menu should work.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 117

### Additional information

_No response_

### LINKED ISSUE #14369: Another Mission - Regression where Flash Forward 2021 game no longer works.
### Describe the bug

Ruffle:Another Mission was created for Flash Forward 2021 and it ran fine at the time. Something since then has caused it to not work.

Once you get past the intro, the game appears to be a blank screen with the tutorial instructions visible. The HUD movies around when you press ASDW but you can't see the actual player or level.

image

### Expected behavior

Expected behavior is to see the player and level.

### Content Location

https://www.newgrounds.com/portal/view/782076

### Affected platform

Self-Hosted Web

### Operating system

Windows 11

### Browser

Chrome Version 119.0.6045.160

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #14369
Fixes #13210
Fixes #12961
Fixes #12877
Fixes #12253

### CODE REVIEW

File: core/src/display_object.rs [hunk 1]
```diff
@@ -1498,6 +1498,9 @@ pub trait TDisplayObject<'gc>:
     fn name(&self) -> AvmString<'gc> {
```
Comment (evilpie) [inline core/src/display_object.rs:1498]: It might be cleaner to return `Option<AvmString<'gc>>` here instead.

File: core/src/display_object/container.rs [hunk 2]
```diff
@@ -793,12 +793,17 @@ impl<'gc> ChildContainer<'gc> {
...
+                    .filter(|(_, child)| child.name_optional().map(|n| n == name).unwrap_or(false))
                     .collect::<Vec<_>>()
             } else {
                 self.depth_list
                     .iter()
-                    .filter(|(_, child)| child.name().eq_ignore_case(name))
+                    .filter(|(_, child)| {
+                        child
+                            .name_optional()
+                            .map(|n| n.eq_ignore_case(name))
```
Comment (evilpie) [inline core/src/display_object/container.rs:804]: `map_or`

File: core/src/display_object.rs (hunk 1 above)
Comment (Lord-McSweeney) [reply core/src/display_object.rs:1498]: I was about to do this, then realized that there are several more places where `name` is used with a default of an empty string. I don't know which of those match Flash and which don't, so I decided to keep this default here.

**Comment by Lord-McSweeney** [comment]
I still need to add a test

**Review by Aaron1011 — APPROVED** [review]
