### PR TITLE
avm2: Avoid allocating when calling a method

### LINKED ISSUE #12346: Test Failure: avmplus Exception suite
Completely passing suites are not shown.

## Testsuite `from_avmplus/as3/Statements/Exceptions/MultipleCatchBlocks2`
| Test | Passes? | Expected | Actual |
| ---- | ---- | ---- | ---- |
| Testing catch block with Reference Error | :heavy_check_mark: | | |
| Testing catch block with Type Error | :heavy_check_mark: | | |
| Testing catch block with Argument Error | :x: | `ArgumentError: Error #1063` | `no error` |
| Testing catch block with URIError | :x: | `no error` | `URIError: Error #1052: Inv` |
| Testing catch block with Eval Error | :heavy_check_mark: | | |
| Testing catch block with Range Error | :heavy_check_mark: | | |
| Testing catch block with Error | :heavy_check_mark: | | |

## Testsuite `from_avmplus/as3/Statements/Exceptions/MultipleCatchBlocksArgument`
| Test | Passes? | Expected | Actual |
| ---- | ---- | ---- | ---- |
| Testing catch block with Argument Error | :x: | `ArgumentError: Error #1063` | `no error` |

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
This makes bytecode method calls with `call_method` about 30-40% faster and any other method calls 10-20% faster.

The unchecked function fix closes #12346.

### CODE REVIEW

File: core/src/avm2/activation.rs [hunk 1]
```diff
@@ -378,75 +439,69 @@ impl<'a, 'gc> Activation<'a, 'gc> {
...
 
-        if method.is_unchecked() {
-            let max_args = signature.len();
-            if user_arguments.len() > max_args && !method.is_variadic() {
-                user_arguments = &user_arguments[..max_args];
-            }
-        }
-
-        if user_arguments.len() > signature.len() && !has_rest_or_args {
+        if user_arguments.len() > signature.len() && !has_rest_or_args && !method.is_unchecked() {
```
Comment (adrian17) [inline core/src/avm2/activation.rs:440]: just to be sure, the `is_unchecked()` already includes the `NEED_REST` but `has_rest_or_args` also checks `NEED_ARGUMENTS | NEED_REST` separately, is this indeed correct?

Comment (adrian17) [reply core/src/avm2/activation.rs:440]: Oh, sorry, only now saw that you also changed the definition of `is_unchecked` below. But... couldn't it go the other way? As in, make `is_unchecked()` cover `NEED_ARGUMENTS | NEED_REST`? Since this appears to be the only place that uses this field anyway.

Also, either way, the docstring at `fn is_unchecked` needs updating.

Comment (Lord-McSweeney) [reply core/src/avm2/activation.rs:440]: The change you proposed makes more sense after some of the commits of #20049; I'll add it in a later PR. I've updated the documentation on `is_unchecked`.

**Review by adrian17 — APPROVED** [review]
