### PR TITLE
avm2: Don't panic when accessing loaderInfo.childAllowsParent on root

### LINKED ISSUE #19785: Error on https://armorgames.com/play/17987/learn-to-fly-3
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/loader_info.rs:305:47:
Loader should be Some

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M2, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://armorgames.com/play/17987/learn-to-fly-3?tag-referral=games-of-2016
SWF URL: https://cache.armorgames.com/files/games/learn-to-fly-3-17987.swf?v=1499105677

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2025-03-12
Channel: nightly
Built: 2025-03-12T00:06:38.270Z
Commit: a2c3d5e7dd54ff9a50de1f2c6bf9011237c3b73c
Is extension: true

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 26001285

### LINKED ISSUE #19990: Error on https://armorgames.com/play/17987/learn-to-fly-3
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/loader_info.rs:282:47:
Loader should be Some

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00008A56) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://armorgames.com/play/17987/learn-to-fly-3
SWF URL: https://cache.armorgames.com/files/games/learn-to-fly-3-17987.swf?v=1499105677

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2025-04-01
Channel: nightly
Built: 2025-04-01T00:07:25.318Z
Commit: 6954bb863c7cc2c53dfdf6b4fe05eec355d400e4
Is extension: true

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 26001285

### LINKED ISSUE #20841: Error on https://armorgames.com/play/17987/learn-to-fly-3
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/loader_info.rs:282:47:
Loader should be Some
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/loader_info.rs:282:47:
Loader should be Some
    at Le.e.wbg.__wbg_new_c68d7209be747379 (https://agi.armorgames.com/ruffle/core.ruffle.d7186bd247eb379f4664.js:1:57531)
    at ruffle_web.wasm.js_sys::Error::new::h6d99c1cce3a44e84 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[13055]:0x98f91f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h8bec20ad7264a866 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[10114]:0x94299b)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h1f8226e239ffaa71 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[6646]:0x87aef3)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb6c28595a1feee80 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[11005]:0x95ca3c)
    at ruffle_web.wasm.core::option::expect_failed::h11af64e8891c7176 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[9248]:0x91f8fb)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::loader_info::get_child_allows_parent::hdb4449fc351584f5 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[2834]:0x61b6e6)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h3755c1e8cef29a24 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[1569]:0x42fd56)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::call_method_with_args::h69953cd7635c3c81 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[2302]:0x576868)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::get_property::h8fd6a0d2b43fdfb9 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[1870]:0x4d012a)
```
AVM2 stack:
```
    at flash.display::LoaderInfo/get childAllowsParent()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerCore$/trace()
    at com.demonsters.debugger::MonsterDebugger$/trace()
    at src.api::ArmorGamesInterface$/agiConnectedCallback()
    at com.armorgames::AGI/8!()
    at 20::User/--()
    at com.armorgames.services::=0/callCallback()
    at com.armorgames.services::Client/handleCallResponse()
    at MethodInfo-5()
    at com.armorgames.services::HTTPQueue/""()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features { features_wgpu: FeaturesWGPU(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES), features_webgpu: FeaturesWebGPU(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE) }
Available features: Features { features_wgpu: FeaturesWGPU(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW), features_webgpu: FeaturesWebGPU(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D) }
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_binding_array_elements_per_shader_stage: 0, max_binding_array_sampler_elements_per_shader_stage: 0, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://armorgames.com/play/17987/learn-to-fly-3?fp=b-misc
SWF URL: https://cache.armorgames.com/files/games/learn-to-fly-3-17987.swf?v=1499105677

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: 0.1.0 nightly 2025-06-20
Channel: nightly
Built: 2025-06-20T00:07:07.090Z
Commit: 157f8e0a0aa4b6dd6189a3a2a10d427110071028
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 26001285

### LINKED ISSUE #20858: Error on https://armorgames.com/play/17987/learn-to-fly-3
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/loader_info.rs:282:47:
Loader should be Some
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/loader_info.rs:282:47:
Loader should be Some
    at push.655.Le.e.wbg.__wbg_new_c68d7209be747379 (https://agi.armorgames.com/ruffle/core.ruffle.d7186bd247eb379f4664.js:1:57531)
    at ruffle_web.wasm.js_sys::Error::new::h6d99c1cce3a44e84 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[13055]:0x98f91f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h8bec20ad7264a866 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[10114]:0x94299b)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h1f8226e239ffaa71 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[6646]:0x87aef3)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb6c28595a1feee80 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[11005]:0x95ca3c)
    at ruffle_web.wasm.core::option::expect_failed::h11af64e8891c7176 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[9248]:0x91f8fb)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::loader_info::get_child_allows_parent::hdb4449fc351584f5 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[2834]:0x61b6e6)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h3755c1e8cef29a24 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[1569]:0x42fd56)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::call_method_with_args::h69953cd7635c3c81 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[2302]:0x576868)
    at ruffle_web.wasm.ruffle_core::avm2::value::Value::get_property::h8fd6a0d2b43fdfb9 (wasm://wasm/ruffle_web.wasm-0325c066:wasm-function[1870]:0x4d012a)
```
AVM2 stack:
```
    at flash.display::LoaderInfo/get childAllowsParent()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parseClass()
    at com.demonsters.debugger::MonsterDebuggerUtils$/parse()
    at com.demonsters.debugger::MonsterDebuggerCore$/trace()
    at com.demonsters.debugger::MonsterDebugger$/trace()
    at src.api::ArmorGamesInterface$/agiConnectedCallback()
    at com.armorgames::AGI/8!()
    at 20::User/--()
    at com.armorgames.services::=0/callCallback()
    at com.armorgames.services::Client/handleCallResponse()
    at MethodInfo-5()
    at com.armorgames.services::HTTPQueue/""()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002709) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features { features_wgpu: FeaturesWGPU(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES), features_webgpu: FeaturesWebGPU(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE) }
Available features: Features { features_wgpu: FeaturesWGPU(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW), features_webgpu: FeaturesWebGPU(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D) }
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_binding_array_elements_per_shader_stage: 0, max_binding_array_sampler_elements_per_shader_stage: 0, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://armorgames.com/play/17987/learn-to-fly-3?tag-referral=flash
SWF URL: https://cache.armorgames.com/files/games/learn-to-fly-3-17987.swf?v=1499105677

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 OPR/119.0.0.0 (Edition Yx GX)
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: 0.1.0 nightly 2025-06-20
Channel: nightly
Built: 2025-06-20T00:07:07.090Z
Commit: 157f8e0a0aa4b6dd6189a3a2a10d427110071028
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 26001285

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #20858
Fixes #20841
Fixes #19990
Fixes #19785

### CODE REVIEW

File: core/src/avm2/globals/flash/display/loader_info.rs [hunk 1]
```diff
@@ -279,18 +279,23 @@ pub fn get_child_allows_parent<'gc>(
...
+                    if let Ok(parent_url) = Url::parse(parent_movie.url()) {
+                        if child_url.host() == parent_url.host() {
+                            return Ok(true.into());
+                        }
                     }
                 }
+                Ok(false.into())
+            } else {
+                // Only the root movie is LoaderStream::Swf but missing a loader.
+                // In that case, return true.
```
Comment (kjarosh) [inline core/src/avm2/globals/flash/display/loader_info.rs:297]: As mentioned on Discord, I think we should explicitly check if the SWF is the root SWF, and then unwrap the loader and handle the case when a non-root SWF doesn't have a loader.

File: core/src/avm2/globals/flash/display/loader_info.rs [hunk 2]
```diff
@@ -275,22 +275,28 @@ pub fn get_child_allows_parent<'gc>(
...
+                assert!(dobj.is_root());
```
Comment (kjarosh) [inline core/src/avm2/globals/flash/display/loader_info.rs]: What about root objects of loaded content? Did Ruffle crash there too?

According to my understanding, this applies only to the root SWF loaded by the player, and the assertion asserts also on roots of child loaders.
