### PR TITLE
avm2: Limited XML namespace support

### LINKED ISSUE #10293: Soccer Skill Zone: Blue screen issue
### Describe the bug

https://www.newgrounds.com/portal/view/495537?emulate=flash
Game seems to work up to the point where you start the first level and the gate opens, but it quickly turns into this.

Free Kick Ruffle

Error dispatching event EventObject(EventObject { type: "EVENT_START_LEVEL", class: flash.events::Event, ptr: 0x31e01b8 }) to handler FunctionObject(FunctionObject { ptr: 0x344d6e8 }) : ReferenceError: Error # 1069: Property http ://www .collada.org/2005/11/COLLADASchema::asset not found on XML and there is no default value.

### Expected behavior

Game should work with the gate opening and a soccer ball should drop onto the field.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by evilpie**
This fixes #10293 and #10639.

Probably also needs some manual testing to make sure we aren't regressing games that use XML and currently work.

### CODE REVIEW

**Comment by evilpie** [comment]
This almost passes `from_avmplus/e4x/Expressions/e11_1_1/`, but there is some unrelated issue with:
```
q = new QName(n, "attr1");
q2 = new QName(q, "attr1");
```

I need to figure out how to run all skipped tests and find out new failing and passing tests.

**Comment by torokati44** [comment]
> I need to figure out how to run all skipped tests and find out new failing and passing tests.

Uh, don't we have a magic command for that?

**Comment by Dinnerbone** [comment]
> I need to figure out how to run all skipped tests and find out new failing and passing tests.

It's automatic, if any test suddenly starts working it'll come up as "failing" and tell you to remove the `known_failure` flag.

No new tests pass because of this PR, sorry!

**Comment by n0samu** [comment]
This also makes [Neopets Lost City Lanes](https://www.neopets.com/games/game.phtml?game_id=1108) playable!

**Comment by evilpie** [comment]
Good to know that we still make sure "failing" tests don't suddenly start working.

What I actually meant was that I would be interested in basically the individual changes inside a test. For example for `e11_1_1` the output changed quite a lot, because a lot more asserts now pass.

**Comment by Dinnerbone** [comment]
> What I actually meant was that I would be interested in basically the individual changes inside a test. For example for `e11_1_1` the output changed quite a lot, because a lot more asserts now pass.

Ah okay. No easy bulk way right just, just run the swf in ruffle desktop and see what it says!

File: core/src/avm2/e4x.rs [hunk 1]
```diff
@@ -475,36 +490,58 @@ impl<'gc> E4XNode<'gc> {
...
-                attribute.key.into_inner(),
-            );
+            let (ns, local_name) = parser.resolve_attribute(attribute.key);
+            let namespace = match ns {
+                ResolveResult::Bound(ns) => Some(AvmString::new_utf8_bytes(
+                    activation.context.gc_context,
+                    ns.into_inner(),
+                )),
+                ResolveResult::Unknown(ns) if ns == b"xmlns" => continue,
+                // TODO: Throw error on unknown prefix
```
Comment (Aaron1011) [inline core/src/avm2/e4x.rs:508]: Can you add an `avm2_stub_method!` call here?

Comment (evilpie) [reply core/src/avm2/e4x.rs]: I just went ahead and added the correct errors in the second commit.

File: core/src/avm2/e4x.rs [hunk 2]
```diff
@@ -475,36 +489,82 @@ impl<'gc> E4XNode<'gc> {
...
 
+        let (ns, local_name) = parser.resolve_element(bs.name());
+        let name =
+            AvmString::new_utf8_bytes(activation.context.gc_context, local_name.into_inner());
+        let namespace = match ns {
+            ResolveResult::Bound(ns) => Some(AvmString::new_utf8_bytes(
+                activation.context.gc_context,
+                ns.into_inner(),
+            )),
+            ResolveResult::Unknown(ns) => {
```
Comment (Aaron1011) [inline core/src/avm2/e4x.rs:551]: Should this have the `xml` and `xmlns` cases as well?

Comment (evilpie) [reply core/src/avm2/e4x.rs:551]: I am not sure if `<xmlns:dummy/>` is even valid XML, because `xmlns:` is used as an attribute usually, but when correctly binding the namespace like this it already works: `<x xmlns:xmlns="http://example.org"><xmlns:a></xmlns:a></x>`.

Interestingly Flash might have a bug related to `xml:`. `<xml:a />` works, but `<xml:a></xml:a>` throws
> The element type "a" must be terminated by the matching end-tag "&lt;/a>".

`<xml:a></a>` works! :exploding_head:

Comment (evilpie) [reply core/src/avm2/e4x.rs:554]: So I added support for `xml`, but not `xmlns`, prefixes for elements.

**Review by Dinnerbone — APPROVED** [review]

**Review by Aaron1011 — APPROVED** [review]
