### PR TITLE
avm1: Fix issues with SharedObjects

### LINKED ISSUE #2149: game works with Nightly 2020-12-11 but not with the latest version
game (Locked Cabin AS2) works with Nightly 2020-12-11 but not with the latest version (Nightly 2020-12-28)

error: `ruffle_web_bg.js:1257 SharedObject::get_local: Unable to parse movie URL`

working game (with Nightly 2020-12-11) : https://en.playit-online.de/game/locked-cabin/

image

in the current demo the game restarts again and again:

image

swf file: https://www.playit-online.de/games/adventure/lockedcabin/lockedcabin.swf

### LINKED ISSUE #2150: SharedObject not working with movies loaded from data stream without url
This can happen when you open a local SWF file on the demo website.

If that happens, SwfMovie is created without an URL:

```rust
    pub fn load_data(&mut self, swf_data: Uint8Array, parameters: &JsValue) -> Result<(), JsValue> {
        ...
            let mut movie = SwfMovie::from_data(&data, None) // url=None
```

Later, if the movie tries calling `SharedObject.getLocal`, this happens:

```rust
pub fn get_local<'gc>(
    activation: &mut Activation<'_, 'gc, '_>,
    _this: Object<'gc>,
    args: &[Value<'gc>],
) -> Result<Value<'gc>, Error<'gc>> {
    ...
    let mut movie_url = if let Some(url) = movie.url().and_then(|url| url::Url::parse(url).ok()) {
        url
    } else {
        log::error!("SharedObject::get_local: Unable to parse movie URL");
        return Ok(Value::Null);
    }
```

The value `null` is returned, which means all the property stores and accesses won't work.
This breaks N, which uses the object returned from getLocal as global store of game progress and, more importantly, key bindings - without that, you can't actually move the character.
I can confirm that replacing that piece of code with a dummy URL makes the controls and other default state work.

### PR DESCRIPTION
**Pull request by Herschel**
* Fix incorrect name used for cached SharedObjects (fix #2149)
 * Use dummy URL for SharedObject path when movie URL is unavailable (fix #2150)

Thanks to @Toad06 and @adrian17 for the tips!

### CODE REVIEW

**Comment by Herschel** [comment]
Possibly we should just switch to `MemoryStorageBackend` for SOs in the case that the URL isn't available, too.

File: core/src/avm1/globals/shared_object.rs [hunk 1]
```diff
@@ -179,8 +179,8 @@ pub fn get_local<'gc>(
     let mut movie_url = if let Some(url) = movie.url().and_then(|url| url::Url::parse(url).ok()) {
         url
     } else {
-        log::error!("SharedObject::get_local: Unable to parse movie URL");
```
Comment (adrian17) [inline core/src/avm1/globals/shared_object.rs:182]: (maybe handle "movie.url() is None" and "parsing url failed" cases separately? That would keep the previous check)
