### PR TITLE
avm2: Work towards starting to remove PrimitiveObject

### LINKED ISSUE #11432: Stuck on Dragon Fist 3D's Second Loading Screen
### Describe the bug

http://onemorelevel.com/static/games3/dragon-fist-3d.swf
The first loading screen works fine, but when you click "Play Game," it gets stuck on the second. Spoofing the URL to https://www.kongregate.com and https://benoldinggames.co.uk didn't work either.
The fist error message repeats about 50 times.

WARN ruffle_core::tag_utils: Unknown tag code: 255
WARN ruffle_core::tag_utils: Unknown tag code: 255
WARN ruffle_core::stub: Encountered stub: AVM2 flash.system.Security.allowDomain()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.system.Security.allowInsecureDomain()
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1ec81d744b8 }) to handler FunctionObject(FunctionObject { ptr: 0x1ec8108c488 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: scaleX)
WARN ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys
ERROR ruffle_core::loader: Error during movie loading: FetchError("HTTP status is not ok, got 404 Not Found") 
ERROR ruffle_core::timer: Unhandled AVM2 error in timer callback: ReferenceError: Error #1069: Property prependScale not found on flash.geom.Matrix3D and there is no default value.

### Expected behavior

The second loading screen should finish loading and bring up the main menu.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

Running Nightly 2023-06-08

### LINKED ISSUE #15559: Regular Show: Dimensional Drift [AVM2]
### Describe the bug

The game is not loading, having the following error:

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x15aa860 }) to handler FunctionObject(FunctionObject { ptr: 0x15a9dd0, name: Ok("Main/init()") }) : TypeError: Error #2007: Parameter alphas must be non-null.`

### Expected behavior

To load and work.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=cn/RegularShow/dimensional-drift/game.swf&params=&name=Regular%20Show%20Dimensional%20Drift)

[Flash](https://www.numuki.com/game/dimensional-drift/)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

_No response_

### LINKED ISSUE #17859: FRUIT NINJA HD - game freezes at loading
### Describe the bug

the loading can be completed in flash player with http file server but not in ruffle

### Content Location

[game.zip](https://github.com/user-attachments/files/16962933/game.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #17859, should fix #15559, fixes #11432

This PR
1. Introduces methods on `Value` that allow for doing most only Class-related operations with it without boxing it (commits 1-2)
2. Completely removes `coerce_to_object` outside of core code (commits 3-10)

### CODE REVIEW

File: core/src/avm2/globals/flash/display/bitmap_data.rs [hunk 1]
```diff
@@ -469,7 +469,7 @@ pub fn set_pixels<'gc>(
     args: &[Value<'gc>],
 ) -> Result<Value<'gc>, Error<'gc>> {
     let rectangle = args.get_object(activation, 0, "rect")?;
-    let bytearray = args.get_object(activation, 0, "inputByteArray")?;
```
Comment (adrian17) [inline core/src/avm2/globals/flash/display/bitmap_data.rs]: Move this to the previous commit please (or squash later).

File: core/src/avm2/globals/flash/display/graphics.rs [hunk 2]
```diff
@@ -103,14 +103,18 @@ pub fn begin_gradient_fill<'gc>(
         let gradient_type = args.get_string(activation, 0)?;
         let gradient_type = parse_gradient_type(activation, gradient_type)?;
         let colors = args.get_object(activation, 1, "colors")?;
-        let alphas = args.get_object(activation, 2, "alphas")?;
-        let ratios = args.get_object(activation, 3, "ratios")?;
+        let alphas = args.try_get_object(activation, 2);
+        let ratios = args
+            .try_get_object(activation, 3)
+            .expect("Ratios should never be null");
```
Comment (adrian17) [inline core/src/avm2/globals/flash/display/graphics.rs:109]: FP also permits null here (I think it just calculates the ratios to be equally spaced then).

File: core/src/avm2/globals/flash/display/graphics.rs [hunk 3]
```diff
@@ -1588,17 +1605,17 @@ fn handle_gradient_fill<'gc>(
...
         .get_public_property("colors", activation)?
-        .coerce_to_object(activation)?;
+        .as_object()
+        .ok_or_else(|| make_error_2007(activation, "colors"))?;
 
     let ratios = obj
         .get_public_property("ratios", activation)?
-        .coerce_to_object(activation)?;
+        .as_object()
+        .expect("Ratios should never be null");
```
Comment (adrian17) [inline core/src/avm2/globals/flash/display/graphics.rs:1618]: I didn't check what FP does here (probably either throws or interpolates itself), but I think I can write AS that'll put a null here

File: core/src/avm2/globals/flash/geom/Matrix3D.as [hunk 4]
```diff
@@ -1,749 +1,750 @@
...
-		}
-
-		public function transformVectors(vin:Vector.<Number>, vout:Vector.<Number>):void {
-			if (vin == null) {
-				throw new TypeError("Error #2007: Parameter vin must be non-null.", 2007);
+    import __ruffle__.stub_method;
+
+    public class Matrix3D {
+
+        // The 4x4 matrix data, stored in column-major order
```
Comment (adrian17) [inline core/src/avm2/globals/flash/geom/Matrix3D.as:8]: can you add a comment about it being non-null?

File: core/src/avm2/globals/flash/display/graphics.rs (hunk 2 above)
Comment (Lord-McSweeney) [reply core/src/avm2/globals/flash/display/graphics.rs:109]: I tested and the behavior is pretty strange; it seems like the start of the first gradient is further back than the start of the fill/line. I left it like this so it can be reported it if it ever happens. I'll add a comment for clarity.

File: core/src/avm2/globals/flash/display/graphics.rs (hunk 3 above)
Comment (Lord-McSweeney) [reply core/src/avm2/globals/flash/display/graphics.rs:1618]: See previous review

**Review by adrian17 — APPROVED** [review]
