### PR TITLE
avm2: Clone event on redispatch

### LINKED ISSUE #10130: Zombie Trailer Park - Blue Screen after Loading
### Describe the bug

Hey,

this was a muck liked and played game on my site. It throws some error which ends in a blue screen:

https://www.newgrounds.com/portal/view/555446?emulate=flash

### Expected behavior

No blue screen...

### Affected platform

Online demo

### Operating system

All

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sleepycatcoding**
Fixes #10130 and #10261

### CODE REVIEW

File: core/src/avm2/events.rs [hunk 1]
```diff
@@ -448,10 +453,33 @@ pub fn dispatch_event<'gc>(
         parent = parent_of(par);
     }
 
+    let dispatched = event.as_event().unwrap().dispatched;
+
+    let event = if dispatched {
+        event
+            .call_public_property("clone", &[], activation)?
+            .coerce_to_object(activation)
```
Comment (Lord-McSweeney) [inline core/src/avm2/events.rs:461]: nit: I think `as_object` should be a little faster here, and not require passing down an Activation. You can do `unwrap_or_else` instead of the `map_err`, too.

**Review by adrian17 — APPROVED** [review]
Can you also add one more test? We test for "recursive dispatch", but how about also non-recursive
```
a.dispatchEvent(e);
b.dispatchEvent(e);
```

**Comment by sleepycatcoding** [comment]
> Can you also add one more test? We test for "recursive dispatch", but how about also non-recursive
> 
> ```
> a.dispatchEvent(e);
> b.dispatchEvent(e);
> ```

Expanded the existing test.

**Review by Dinnerbone — APPROVED** [review]
