### PR TITLE
Ignore bad version mark (sometimes used by obfuscators) (close #15006)

### LINKED ISSUE #15006: Panic on https://s1.4399hxjy.com/game.php
### Describe the bug

```
339.js:1038  panicked at core/src/avm2/namespace.rs:50:40:
Bad version mark 58077
```

The mark  0xE294 - 0xE2DD = 0x49 seems to exceed the special case of selecting the API version by index.
https://github.com/ruffle-rs/ruffle/blob/1cf669c75e81654f83e20900a683cdb22e14a6d2/core/src/avm2/namespace.rs#L40C5-L40C44

### Expected behavior

Run the game

### Content Location

https://s1.4399hxjy.com/game.php
Server selection: https://news.4399.com/hxjy/

### Affected platform

Browser's extension

### Operating system

Window 11

### Browser

Edge/Chrome 120

### Additional information

This game is part of a bigger effort to support 4399.com games.
There might be other issues with this website, from how it handles Flash checks and many CORS issues.
Unfortunately, some games cannot be easily debugged on desktop because the swf download other swf or do requests while logged in.

**If Ruffle is not detected try to reload the page multiple times because of the known race condition on the Flash check. To avoid refreshing try this Tampermonkey user script [一键下载 flash 游戏 (greasyfork.org)](https://greasyfork.org/en/scripts/445006-%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD-flash-%E6%B8%B8%E6%88%8F)**

To solve these issues refers to previous issues such as:

- https://github.com/ruffle-rs/ruffle/issues/13943#issuecomment-1835074616 - Race condition discussion
- https://github.com/ruffle-rs/ruffle/issues/14578#issuecomment-1873523939 - Ruffle detection issue
- Edge/Chrome flag to temporarily disable CORS `--disable-web-security` or use https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf
- Disable antidebugging with https://greasyfork.org/en/scripts/440060-anti-anti-debugger/code or Deactivate breakpoint
- Disable second antidebugging manually 
fadb9686-1ce4-406b-9694-42b97842ee35

### PR DESCRIPTION
**Pull request by wsxarcher**
Some obfuscators use random mark on all the object. Ignore them as avmplus does otherwise some things won't run.
Example #15006

### CODE REVIEW

File: core/src/avm2/namespace.rs [hunk 1]
```diff
@@ -153,10 +155,8 @@ impl<'gc> Namespace<'gc> {
...
             if let Some((stripped, version)) = stripped {
-                assert!(
-                    is_playerglobals,
-                    "Found versioned url {namespace_name:?} in non-playerglobals domain"
-                );
+                // Ignore if versioned url is in non-playerglobals domain as avmplus does
+                // https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/AbcParser.cpp#L1510
                 let stripped_string = AvmString::new(context.gc_context, stripped);
                 namespace_name = context.interner.intern(context.gc_context, stripped_string);
                 api_version = version;
```
Comment (Aaron1011) [inline core/src/avm2/namespace.rs:162]: This will set the api version to the value parsed from the mark, which isn't correct.
