### PR TITLE
avm2: Account for shared slot_id/disp_id numbering space in slot hole check

### LINKED ISSUE #23143: The Enchanted Cave 2: The ABC data is corrupt
### Describe the bug

The game won't start, I only see a white screen and the following errors:

```
ERROR core/src/avm2.rs:688 Error loading AVM2 ABC: VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.
ruffle_web.js:2149 ERROR core/src/avm2.rs:688
Error attempting to lookup AVM2 symbol class: ReferenceError: Error #1065: Variable boot_b065 is not defined.
....
```

### Expected behavior

Start the game

### Content Location

PLAY Online - https://www.gameflare.com/online-game/the-enchanted-cave-2/
SWF URL - https://data.gameflare.com/games/5881/mSJ2ApTLIwFeti.swf

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

_No response_

### Additional information

_No response_

### LINKED ISSUE #23286: Crossbridge lua test swf fails to load
### Describe the bug

Attempting to load the swf, either from link or file, fails. Log shows:
Error loading AVM2 ABC: VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

### Expected behavior

Expected behavior is that it doesn't fail to load. (The swf works fine in flash player)

### Content Location

The swf can be found here: https://github.com/ThePizza1k/crossbridge-swc-lua/releases/download/v0.4.0/Main.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

This bug did not occur on older versions of ruffle. The 2026-02-05 nightly version loads the swf fine.
[ruffle.log](https://github.com/user-attachments/files/26124899/ruffle.log)

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #23143, fixes #23145 and fixes #23286.

### CODE REVIEW

**Comment by kjarosh** [comment]
Can you elaborate on the fix?

**Comment by SuchAFuriousDeath** [comment]
Yeah sure, just give me a while. Just for context - I had Claude Code research and bisect the regression and it got a bit too enthusiastic and created the PR before I had a chance to review this (It misunderstood a prompt). But I can confirm that https://github.com/ruffle-rs/ruffle/pull/22136 broke that game based on a bisect.

File: core/src/avm2/vtable.rs [hunk 1]
```diff
@@ -522,14 +526,23 @@ impl<'gc> VTable<'gc> {
...
+        // (slot_id and disp_id share a numbering space in ABC).
+        // new_slots.len() equals the highest slot_id relative to this class
+        // (max_slot_id - first_slot_offset), so it must not exceed trait_count.
+        // https://github.com/adobe/avmplus/blob/858d034/core/Traits.cpp#L800
+        if !force_auto_assign_slots && new_slots.len() > trait_count {
+            return Err(VTableInitError::SlotHole);
+        }
+
+        // Append the new slots to the slot table now.
+        // Gaps in the slot numbering (positions used by method disp_ids) are
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: This comment is incorrect; these are not "positions used by method disp_ids".

File: core/src/avm2/vtable.rs [hunk 2]
```diff
@@ -522,14 +526,23 @@ impl<'gc> VTable<'gc> {
...
+        // filled with a default `*`-typed slot, matching avmplus behavior.
         for slot in new_slots {
-            if let Some(slot) = slot {
-                slot_table.push(slot);
-            } else {
-                // Holes in the slot table throw an error in Flash Player
-                return Err(VTableInitError::SlotHole);
-            }
+            slot_table.push(slot.unwrap_or(SlotInfo {
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: nit: Can you separate this out into an `if let Some`, and add the comment above to the `else` case? I think it's slightly more readable that way

File: core/src/avm2/vtable.rs [hunk 3]
```diff
@@ -522,14 +526,23 @@ impl<'gc> VTable<'gc> {
             }
         }
 
-        // Append the new slots to the slot table now
+        // Flash Player checks that no slot_id exceeds the total trait count
+        // (slot_id and disp_id share a numbering space in ABC).
+        // new_slots.len() equals the highest slot_id relative to this class
+        // (max_slot_id - first_slot_offset), so it must not exceed trait_count.
+        // https://github.com/adobe/avmplus/blob/858d034/core/Traits.cpp#L800
+        if !force_auto_assign_slots && new_slots.len() > trait_count {
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: Can you add right after this a comment saying something like
```
// This check is illogical, but SWFs depend on it, so we have to use it to match avmplus
```
or otherwise word the comment to explain that this check is illogical in avmplus, and is not necessary for slot correctness?

**Comment by Lord-McSweeney** [comment]
Adrian mentioned a case where this behavior causes a SWF that fails in FP to work in Ruffle over [Discord](https://discord.com/channels/610531541889581066/1018988594259574845/1473807352179196141). Can you add that as a test case?

**Comment by SuchAFuriousDeath** [comment]
> Adrian mentioned a case where this behavior causes a SWF that fails in FP to work in Ruffle over [Discord](https://discord.com/channels/610531541889581066/1018988594259574845/1473807352179196141). Can you add that as a test case?

Added as a known_failure.

File: tests/tests/swfs/avm2/slot_id_exceeds_trait_count/test.toml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+# Class C extends A, where C has slot_id=2 but only 1 trait.
+# Flash Player throws VerifyError #1107 because ne.id (2) > nameCount (1).
+# https://github.com/adobe/avmplus/blob/858d034/core/Traits.cpp#L800
+num_frames = 1
+known_failure = true
```
Comment (Lord-McSweeney) [inline tests/tests/swfs/avm2/slot_id_exceeds_trait_count/test.toml:5]: Why is this test a known failure? Shouldn't our behavior be matching FP now in this area?

File: core/src/avm2/vtable.rs [hunk 5]
```diff
@@ -522,13 +526,28 @@ impl<'gc> VTable<'gc> {
             }
         }
 
-        // Append the new slots to the slot table now
+        // Flash Player checks that no slot_id exceeds the total trait count
+        // (slot_id and disp_id share a numbering space in ABC).
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: Why do you state that slot_id and disp_id share a numbering space in FP? They don't, you can have a slot id set to the same as a disp id.

File: core/src/avm2/vtable.rs [hunk 6]
```diff
@@ -334,7 +334,11 @@ impl<'gc> VTable<'gc> {
             }
         }
 
+        let mut trait_count = 0usize;
+
         for trait_data in defining_class_def.traits() {
+            trait_count += 1;
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: Couldn't `trait_count` just be set to `defining_class_def.traits().len()`?

File: core/src/avm2/vtable.rs [hunk 7]
```diff
@@ -522,13 +526,28 @@ impl<'gc> VTable<'gc> {
...
-        // Append the new slots to the slot table now
+        // Flash Player checks that no slot_id exceeds the total trait count
+        // (slot_id and disp_id share a numbering space in ABC).
+        // new_slots.len() equals the highest slot_id relative to this class
+        // (max_slot_id - first_slot_offset), so it must not exceed trait_count.
+        // This check is not necessary for slot correctness, but SWFs depend
+        // on it, so we match avmplus behavior.
+        // https://github.com/adobe/avmplus/blob/858d034/core/Traits.cpp#L800
+        if !force_auto_assign_slots && new_slots.len() > trait_count {
+            return Err(VTableInitError::SlotHole);
```
Comment (Lord-McSweeney) [inline core/src/avm2/vtable.rs]: Can we rename this error variant to something else? It's not returned when slot holes appear anymore.

**Review by adrian17 — APPROVED** [review]

**Review by Lord-McSweeney — APPROVED** [review]
