### PR TITLE
avm1: Various Sound fixes

### LINKED ISSUE #4010: Sound duration and position works differently in Ruffle (AS2)
```var mysound = new Sound()```
Now checking ```mysound.duration``` shows 'undefined' in Flash player and in Ruffle it shows '0'
```mysound.attachSound("somesound")```
With the wav sound file I tested Flash shows ```mysound.duration``` equal to 1080, Ruffle shows it equal to 1079.
```mysound.start()```
After sound is finished playing, ```mysound.position``` in Flash is 1080, in Ruffle it shows 0.
That's why checking if sound has finished playing before playing it again doesn't work in some old code with Ruffle:
```if (mysound.duration == mysound.position) { mysound.start(); }```

P. S.
Also if I do ```stopAllSouds()``` in a middle of playing sound, it's position stays where it was at that moment in Flash, in Ruffle it resets to 0.

### PR DESCRIPTION
**Pull request by relrelb**
* `Sound.duration` should return `undefined` when no sound is attached (fixes #4010). Previously it returned 0.
* Fix rounding behavior of `Sound.duration` (also #4010). Previously it was always rounded down. Change it to the nearest integer.
* Implement undocumented `Sound.getDuration` and `Sound.setDuration`.

### CODE REVIEW

File: core/src/avm1/globals/sound.rs [hunk 1]
```diff
@@ -230,7 +238,10 @@ fn duration<'gc>(
 ) -> Result<Value<'gc>, Error<'gc>> {
     if activation.current_swf_version() >= 6 {
         if let Some(sound_object) = this.as_sound_object() {
-            return Ok(sound_object.duration().into());
+            return Ok(sound_object
+                .sound()
+                .and_then(|s| activation.context.audio.get_sound_duration(s))
+                .map_or(Value::Undefined, |d| d.into()));
```
Comment (Herschel) [inline core/src/avm1/globals/sound.rs:244]: I think we still want to cache the duration, because, for example, loadSound immediately resets it to 0 even if the sound can't be loaded:
```
sound.loadSound("invalid-url.mp3");
trace(sound.duration); // traces 0
```

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!
