### PR TITLE
desktop: Only attach to parent console on Windows if stdout is not a pipe or a regular file

### LINKED ISSUE #9145: Cannot redirect command-line output to file on Windows
### Describe the bug

When I run Ruffle from the command line on Windows, I cannot redirect its output to a file as [explained here](https://ss64.com/nt/syntax-redirection.html). For example, typing `ruffle.exe --version > version.txt` still prints the version in the Command Prompt and does not output it to the `version.txt` file.

### Expected behavior

In very old builds of Ruffle (early 2021), this functionality worked properly.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #9145. I tested this on my Windows backup laptop and it seems to work, but somebody please double check.

The original code caused the issue by attaching to a console unconditionally, which overrode the redirection to the file.

### CODE REVIEW

**Comment by sombraguerrero** [comment]
This checks out per my testing. I'd say it's good to merge.

File: desktop/src/main.rs [hunk 1]
```diff
@@ -61,10 +61,32 @@ fn init() {
     // When linked with the windows subsystem windows won't automatically attach
     // to the console of the parent process, so we do it explicitly. This fails
     // silently if the parent has no console.
+    //
+    // However, if stdout/stderr are already redirected (e.g., `ruffle.exe > file.txt`),
+    // we should NOT attach to the console as that would bypass the redirection.
+    // See: https://github.com/ruffle-rs/ruffle/issues/9145
     #[cfg(windows)]
     unsafe {
```
Comment (kjarosh) [inline desktop/src/main.rs]: The scope of this `unsafe` block is quite large and encompasses several unsafe calls, it's better to use `unsafe` near calls and add safety comments if needed.

File: desktop/src/main.rs [hunk 2]
```diff
@@ -61,10 +61,32 @@ fn init() {
...
+        let stdout_handle = GetStdHandle(STD_OUTPUT_HANDLE);
+        let file_type = GetFileType(stdout_handle);
+
+        match file_type {
+            // If output is redirected to a file or pipe, don't attach to console
+            // as that would bypass the redirection
+            FILE_TYPE_DISK | FILE_TYPE_PIPE => {}
+            // Otherwise, attach to parent console for interactive use
+            _ => {
+                AttachConsole(ATTACH_PARENT_PROCESS);
```
Comment (kjarosh) [inline desktop/src/main.rs]: We're attaching console conditionally but freeing it unconditionally. Should it be this way?

File: desktop/src/main.rs [hunk 3]
```diff
@@ -61,10 +61,32 @@ fn init() {
...
+        use windows_sys::Win32::Storage::FileSystem::{
+            FILE_TYPE_DISK, FILE_TYPE_PIPE, GetFileType,
+        };
+        use windows_sys::Win32::System::Console::{
+            ATTACH_PARENT_PROCESS, AttachConsole, GetStdHandle, STD_OUTPUT_HANDLE,
+        };
+
+        // Check if stdout is already redirected to a file or pipe
+        let stdout_handle = GetStdHandle(STD_OUTPUT_HANDLE);
+        let file_type = GetFileType(stdout_handle);
```
Comment (kjarosh) [inline desktop/src/main.rs]: For instance, according to the Microsoft docs, I can see that safety guarantees may be broken here. `GetFileType` claims to accept a handle to the file, but `GetStdHandle`'s docs mentions it can return `INVALID_HANDLE_VALUE` or `NULL`.

File: desktop/src/main.rs (hunk 1 above)
Comment (kjarosh) [inline desktop/src/main.rs]: Maybe it's too much for this PR, but the way I see it we could use RAII for freeing the console and ideally we would store such (non-unsafe) structure in a separate Windows-specific file.

Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: Sure, I can do it.

File: desktop/src/main.rs (hunk 2 above)
Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: Probably not. I did not know about the FreeConsole call. Good catch.

File: desktop/src/main.rs (hunk 3 above)
Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: AFAIK, the Rust bindings do not have any proper safety invariants.

And actually the Microsoft docs claim the following if you look carefully: 

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype

image

But maybe we should err on the side of caution anyway. Up to you.

File: desktop/src/main.rs (hunk 1 above)
Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: I cooked something up.

File: desktop/src/main.rs [hunk 4]
```diff
@@ -188,7 +172,11 @@ fn main() -> Result<(), Error> {
     if let Err(error) = &result {
         eprintln!("{:?}", error)
     }
-    shutdown();
+
+    // Drop the console only after printing errors above
+    #[cfg(windows)]
+    drop(console);
```
Comment (kjarosh) [inline desktop/src/main.rs]: The console should be dropped automatically, just name it `_console`.

Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: I wanted to be a bit more explicit about it, but sure, no problem.

File: desktop/src/main.rs (hunk 3 above)
Comment (kjarosh) [reply desktop/src/main.rs]: Sure, that leaves only `NULL` to handle I guess

Comment (SuchAFuriousDeath) [reply desktop/src/main.rs]: Unless you consider NULL to be included in 'invalid handle'. But I will check for NULL to be safe.

File: desktop/src/windows.rs [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+    // However, if stdout/stderr are already redirected (e.g., `ruffle.exe > file.txt`),
+    // we should NOT attach to the console as that would bypass the redirection.
+    // See: https://github.com/ruffle-rs/ruffle/issues/9145
+    pub(super) fn attach() -> Self {
+        use windows_sys::Win32::Storage::FileSystem::{
+            FILE_TYPE_DISK, FILE_TYPE_PIPE, GetFileType,
+        };
+        use windows_sys::Win32::System::Console::{
+            ATTACH_PARENT_PROCESS, AttachConsole, GetStdHandle, STD_OUTPUT_HANDLE,
+        };
```
Comment (kjarosh) [inline desktop/src/windows.rs]: Now as the file is Windows-only you can move those to the very top.

Comment (SuchAFuriousDeath) [reply desktop/src/windows.rs]: Done

**Review by kjarosh — APPROVED** [review]
