### PR TITLE
core: Fix incorrect rendering of word-wrap text boxes (close #1095)

### LINKED ISSUE #1095: Hovering text is broken in Sonny
Sonny is available here : https://armorgames.com/play/505/sonny
Version : Nightly on 2020-09-03T00:33:39.000Z
This is how it looks like :
image

### PR DESCRIPTION
**Pull request by rrogowski**
This PR fixes the way word-wrap text boxes are rendered. Here are some "before-and-after" snapshots demonstrating the effects of this fix for the game "Sonny":

## Before
Screen Shot 2022-08-22 at 4 19 31 PM
Screen Shot 2022-08-22 at 4 39 40 PM

## After
Screen Shot 2022-08-22 at 4 18 39 PM
Screen Shot 2022-08-22 at 4 37 51 PM

### CODE REVIEW

**Comment by adrian17** [comment]
Ooooh, neat! I couldn't figure it out at all back when I was implementing `autosize`.

File: core/src/display_object/edit_text.rs [hunk 1]
```diff
@@ -803,6 +803,9 @@ impl<'gc> EditText<'gc> {
             if !is_word_wrap {
                 edit_text.bounds.set_x(new_x);
                 edit_text.bounds.set_width(width);
+            } else {
+                let max_width = edit_text.static_data.text.bounds.x_max;
```
Comment (adrian17) [inline core/src/display_object/edit_text.rs:807]: Hmm, why not `max - min`?

File: core/src/display_object/edit_text.rs [hunk 2]
```diff
@@ -803,6 +803,9 @@ impl<'gc> EditText<'gc> {
...
+                edit_text.bounds.set_width(max_width);
```
Comment (Herschel) [inline core/src/display_object/edit_text.rs:808]: We could move the `is_word_wrap` check a little higher to avoid unnecessarily calculating `new_x` in the word wrap case:

```
if !is_word_wrap {
  let width = intrinsic_bounds.width() + padding;
  let new_x = match autosize { // ...etc }
  edit_text.bounds.set_x(new_x);
  edit_text.bounds.set_width(width);
} else {
  // ... etc.
}
  let height = intrinsic_bounds.height() + padding;
  edit_text.bounds.set_height(height);
```

Also I don't think `edit_text.bounds.set_width(max_width)`  is necessary -- if wordWrap+autosize are on, the width of the text field shouldn't change. Example SWF:

[autosize1.zip](https://github.com/ruffle-rs/ruffle/files/9397764/autosize1.zip)
```
txt._width = 200;
txt.autoSize = "left";
trace(txt._width);
```
Traces 200 in FP, but 98 in this PR because the text field ends up resetting to the SWF dimensions.

**Review by Herschel — COMMENTED** [review]
Thank you, and welcome!

A somewhat larger issue is that might be involved: In Ruffle, the layout gets recalculated immediately whenever autosize, wordwrap, etc. is changed. However, in the Flash Player, the layout only gets recalculated on demand (for example, by accessing `_width` or by rendering). This can cause a difference in Ruffle depending on the order that the parameters are set in, whereas in FP the parameter changes wouldn't take effect until after they are all set.

Example SWF:
[autosize2.zip](https://github.com/ruffle-rs/ruffle/files/9397782/autosize2.zip)
```
var txt = createTextField("txt", 0, 10, 10, 100, 0);
trace("(" + txt._x + ", " + txt._y + ")  " + txt._width + "x" + txt._height);

trace("autosize = left");
txt.autoSize = "left";
trace("(" + txt._x + ", " + txt._y + ")  " + txt._width + "x" + txt._height);

trace("set text");
txt.text = "TEST TEST\nTEST TEST TEST TEST TEST TEST TEST TEST ";
trace("(" + txt._x + ", " + txt._y + ")  " + txt._width + "x" + txt._height);

trace("set word wrap");
txt.wordWrap = true;
trace("(" + txt._x + ", " + txt._y + ")  " + txt._width + "x" + txt._height);
```
The trace lines end up forcing a relayout because of `_width` and `_height`. Notice how the values change if you comment those traces out, and also compare to the behavior in Ruffle.

Solving this issue can be for a future PR, but mentioning it because it may be affecting things here.

File: core/src/display_object/edit_text.rs (hunk 1 above)
Comment (Herschel) [reply core/src/display_object/edit_text.rs:807]: The width and position of the text field shouldn't change at all if word wrap is on, only the height -- [AS3 docs](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#autoSize):

> If wordWrap is also set to true, only the bottom of the text field is resized and the right side remains fixed.

**Comment by adrian17** [comment]
> However, in the Flash Player, the layout only gets recalculated on demand (for example, by accessing _width or by rendering)

Yeah, I was aware of that when originally implementing `autosize`.
For example, in FP `tf.autosize="right"; tf.autosize="left"; trace(tf._x);` gives different results than `tf.autosize="right"; trace(tf._x); tf.autosize="left"; trace(tf._x);`.
This, however, requires access to UpdateContext at minimum, from render layer. (I think I tried doing that at some point and even then things got messy)

> The width and position of the text field shouldn't change at all if word wrap is on, only the height

Yeah, but the point is that manually setting width to `static.max-static.min` is equivalent to "enforce original text field size, as if it didn't change", right? This indeed isn't a complete fix, but as a stopgap it's objectively better than current state, I think?

**Comment by Herschel** [comment]
> Yeah, but the point is that manually setting width to `static.max-static.min` is equivalent to "enforce original text field size, as if it didn't change", right? This indeed isn't a complete fix, but as a stopgap it's objectively better than current state, I think?

My original thought is that it works for Sonny, while being incorrect for other cases (see autosize1 SWF above), so it's mostly up to chance, and it'd be better for the code to do what it actually should -- but yea, you're probably right that this PR is probably better more often than not!

File: core/src/display_object/edit_text.rs (hunk 1 above)
Comment (Herschel) [reply core/src/display_object/edit_text.rs:807]: Scratch that: per the below discussion, setting the width to `x_max - x_min` is a good solution for now. Let's add a TODO comment that eventually the width shouldn't change.

**Comment by Herschel** [comment]
Thank you!
