### PR TITLE
avm1: Implement NetConnection, more or less

### LINKED ISSUE #3317: avm1: Flash Remoting not working
**Describe the bug**
When clicking a disorder on http://www.g2conline.org/, information is supposed to load into the animation by utilizing Action Message Format with [Flash Remoting](https://www.oreilly.com/library/view/flash-remoting-the/059600401X/ch01s02.html). However, nothing loads. Here is a picture of clicking ADHD with Ruffle:
adhd_ruffle
I'm also seeing the same problem with http://www.eugenicsarchive.org/eugenics/list2.pl, which also uses AMF to load content. Here is a picture of it with Ruffle, after clicking the magnifying glass for Search, clicking Accept, clicking Topics, and then clicking "Agricultural Genetics":
eugenics_archive_ruffle

**Expected behavior**
Here's a picture of what happens when you click ADHD using Flash on g2conline:
adhd_flash
Here's a picture of what happens on the Eugenics Archive after clicking the magnifying glass for Search, clicking Accept, clicking Topics, and then clicking "Agricultural Genetics" in Flash:
eugenics_archive_flash

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
I'm using the browser extension

**What platform are you using?**
Windows, Google Chrome

### LINKED ISSUE #15823: AGI AS2 does not work on Ruffle
### Describe the bug

AS2 NetConnection is currently not implemented, preventing AGI AS2 from Authenticating
```
[ AGI ] -> : Armor Games Interface AS2 - Version 1.0
[ AGI ] -> : AGI Services connecting ...
[ AGI ] -> : Client: Connecting...
[ AGI ] -> : Client: Authenticating...
```
Example of a game using it:
https://armorgames.com/play/12009/the-last-stand-union-city

### Expected behavior

I'd be able to Log In to the game with my AG Account

### Content Location

https://cache.armorgames.com/files/games/the-last-stand-union-12009.swf?v=1462428589

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dinnerbone**
Tests are ported from avm2

Fixes #15823
Fixes #3317

### CODE REVIEW

File: core/src/avm1/globals/netconnection.rs [hunk 1]
```diff
@@ -1,26 +1,153 @@
...
+        this.call_method(
+            "onStatus".into(),
+            &[event.into()],
+            &mut activation,
+            ExecutionReason::Special,
+        )?;
+        Ok(())
+    }
+
+    // [NA] I have no idea why this is a thing. It's similar in AVM2 too.
```
Comment (Lord-McSweeney) [inline core/src/avm1/globals/netconnection.rs:78]: We confirmed that in AVM2 this is an event that sends the metadata script data. Have you checked that it's the same in AS2?

Comment (Dinnerbone) [reply core/src/avm1/globals/netconnection.rs:78]: I have no idea. How/where did you confirm that? I wasn't aware!

This is the code we have for avm2, which is as I originally wrote it still:
```actionscript
                    let event = Avm2EventObject::net_status_event(
                        &mut activation,
                        "netStatus",
                        vec![
                            ("code", ""),
                            ("description", ""),
                            ("details", ""),
                            ("level", "status"),
                        ],
                    );
```

For AVM1 it seems to just call the method with undefined.
