### PR TITLE
avm1: Fix `loadVariablesNum` / `Action::GetUrl2`

### LINKED ISSUE #6307: [When Stuffed Animals Attack!] The game does not start after loading external data.
### Describe the bug

When I start the game in **'Dexter's Laboratory: When Stuffed Animals Attack!'**, it freezes at a loading screen like the one below and doesn't go any further.

image

The game tries to load the external data file: `\dexter_maps\level1.dex`.

Loading the `level1.dex` file seems to succeed, but the loading progress bar doesn't change and it doesn't proceed to the next one.

[dexter.zip](https://github.com/ruffle-rs/ruffle/files/8088528/dexter.zip)

Verified on Ruffle Nightly `2022-02-10`.

### Expected behavior

The game should run normally.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 98

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Toad06**
Resolves #6307.

`loadVariablesNum` currently has issues that can be observed in different ways.

---

1- With minor changes in the [avm1 loadvariablesnum test](https://github.com/ruffle-rs/ruffle/tree/master/tests/tests/swfs/avm1/loadvariablesnum):

Frame 1:
`loadVariablesNum("testvars.txt",2,"GET"); // Load variables on _level2.`

Frame 3:
```
if(this.loaded !== undefined) // This evaluates to true in Ruffle with the current builds and traces unexpected values.
{
   trace("this.loaded !== undefined");
   trace(this.loaded); // "Hurray"
   trace(_root.loaded); // "Hurray"
   trace(_level0.loaded); // "Hurray"
   trace(_level2.loaded); // undefined
   stop();
}
else if(_level2.loaded !== undefined) // Instead this should run and traces the following values.
{
   trace("_level2.loaded !== undefined");
   trace(_level2.loaded); // "Hurray"
   trace(_root.loaded); // undefined
   trace(_level0.loaded); // undefined
   trace(this.loaded); // undefined
   stop();
}
else
{
   gotoAndPlay(2);
}
```

[Sample](https://github.com/ruffle-rs/ruffle/files/8140295/sample.zip)

---

2- With changes based on the [avm1 tell_target_invalid test](https://github.com/ruffle-rs/ruffle/tree/master/tests/tests/swfs/avm1/tell_target_invalid) (which now looks completely different 😃):

frame 1 in a DefineSprite:
`loadVariablesNum("testvars.txt",0); // Load variables on _level0.`

frame 2 on the main timeline:
```
if(this.mc.loaded !== undefined) // This evaluates to true in Ruffle with the current builds and traces unexpected values.
{
   trace("this.mc.loaded !== undefined");
   trace(this.mc.loaded); // "Hurray"
   trace(this.loaded); // undefined
   trace(_root.loaded); // undefined
   stop();
}
else if(this.loaded !== undefined) // Instead this should run and traces the following values.
{
   trace("this.loaded !== undefined");
   trace(this.loaded); // "Hurray"
   trace(_root.loaded); // "Hurray"
   trace(this.mc.loaded); // undefined
   stop();
}
```

[Sample](https://github.com/ruffle-rs/ruffle/files/8140506/sample2.zip)

### CODE REVIEW

**Review by kmeisthax — APPROVED** [review]

File: core/src/avm1/activation.rs [hunk 1]
```diff
@@ -1185,59 +1185,90 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
...
+                    if target.len() == 6 {
+                        0
+                    } else {
+                        -1
+                    }
+                }
+            }
+        } else {
+            -1
+        };
```
Comment (Herschel) [inline core/src/avm1/activation.rs:1213]: I think it's worthwhile to resolve the TODO in this PR and switch this over to using `StageObject::get_level_by_path`, because it will clean this up and also handle these weirdo cases:
`loadMovieNum("child.swf", 4294967297); // wraps to _level1`
`loadMovie("child.swf", "_flash1"); // way old synonym for _level1`

Possibly `StageObject::get_level_by_path` could be moved somewhere more appropriate as a utility function.

Comment (Toad06) [reply core/src/avm1/activation.rs:1213]: Thanks for the review.

This TODO is actually more recent than this PR (cc. #6434), that's why I didn't really consider it here.

I've made an alternative version that could eventually supersede this PR but more changes are implied:
https://github.com/Toad06/ruffle/commit/304ae9f77c7823dbc92d638eda64687fdda23d97

To sum up what this PR does:
- It uses `StageObject::parse_level_id`, as `StageObject::get_level_by_path` won't resolve a level that doesn't exist.
- `StageObject::parse_level_id` is changed to parse the whole string, not just the part after "_level". The function also has a new argument `strict_parse`, as things like `_level1ABC` only resolves to `_level1` in `action_get_url_2` if this level already exists.

All of this is still very experimental to me.

**Review by Herschel — APPROVED** [review]
Thank you!
