### PR TITLE
avm2: getStackTrace() returns null when the stack trace is unavailable

### LINKED ISSUE #12572: Crystal Cove Online - Black screen after initial load screen complete
### Describe the bug

After the initial loading screen, the game ends up with a black screen. The music plays fine at this point, and some limited interactivity is possible (pressing Z or Enter has a pop sound effect indicating the next screen is reached, although inputs seem to do nothing else afterwards).

I'm using dropbox here as the game exceeds GitHub's zip size limit (as the game is ~40MB). Two links are provided here, the first is an unmodified copy of the game, and the second one is slightly modified to allow for the standalone flashplayer to play this game (and thus compare its results) (the modifications just being disabling the online enforcement and thus allowing flashplayer to fetch the swf files locally). The result is the same regardless within Ruffle.

https://www.dropbox.com/s/64st2l6qrwhcd9n/crystal_cove_online_unmodified.zip?dl=1
https://www.dropbox.com/scl/fi/ka28zfp5uramkxxlf0l3q/crystal_cove_online.zip?rlkey=wg0mi1dzdtkjw6dcmow8b18l1&dl=1

Image of issue:
image

### Expected behavior

The next screen should load up fine:
image

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

Using `RUST_LOG=warn,ruffle_core=debug,avm_trace=trace`
```
2023-08-05T10:10:11.111189Z  INFO ruffle_core::player: Loaded SWF version 10, resolution 688x375 @ 30 FPS
2023-08-05T10:10:11.164130Z  INFO run_frame:run_all_phases_avm2: avm_trace: sending unique to toAchieveModule unique val: 1244
2023-08-05T10:10:11.164392Z  WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.net.LocalConnection.send()
2023-08-05T10:10:11.165403Z  INFO run_frame:run_all_phases_avm2: avm_trace: LocalConnection encountered an error.
2023-08-05T10:10:11.165712Z  WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.net.LocalConnection.connect()
2023-08-05T10:10:11.189154Z  INFO run_frame:run_all_phases_avm2: avm_trace: <temp_xml><file cast="Xmls" type="xmlswf" filename="Animation.swf"/><file cast="Xmls" type="xmlswf" filename="Xmls.swf"/><file cast="Font" type="font" filename="Fonts.swf"/><file cast="Room_000" type="swf" filename="Rooms/000.swf"/><file cast="Room_CC_EX_01a" type="swf" filename="Rooms/CC_EX_01a.swf"/><file cast="Room_CC_IN_01a" type="swf" filename="Rooms/CC_IN_01a.swf"/><file cast="Sound" type="swf" filename="Sound/Sound.swf"/><file cast="LevelMedia" type="swf" filename="LevelMedia/LevelMedia.swf"/><file cast="Media_Screen" type="swf" filename="Media_Screen/Media_Screen.swf"/><file cast="Media_Screen" type="swf" filename="Media_Screen/M_Splash_Week_0.swf"/><file cast="Media_Screen" type="swf" filename="Media_Screen/M_Splash_Week_X.swf"/><file cast="PDA" type="swf" filename="PDA/PDA.swf"/><file cast="Media_MM" type="swf" filename="Media_MM/Media_MM.swf"/><file cast="Media_Popup" type="swf" filename="Media_Popup/Media_Popup.swf"/><file cast="Media_Avatar" type="swf" filename="Media_Avatar/avatar.swf"/><file cast="Media_Avatar" type="swf" filename="Media_Avatar/avatar2.swf"/><file cast="Media_Poster" type="swf" filename="Media_Poster/Media_Poster.swf"/><file cast="Media_Character" type="swf" filename="Media_Character/characters.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/Media_Enemy.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/caterpillar.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/wasp.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/giantfly.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/wolf.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/RCar.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/Rat.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/crab.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/Gator.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/idol.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/bat.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/monkey.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/gnome.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/wreckball.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/mechspider.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/octopus.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/cicada.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/flamingSkull.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/motorcycle.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/evilRose.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/traps.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/dragon.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/zombie.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/beetle.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/chair.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/bearRug.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/snake.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/JetPlane.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/ShadowFreak.swf"/><file cast="Media_Enemy" type="swf" filename="Media_Enemy/WaspNest.swf"/><file cast="Preloader" type="swf" filename="PreloaderGame.swf"/><file cast="Media_Screen" type="swf" filename="Media_Screen/M_Splash_Week_26.swf"/></temp_xml>
2023-08-05T10:10:11.222798Z  INFO run_frame:run_all_phases_avm2: avm_trace: [INFO] engine::DownloadManager::mNextImgDownload()[null - TotalDownload: 14228KB
2023-08-05T10:10:11.505312Z  WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.display.Loader.unload()
2023-08-05T10:10:12.957067Z  WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.text.Font.registerFont()
2023-08-05T10:10:13.040641Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.040983Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.041845Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.042142Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.160852Z  INFO avm_trace: sending unique to toAchieveModule unique val: 1244
2023-08-05T10:10:13.161159Z  INFO avm_trace: LocalConnection encountered an error.
2023-08-05T10:10:13.241338Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.241702Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.242541Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.242817Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.409810Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.410092Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.410932Z  INFO run_frame: avm_trace: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2023-08-05T10:10:13.411180Z  INFO run_frame: avm_trace:



2023-08-05T10:10:13.458536Z  WARN run_frame: ruffle_core::stub: Encountered stub: AVM2 flash.media.Sound constructor with arguments
2023-08-05T10:10:13.835238Z  WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.display.InteractiveObject.tabIndex setter
2023-08-05T10:10:15.122608Z  INFO avm_trace: sending unique to toAchieveModule unique val: 1244
2023-08-05T10:10:15.122842Z  INFO avm_trace: LocalConnection encountered an error.
2023-08-05T10:10:17.139948Z  INFO avm_trace: sending unique to toAchieveModule unique val: 1244
2023-08-05T10:10:17.140266Z  INFO avm_trace: LocalConnection encountered an error.
2023-08-05T10:10:18.365978Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160af777710 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.393054Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1934bb0 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.426574Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1935550 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.459806Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b19349f0 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.492985Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b19366d0 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.526593Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b19367b0 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.559594Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1936970 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.593031Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1934050 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.626709Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1936c10 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.659864Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b19360b0 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
2023-08-05T10:10:18.746948Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x160b1934130 }) to handler FunctionObject(FunctionObject { ptr: 0x160f29ff830 }) : RustError("ArgumentError: Child is not a child of this object")
```
Those last errors end up just getting spammed constantly.

### PR DESCRIPTION
**Pull request by n0samu**
In release builds of FP, [getStackTrace() returns null](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Error.html#getStackTrace()). We were erroneously returning "Error" because of how [ErrorObject.display() is implemented](https://github.com/ruffle-rs/ruffle/blob/e18c708d47775c4534cdd87db37c37405c22be83/core/src/avm2/object/error_object.rs#L90-L92). To work around this, we can explicitly check whether the call stack is empty and return null if so.

This fixes #12572, which has code that looks like this:
```as
var vStackTrace:String = new Error().getStackTrace();
if(vStackTrace != null) {
    // Parse the stack trace...
}     
```

### CODE REVIEW

File: core/src/avm2/globals/error.rs [hunk 1]
```diff
@@ -25,7 +25,10 @@ pub fn get_stack_trace<'gc>(
...
 ) -> Result<Value<'gc>, Error<'gc>> {
     if let Some(error) = this.as_error_object() {
-        return Ok(AvmString::new(activation.context.gc_context, error.display_full()?).into());
+        let call_stack = error.call_stack();
+        if !call_stack.is_empty() {
+            return Ok(AvmString::new(activation.context.gc_context, error.display_full()?).into());
+        }
     }
-    Ok(Value::Undefined)
+    Ok(Value::Null)
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/error.rs:33]: This should be unreachable, so there's no need to modify it

Comment (n0samu) [reply core/src/avm2/globals/error.rs:33]: Nope, test it out and you'll see that this is in fact where the return value comes from 😛

**Review by Dinnerbone — APPROVED** [review]
