### PR TITLE
avm2: Improve XMLList set_local_property

### LINKED ISSUE #2444: Error on https://www.newgrounds.com/portal/view/562116
#Well, very simply, I was trying to play REBUILD on Newgrounds, and I got sent to a screen where it said "RUFFLE ENCOUNTERED A BUG." Here's a screenshot: http://my.jetscreenshot.com/2306/20210113-sm8a-80kb 

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.N (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/core.ruffle.js:1:21219)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38351)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[1279]:0x25eedb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[1537]:0x28eac1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4274]:0x361c64)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[3304]:0x33c6a5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[3885]:0x357ce6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4618]:0x36733c)
    at rust_begin_unwind (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4492]:0x3659ab)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4620]:0x3673a0)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://uploads.ungrounded.net/562000/562116_Rebuilder___newg.swf?123
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=5ffe626c6be18&NewgroundsAPI_SessionID=pyh8TfKx6P9pzdi2Eeizd6626beaaa2e2ca91da1c64596773f371e0f1a42tY9j&NewgroundsAPI_UserName=AlphaFactor&NewgroundsAPI_UserID=118199&ng_username=AlphaFactor
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.newgrounds.com/portal/view/562116
SWF URL: https://uploads.ungrounded.net/562000/562116_Rebuilder___newg.swf?123

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

### LINKED ISSUE #10540: Snailiad - Can't proceed past intro
### Describe the bug

https://www.newgrounds.com/portal/view/573352?emulate=flash

Snailiad is at a point now where it starts up, the title screen works and the intro works but it stops when you get to the game.

The prominent console error appears to be:
Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3f661b0 }) to handler FunctionObject(FunctionObject { ptr: 0x3f289f0 }) : RustError("Modifying an XMLList object is not yet implemented: target XmlObject(XmlObject { ptr: 0x4cf8a28 })")

### Expected behavior

Once everything is working, game should proceed to gameplay after the intro.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome version Version 110.0.5481.178

### Additional information

_No response_

### LINKED ISSUE #12173: Ancient Jewels Cleopatra - XML Error
### Describe the bug

https://www.spiele-umsonst.de/azad/downloads/flashgames/ancientjewelscleopatrastreasure.swf - After I click on Create nothing happens, also the loading bar of the game is out of the box.

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x4d897b8 }) to handler FunctionObject(FunctionObject { ptr: 0x6e29760 }) : RustError("Cannot append non-XML value PrimitiveObject(PrimitiveObject { ptr: 0x41d4bf0 })")

### Expected behavior

Create the profile and continue play

### Affected platform

Desktop app

### Operating system

All

### Browser

All

### Additional information

_No response_

### LINKED ISSUE #12406: Rebuild 2 - can't start game
### Describe the bug

1. Download SWF from https://uploads.ungrounded.net/581000/581493_Rebuild2.swf
2. Load SWF at https://ruffle.rs/demo/
3. Try to start a new game.

It just reloads the same screen rather than starting the game.

After trying to start a few times, I see this in the DevTools console:

```
ruffle_web-wasm_extensions.js:716 WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.text.TextField.restrict setter
ruffle_web-wasm_extensions.js:716 WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.media.Sound constructor with arguments
ruffle_web-wasm_extensions.js:716 WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.media.Sound.bytesLoaded getter
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x568f3f8 }) to handler FunctionObject(FunctionObject { ptr: 0x433eff0 }) : RustError("Modifying an XMLList object is not supported for Multiname { ns: Multiple([Namespace(Private(\"rebuild2.game:SaveManager\")), Namespace(Namespace(\"rebuild2\")), Namespace(Namespace(\"\")), Namespace(Namespace(\"rebuild2.game\")), Namespace(StaticProtected(\"rebuild2.game:SaveManager\")), Namespace(Private(\"SaveManager.as$21\")), Namespace(PackageInternal(\"rebuild2.game\")), Namespace(Namespace(\"http://adobe.com/AS3/2006/builtin\")), Namespace(Namespace(\"rebuild2.events\")), Namespace(Namespace(\"rebuild2.fort\")), Namespace(Namespace(\"rebuild2.gui\")), Namespace(Namespace(\"rebuild2.map\")), Namespace(Namespace(\"rebuild2.mission\")), Namespace(Protected(\"rebuild2.game:SaveManager\"))]), name: Some(\"food\"), param: None, flags: MultinameFlags(0x0) } = Integer(75)")
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x9a01ec0 }) to handler FunctionObject(FunctionObject { ptr: 0x433eff0 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: setHighlightGlow)
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xdc715b8 }) to handler FunctionObject(FunctionObject { ptr: 0x433eff0 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: setHighlightGlow)
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xa6565e8 }) to handler FunctionObject(FunctionObject { ptr: 0x433eff0 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: setHighlightGlow)
```

### Expected behavior

I expect the game to start.

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Chrome 115.0.5790.102

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sleepycatcoding**
This PR solves `RustError("Modifying an XMLList object is not yet implemented: need to resolve")` errors.

Fixes #2444
Fixes #10540
Fixes #12173
Fixes #12406

TODO:

- [x] Fix all the FIXMEs about target property
- [x] Add tests

### CODE REVIEW

File: core/src/avm2/globals/xml.rs [hunk 1]
```diff
@@ -456,9 +465,11 @@ pub fn descendants<'gc>(
     let multiname = name_to_multiname(activation, &args[0], false)?;
     let mut descendants = Vec::new();
     xml.node().descendants(&multiname, &mut descendants);
-    Ok(XmlListObject::new(activation, descendants, Some(xml.into())).into())
+    // FIXME: Usage of target property needs to be evaluated.
+    Ok(XmlListObject::new(activation, descendants, Some(xml.into()), None).into())
```
Comment (evilpie) [inline core/src/avm2/globals/xml.rs:469]: I guess we need to verify what Flash does in practice, but in the spec I think this has a null [[TargetObject]] (so the current code is wrong) and no [[TargetProperty]] (implicit null?).

> 9.1.1.8 [[Descendants]] (P)
> 2. Let list be a new XMLList with list.[[TargetObject]] = null

Comment (sleepycatcoding) [reply core/src/avm2/globals/xml.rs:469]: According to avmplus `XMLListObject::create` defaults to `null` target property and object (https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/XMLListObject.h#L69C1-L69C1) and getDescendants does not specify either of those (https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/XMLListObject.cpp#L192) so this is implicit null, yes.

File: core/src/avm2/object/xml_list_object.rs [hunk 2]
```diff
@@ -230,6 +329,66 @@ impl<'a, 'gc> Deref for E4XWrapper<'a, 'gc> {
...
+    pub fn from_value(value: Value<'gc>) -> Result<XmlOrXmlListObject<'gc>, Error<'gc>> {
+        if let Some(xml) = value.as_object().and_then(|x| x.as_xml_object()) {
+            return Ok(XmlOrXmlListObject::Xml(xml));
+        }
+
+        if let Some(list) = value.as_object().and_then(|x| x.as_xml_list_object()) {
+            return Ok(XmlOrXmlListObject::XmlList(list));
+        }
+
+        Err(format!("Value {:?} was neither XmlObject or XmlListObject", value).into())
```
Comment (Lord-McSweeney) [inline core/src/avm2/object/xml_list_object.rs:376]: If this error condition can never be hit, can you replace this with a `panic!`?

Comment (sleepycatcoding) [reply core/src/avm2/object/xml_list_object.rs:376]: This error condition technically should never be hit since get_property_local of Xml/XmlListObject should return a XmlListObject.

Comment (Lord-McSweeney) [reply core/src/avm2/object/xml_list_object.rs:376]: In that case can you replace it with a panic?

Comment (sleepycatcoding) [reply core/src/avm2/object/xml_list_object.rs:376]: > In that case can you replace it with a panic?

I think so.

Comment (adrian17) [reply core/src/avm2/object/xml_list_object.rs:376]: > since get_property_local of Xml/XmlListObject should return a XmlListObject.

Sure, but this only applies to its callers, not to the method itself. I'd say adding such an invisible invariant to the signature is a bit weird. Maybe wrap the entire get-property + cast into a single method?

**Comment by sleepycatcoding** [comment]
I think I will also implement the other path in this PR as it actually does not seem that complicated as I thought it was.

File: core/src/avm2/object/xml_list_object.rs [hunk 3]
```diff
@@ -539,39 +539,329 @@ impl<'gc> TObject<'gc> for XmlListObject<'gc> {
...
+                        }
+
+                        // 2.c.iii Create a new XML object y with y.[[Parent]] = r, y.[[Name]] = x.[[TargetProperty]],
+                        //         y.[[Attributes]] = {}, y.[[Length]] = 0
+                        let y = match self.target_property() {
+                            // 2.c.iv. If Type(x.[[TargetProperty]]) is AttributeName
+                            Some(x) if x.is_attribute() => {
+                                // 2.c.iv.1. Let attributeExists be the result of calling the [[Get]] method of r with argument y.[[Name]]
+                                // FIXME: Looking at avmplus, it seems it does not check if r is null, not sure if we should use a unwrap or if let?
+                                let attribute_exists = XmlObject::new(r.unwrap(), activation)
```
Comment (Lord-McSweeney) [inline core/src/avm2/object/xml_list_object.rs:597]: Should this be an `expect` at the very least so we can have a little more detail about it in the error report?

File: core/src/avm2/object/xml_list_object.rs [hunk 4]
```diff
@@ -230,6 +328,79 @@ impl<'a, 'gc> Deref for E4XWrapper<'a, 'gc> {
     }
 }
 
+/// Represents either a XmlObject or a XmlListObject. Used
+/// for resolving the value of empty XMLLists.
+#[derive(Clone, Collect, Copy, Debug)]
+#[collect(no_drop)]
+pub enum XmlOrXmlListObject<'gc> {
```
Comment (adrian17) [inline core/src/avm2/object/xml_list_object.rs:335]: personally I'd probably keep using an Object, but I guess this is slightly safer.

**Review by adrian17 — APPROVED** [review]

File: core/src/avm2/object/xml_list_object.rs (hunk 3 above)
Comment (sleepycatcoding) [reply core/src/avm2/object/xml_list_object.rs:597]: Yeah, you are right, I don't think there is a case where target_property would be Some and target_object would be None. (It is usually the other way around).

**Review by Lord-McSweeney — APPROVED** [review]

**Review by Dinnerbone — APPROVED** [review]
