### PR TITLE
avm2: ByteArray.readUTF/readUTFBytes should cut off after null byte

### LINKED ISSUE #9668: AVM2: Bytearray behaviour is not the same as Flash
### Describe the bug

Bytearray `readUTFBytes` should terminate after a NULL is detected
in ruffle it traces:
2023-02-22T02:55:51.714413Z  INFO run_frame:run_all_phases_avm2: avm_trace: abcdef
2023-02-22T02:55:51.717318Z  
INFO run_frame:run_all_phases_avm2: avm_trace: 8 ( Bytearray position )
[bytearray.zip](https://github.com/ruffle-rs/ruffle/files/10799635/bytearray.zip)

Uses SWF I attached above

### Expected behavior

However in Flash it traces
abc
8 ( Bytearray position )

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Bale001**
When reading from a bytearray using either `readUTF` or `readUTFBytes`, we are meant to cut off at the first null byte. This is a bug in FP, and more info can be found here https://bugzilla.mozilla.org/show_bug.cgi?id=687341

Fixes #9668

### CODE REVIEW

File: core/src/avm2/bytearray.rs [hunk 1]
```diff
@@ -132,6 +132,16 @@ impl ByteArrayStorage {
         Ok(bytes)
     }
 
+    /// Same as `read_bytes`, but cuts the result at the first null byte to recreate a bug in FP.
+    pub fn read_bytes_null_terminated(&self, amnt: usize) -> Result<&[u8], EofError> {
```
Comment (relrelb) [inline core/src/avm2/bytearray.rs:136]: Maybe rename this to `read_utf_bytes()`, to match avmplus:
https://github.com/adobe/avmplus/blob/master/core/ByteArrayGlue.cpp#L2640

Comment (Bale001) [reply core/src/avm2/bytearray.rs]: I had no idea they hardcoded that

**Review by relrelb — APPROVED** [review]

**Comment by relrelb** [comment]
Thanks! Feel free to rebase and merge. Just make sure to squash the CR commit into the actual fix.
