### PR TITLE
avm2: Match verifier reading implementation with FP's

### LINKED ISSUE #15181: some doswf encrypted swf doesn't work now
### Content Location

[最强大脑.zip](https://github.com/ruffle-rs/ruffle/files/14227585/default.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### LINKED ISSUE #15314: Bratz Style It: Stuck on a black screen when launching a game (AVM2)
### Describe the bug

When you launch the game, you will no longer be stuck on a black screen, and the console will look like this:

```
ERROR core/src/display_object/movie_clip.rs:2225 Got "VerifyError: Error #1011: Method contained illegal opcode.
	at ί/init()
	at ί()" when constructing AVM2 side of movie clip of type ί
```

### Expected behavior

The game should run normally.

### Content Location

See attachment file below:

[bratz-style-it.zip](https://github.com/ruffle-rs/ruffle/files/14395167/bratz-style-it.zip)

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Google Chrome 122

### Additional information

_No response_

### LINKED ISSUE #15345: The Amazing Fix: Possible regression by optimizer improvements
### Describe the bug

The game is unplayable, I can see only a white screen,

The game is working great with Nightly 2024-02-23, looks like the problem is https://github.com/ruffle-rs/ruffle/pull/15105

### Expected behavior

start the game

### Content Location

Play online - https://www.gameflare.com/online-game/the-amazing-fix/
SWF - https://data.gameflare.com/games/1141/uF3NIfhHhafOrv.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #15314
Fixes #15181

Fixes #15345

Fixes the regression in #10148

With this implementation, all code in `new_code` is guaranteed to be reachable (and therefore also run through the verifier).

### CODE REVIEW

File: core/src/avm2/verify.rs [hunk 1]
```diff
@@ -112,28 +112,41 @@ pub fn verify_method<'gc>(
...
                     return Err(make_error_1021(activation));
                 }
 
                 if target_position < 0 || target_position as usize >= body.code.len() {
                     return Err(make_error_1021(activation));
                 }
 
+                // Ensure backwards jumps to not-yet-jumped-to code target a `Label` op
+                if !seen_targets.contains(&target_position) && offs < 0 {
+                    reader.seek_absolute(&body.code, target_position as usize);
```
Comment (adrian17) [inline core/src/avm2/verify.rs:139]: random thought: if the jump is backwards, can we guarantee that all the ops before it were already seen? If so, then `byte_info` should be reached and we could use that instead?
That said, the current impl should work too and I don't wanna rock the boat too much

File: core/src/avm2/verify.rs [hunk 2]
```diff
@@ -518,6 +493,7 @@ pub fn verify_method<'gc>(
     })
 }
 
+// Taken from avmplus's opcodes.tbl
 fn op_can_throw_error(op: AbcOp) -> bool {
```
Comment (adrian17) [inline core/src/avm2/verify.rs:492]: can this take a reference? One less clone :D

**Review by adrian17 — APPROVED** [review]

File: core/src/avm2/verify.rs (hunk 1 above)
Comment (Lord-McSweeney) [reply core/src/avm2/verify.rs:139]: > if the jump is backwards, can we guarantee that all the ops before it were already seen?

No, definitely not, since there can be gaps in bytecode.
