### PR TITLE
core: Fix panic in `remove_invalid_jpeg_data`

### LINKED ISSUE #2371: Error on http://archive.knarcrafttest.net/Flash/Flash-Games/Strategy/Stormwinds
# Necessary debug info
The swf file is the same one used at: [https://archive.knarcraft.net/Flash/Games/Strategy/Stormwinds/](https://archive.knarcraft.net/Flash/Games/Strategy/Stormwinds/). knarcrafttest.net is a development site only accessible if the *.knarcrafttest.net domains are manually redirected to the knarcraft.net IP address using the hosts file.

# Error Info
Error name: Error
Error message: panicked at 'range end index 4 out of range for slice of length 2', core/src/backend/render.rs:308:8
Error stack:
```
Q@http://static.knarcrafttest.net/archive/tools/ruffle/core.ruffle.fb39aa46f71a4c17d772.js:1:21164
__wbg_new_df6e6ab7a65c4c4d@http://static.knarcrafttest.net/archive/tools/ruffle/ruffle.js:1:39038
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1279]:0x25da48
std::sync::once::Once::call_inner::h02eac160d339afc2@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1535]:0x28d0de
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4272]:0x360088
std::panicking::rust_panic_with_hook::h123718ba3bf480af@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[3308]:0x33af47
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[3885]:0x3561e1
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4616]:0x365760
rust_begin_unwind@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4490]:0x363dcf
core::panicking::panic_fmt::h285dc015a87be5a4@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4618]:0x3657c4
core::slice::index::slice_end_index_len_fail::h6f6253f4aa8173a8@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4052]:0x35aff3
ruffle_core::backend::render::remove_invalid_jpeg_data::hf569188f45d06fb0@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[2141]:0x2ddb71
ruffle_core::library::MovieLibrary::set_jpeg_tables::h7b68cc897cb69dac@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[2488]:0x3009ae
ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::ha9842aafbf2ba74f@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[288]:0x51f3e
ruffle_core::tag_utils::decode_tags::h444b973e7144f174@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1226]:0x2527b5
ruffle_core::display_object::movie_clip::MovieClip::preload::h0791720138e88e71@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[794]:0x1d9645
ruffle_core::display_object::movie_clip::MovieClipData::define_sprite::habda665292eeb5cc@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1314]:0x264b50
ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::ha9842aafbf2ba74f@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[288]:0x502ec
ruffle_core::tag_utils::decode_tags::h444b973e7144f174@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1226]:0x2527b5
ruffle_core::display_object::movie_clip::MovieClip::preload::h0791720138e88e71@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[794]:0x1d9645
ruffle_core::player::Player::set_root_movie::h694e4dccef013033@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[332]:0xb7d8f
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbed74add1a19f0bd@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[562]:0x175130
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h88b6a9d289d6d4e2@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[1754]:0x2ae388
wasm_bindgen_futures::task::singlethread::Task::run::h948542b2e2858e67@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[3094]:0x32ed46
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h32138f34f1d034f5@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[2805]:0x31af6b
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h40f4f0b308053f2c@http://static.knarcrafttest.net/archive/tools/ruffle/d8c011b7243f5bf278fd.module.wasm:wasm-function[4799]:0x367641
O@http://static.knarcrafttest.net/archive/tools/ruffle/core.ruffle.fb39aa46f71a4c17d772.js:1:19225
f@http://static.knarcrafttest.net/archive/tools/ruffle/core.ruffle.fb39aa46f71a4c17d772.js:1:17873

```

# Player Info
Allows script access: false

# Page Info
Page URL: http://archive.knarcrafttest.net/Flash/Flash-Games/Strategy/Stormwinds
SWF URL: https://static.knarcraft.net/archive/games/strategy/swf/stormwinds.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-10
Channel: nightly
Built: 2021-01-10T00:52:56.294Z
Commit: 6638aebde8b741e949d5f186c2e1683268cd9d50

### LINKED ISSUE #2908: Ruffle Error on https://www.jogos360.com.br/the_king_of_fighters_wing_1_7.html
# Error Info
Error name: Error
Error message: panicked at 'range end index 4 out of range for slice of length 0', core/src/backend/render.rs:310:8
Error stack:
```
Error: panicked at 'range end index 4 out of range for slice of length 0', core/src/backend/render.rs:310:8
    at Object.Y (https://www.jogos360.com.br/js/ruffle/core.ruffle.8523be3f1afb3ed16c0c.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (https://www.jogos360.com.br/js/ruffle/ruffle.js:1:35853)
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1117]:0x22cea9
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1457]:0x26f425
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3876]:0x329523
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3036]:0x3092fe
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4179]:0x32e379
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4209]:0x32e8dc
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4082]:0x32cecc
    at https://www.jogos360.com.br/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4210]:0x32e912
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/the_king_of_fighters_wing_1_7.html
SWF URL: https://cdn.jogos360.com.br/files/games/th/ek/the-king-of-fighters-wing-1-7.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

### PR DESCRIPTION
**Pull request by relrelb**
`data` could be shorter than 4 bytes.

Fixes #2371.
Fixes #2908.

### CODE REVIEW

File: core/src/backend/render.rs [hunk 1]
```diff
@@ -305,13 +305,12 @@ pub fn glue_tables_to_jpeg<'a>(
...
+    if data.get(0..4) == Some(&[0xFF, 0xD9, 0xFF, 0xD8]) {
         data = &data[4..];
     }
-    if let Some(pos) = (0..data.len() - 4).find(|&n| data[n..n + 4] == [0xFF, 0xD9, 0xFF, 0xD8]) {
-        let mut out_data = Vec::with_capacity(data.len() - 4);
-        out_data.extend_from_slice(&data[..pos]);
-        out_data.extend_from_slice(&data[pos + 4..]);
+    if let Some(pos) = data.windows(4).position(|w| w == [0xFF, 0xD9, 0xFF, 0xD8]) {
+        let mut out_data = data.to_vec();
+        out_data.splice(pos..pos + 4, vec![]);
```
Comment (Herschel) [inline core/src/backend/render.rs:313]: Can we use the `extend_from_slice` here instead? It should avoid a little extra copying (`to_vec` followed by `splice`), particularly because this junk data is quite often at the very beginning of the vec.

**Comment by Herschel** [comment]
Thank you!
