### PR TITLE
core: Fix panic from oversized bitmap warning

### LINKED ISSUE #11908: Error on Back to Alien Party
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/movie_clip.rs:2356:25
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/movie_clip.rs:2356:25
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.dc92645d13601e80b33b.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc123de34c3ab8e83 (wasm://wasm/02d1711a:wasm-function[8764]:0x861256)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d1711a:wasm-function[5753]:0x77c615)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d1711a:wasm-function[8625]:0x85cd9c)
    at core::result::unwrap_failed::he0ddc269083098af (wasm://wasm/02d1711a:wasm-function[6650]:0x7c068f)
    at ruffle_core::display_object::TDisplayObject::path::h3eb67839ec0a0163 (wasm://wasm/02d1711a:wasm-function[2982]:0x601610)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::path::hcaf3a357be8f0af3 (wasm://wasm/02d1711a:wasm-function[2449]:0x57cd29)
    at ruffle_core::display_object::render_base::hd94ca4a07c6cb0ae (wasm://wasm/02d1711a:wasm-function[637]:0x1b83bd)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h0d9e794535d2dc74 (wasm://wasm/02d1711a:wasm-function[6243]:0x79f01a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h867b725133c3efe0 (wasm://wasm/02d1711a:wasm-function[4042]:0x6c7391)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD FirePro W5100 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 600, height: 450, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.newgrounds.com/portal/view/588898/format/flash?emulate=flash
SWF URL: https://uploads.ungrounded.net/588000/588898_backtoalienparty_v1.8.swf?1327938884

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-04
Channel: nightly
Built: 2023-07-04T00:20:28.931Z
Commit: c943866745281bad7f75fcc859ab7f2734385951
Is extension: false

# Metadata
width: 600
height: 450
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3676220

### PR DESCRIPTION
**Pull request by n0samu**
And warn only once per bitmap. Fixes #11908.

### CODE REVIEW

**Review by Lord-McSweeney — APPROVED** [review]

File: core/src/display_object.rs [hunk 1]
```diff
@@ -703,6 +706,7 @@ pub fn render_base<'gc>(this: DisplayObject<'gc>, context: &mut RenderContext<'_
         let mut cache_info: Option<(BitmapHandle, bool, Transform, Rectangle<Twips>)> = None;
         let base_transform = context.transform_stack.transform();
         let bounds: Rectangle<Twips> = this.bounds_with_transform(&base_transform.matrix);
+        let path = this.path();
```
Comment (Dinnerbone) [inline core/src/display_object.rs:709]: I'm a little worried about the cost of calling `path` for every render, but it's true for `bounds_with_transform` too. I'll fix them both up in a followup PR

**Review by Dinnerbone — APPROVED** [review]
