### PR TITLE
naga-pixelbender: Implement Sign opcode 

### LINKED ISSUE #23503: Error on http://seaquence.org/
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1292:29:
Unimplemented opcode Sign

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0"
Enabled features: Features { features_wgpu: FeaturesWGPU(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES), features_webgpu: FeaturesWebGPU(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE) }
Available features: Features { features_wgpu: FeaturesWGPU(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW), features_webgpu: FeaturesWebGPU(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D) }
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_binding_array_elements_per_shader_stage: 0, max_binding_array_sampler_elements_per_shader_stage: 0, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000, max_task_workgroup_total_count: 0, max_task_workgroups_per_dimension: 0, max_mesh_output_layers: 0, max_mesh_multiview_count: 0, max_blas_primitive_count: 0, max_blas_geometry_count: 0, max_tlas_instance_count: 0, max_acceleration_structures_per_shader_stage: 0 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /swf/SeaquenceApp.swf
Param allowscriptaccess: sameDomain
Param quality: high
Param wmode: transparent
Param allowfullscreen: true
Param flashvars: landing=true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: http://seaquence.org/#
SWF URL: http://seaquence.org/swf/SeaquenceApp.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:149.0) Gecko/20100101 Firefox/149.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.2.0-nightly.2026.3.26
Name: 0.2.0-nightly.2026.3.26
Channel: nightly
Built: 2026-03-26T00:13:15.063Z
Commit: 18c74188d4a9690bce196cc1cea0d775e630e6cc
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 172340

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes https://github.com/ruffle-rs/ruffle/issues/23503

### CODE REVIEW

File: render/naga-pixelbender/src/lib.rs [hunk 1]
```diff
@@ -1288,6 +1288,39 @@ impl ShaderBuilder<'_> {
                             arg2: None,
                             arg3: None,
                         }),
+                        Opcode::Sign => {
+                            // FP returns 0 for sign(NaN). Avoid relying on the
+                            // backend's sign() semantics (which may propagate NaN)
+                            // by computing it as (x > 0) - (x < 0).
```
Comment (kjarosh) [inline render/naga-pixelbender/src/lib.rs:1294]: Smart!

File: render/naga-pixelbender/src/lib.rs [hunk 2]
```diff
@@ -1288,6 +1288,39 @@ impl ShaderBuilder<'_> {
...
+
+                            let gt_zero = self.evaluate_expr(Expression::Binary {
+                                op: BinaryOperator::Greater,
+                                left: src,
```
Comment (kjarosh) [inline render/naga-pixelbender/src/lib.rs:1298]: How does it work when src is not a vec4f?

**Review by kjarosh — APPROVED** [review]

File: render/naga-pixelbender/src/lib.rs (hunk 2 above)
Comment (SuchAFuriousDeath) [reply render/naga-pixelbender/src/lib.rs:1298]: https://github.com/ruffle-rs/ruffle/blob/e5cd3b73238f1fb20a4d473be6f10de4225d64cb/render/naga-pixelbender/src/lib.rs#L877

This does a load with padding to a vec4f. So it's always a vec4f.
