### PR TITLE
web: Fix extension and self-hosted builds conflicting with each other

### LINKED ISSUE #1311: "obfuscated_event_prefix" uninitialized variable error on some sites

### LINKED ISSUE #1355: Sproadic error when loading a page w/ both selfhosted and extension
I get the following error occasionally when loading a page using self-hosted while also having the extension installed:

```
Loading SWF file 3516_McFretN2.swf
chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
ruffle.js:1 Serious error loading Ruffle: ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
(anonymous) @ ruffle.js:1
ruffle.js:1 Serious error occurred loading SWF file: ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
stream_swf_url @ ruffle.js:1
ruffle.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
    at Object.ao.f.j (http://localhost:8000/ruffle/ruffle.js:1:25738)
    at http://localhost:8000/ruffle/ruffle.js:1:24017
    at Array.reduce (<anonymous>)
    at Function.ao.e (http://localhost:8000/ruffle/ruffle.js:1:23994)
    at http://localhost:8000/ruffle/ruffle.js:1:1351
    at e.exports (http://localhost:8000/ruffle/ruffle.js:1:1386)
    at new e (http://localhost:8000/ruffle/ruffle.js:1:12261)
    at new e (http://localhost:8000/ruffle/ruffle.js:1:7941)
    at Function.from_native_embed_element (http://localhost:8000/ruffle/ruffle.js:1:8803)
    at f (http://localhost:8000/ruffle/ruffle.js:1:3494)
```
Occurs both in Firefox 82.0 and Chrome 86, often on the first load of the page in a tab. Reloading the page seems to fix the error.
This is running off of a local Python webserver (have not yet tried on a live server).

~May be related to #1354 and started with the bump to webpack 5.~

### PR DESCRIPTION
**Pull request by Toad06**
The web extension currently declares the `runtime_path` variable in the global scope (`extension/js/lv0.js`): this is causing self-hosted builds to be detected as the web extension, because the `fetchRuffle` function assumes that if this variable is set, then we are executing inside the extension (`core/src/load-ruffle.ts`).

- Ruffle script is now injected in an asynchronous function (lv0.js), restoring a previous behavior (https://github.com/ruffle-rs/ruffle/blob/42d724292fc09e7d139df4603963e4229b0983a1/web/extension/build/js/lv0.js). 
- `runtime_path` is renamed to `ruffleRuntimePath` to help preventing conflicts with external scripts.
- Some recent changes in `core/src/public-api.ts` have been reverted. For instance, `prevRuffle?.constructor.name === PublicAPI.name` wasn't checking the source names ("local" or "extension") but... the function names, so `PublicAPI.name` was just returning "PublicAPI" (actually a single letter because minification/obfuscation is enabled), so that didn't seem to help much unless I'm missing something. Also, the `conflict` property always remained `null`.

Should fix #1355, #1702 and #1948.
Also seems to fix #1311.

### CODE REVIEW

File: web/packages/extension/js/lv0.js [hunk 1]
```diff
@@ -141,26 +141,40 @@ get_sync_storage(["ruffle_enable", "ignore_optout"], function (data) {
...
+                    ext_path +
+                    '";\nvar obfuscated_event_prefix = "' +
+                    obfuscated_event_prefix +
+                    '";\n' +
+                    (await ruffle_src_resp.text()) +
+                    "}())";
+                let ruffle_script = document.createElement("script");
+                ruffle_script.appendChild(
+                    document.createTextNode(ruffle_source)
+                );
```
Comment (Herschel) [inline web/packages/extension/js/lv0.js:171]: Might as well make all of these use `camelCase` naming while we're modifying it

Comment (Toad06) [reply web/packages/extension/js/lv0.js]: Yeah, I shouldn't have been that lazy. :D I've now updated all the variables / functions that don't rely on other files.

**Comment by Herschel** [comment]
Thanks!
