### PR TITLE
avm1: Replace recursion with iterative `qsort`

### LINKED ISSUE #18109: [AS2] Array.sortOn: Uncaught RangeError: Maximum call stack size exceeded on large arrays
### Describe what you were doing

1. Launch test swf file:
[test.zip](https://github.com/user-attachments/files/17181061/test.zip)

Code:
```as
var arr = [];
for(var i = 0; i < 8000; i++) {
   arr.push({key: i});  
}
flash.external.ExternalInterface.call("console.log",arr[0]);
arr.sortOn("key",Array.DESCENDING | Array.NUMERIC);
flash.external.ExternalInterface.call("console.log",arr[0]);
```
2. Ruffle crashes after sort attempt (Flash sorts the array in < 1 sec)
3. Expected console.log output:
```
{key: 0}
{key: 7999}
```

### What does the crash message say?

Uncaught RangeError: Maximum call stack size exceeded
    at ruffle_web.wasm.ruffle_wstr::utils::swf_to_lowercase::h81d97944dc74cba0 (ruffle_web.wasm-0322297e:0x853402)
    at ruffle_web.wasm.indexmap::map::IndexMap<K,V,S>::get::hc93a8379153de48e (ruffle_web.wasm-0322297e:0x73f451)
    at ruffle_web.wasm.<ruffle_core::avm1::object::script_object::ScriptObject as ruffle_core::avm1::object::TObject>::get_local_stored::h6964997af4fe8582 (ruffle_web.wasm-0322297e:0x7b59dd)
    at ruffle_web.wasm.<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::get_local_stored::hca73950b602e76a1 (ruffle_web.wasm-0322297e:0x7d2855)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::sort_on_compare::{{closure}}::h71873913f8cb04bc (ruffle_web.wasm-0322297e:0x751aca)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::qsort::h73a5d043759b6b07 (ruffle_web.wasm-0322297e:0x5074d8)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::qsort::h73a5d043759b6b07 (ruffle_web.wasm-0322297e:0x507780)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::qsort::h73a5d043759b6b07 (ruffle_web.wasm-0322297e:0x50772e)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::qsort::h73a5d043759b6b07 (ruffle_web.wasm-0322297e:0x507780)
    at ruffle_web.wasm.ruffle_core::avm1::globals::array::qsort::h73a5d043759b6b07 (ruffle_web.wasm-0322297e:0x50772e)

### Ruffle Version

0.1.0 nightly 2024-09-29

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Additional information

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002504) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: test.swf?v=14
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://xarium.cc/test.html
SWF URL: https://xarium.cc/test.swf?v=14

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-29
Channel: nightly
Built: 2024-09-29T00:06:30.056Z
Commit: 877cfecfde02ff44f2647344f26cffda2c6eea61
Is extension: false

# Metadata
width: 1
height: 1
frameRate: 25
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 652

### PR DESCRIPTION
**Pull request by 123jjck**
Fixes #18109

Speeds up sorting
```as
var arr = [];
var i = 0;
while(i < 3000)
{
   arr.push({key:i});
   i++;
}

flash.external.ExternalInterface.call("console.log",arr[0]);

var startDate = new Date();
flash.external.ExternalInterface.call("console.log","Sorting started at: " + startDate);

arr.sortOn("key",Array.DESCENDING | Array.NUMERIC);

var endDate = new Date();
flash.external.ExternalInterface.call("console.log","Sorting ended at: " + endDate);

flash.external.ExternalInterface.call("console.log",arr[0]);

var duration = endDate.getTime() - startDate.getTime();
flash.external.ExternalInterface.call("console.log","Sorting duration (ms): " + duration);
```
In this example:
Recursion qsort duration: 347ms
Iterative qsort duration: 271ms

### CODE REVIEW

File: core/src/avm1/globals/array.rs [hunk 1]
```diff
@@ -674,70 +674,61 @@ fn qsort<'gc>(
         return Ok(());
     }
 
-    // Fast-path for 2 elements.
-    if let [(_, a), (_, b)] = &elements {
-        if compare_fn(activation, a, b, options)?.is_gt() {
-            elements.swap(0, 1);
+    // Stack for storing subarray boundaries (start and end).
```
Comment (adrian17) [inline core/src/avm1/globals/array.rs:677]: to be sure, it's an inclusive-inclusive range? Can you please add that to the comment?

File: core/src/avm1/globals/array.rs [hunk 2]
```diff
@@ -674,70 +674,61 @@ fn qsort<'gc>(
...
+    let mut stack: Vec<(usize, usize)> = Vec::new();
+
+    stack.push((0, elements.len() - 1));
+
+    while let Some((low, high)) = stack.pop() {
+        if low >= high {
```
Comment (adrian17) [inline core/src/avm1/globals/array.rs:683]: `>` isn't normally possible, right? Can we `assert` that?

File: core/src/avm1/globals/array.rs [hunk 3]
```diff
@@ -674,70 +674,61 @@ fn qsort<'gc>(
         return Ok(());
     }
 
-    // Fast-path for 2 elements.
```
Comment (adrian17) [inline core/src/avm1/globals/array.rs:677]: To be sure, did the fast-path make no difference in perf in your case?

**Review by adrian17 — COMMENTED** [review]
Thank you! Sorry for a delay, I added some review comments. I think this looks fine, though I'm kinda surprised at the 20% speedup.

File: core/src/avm1/globals/array.rs (hunk 1 above)
Comment (123jjck) [reply core/src/avm1/globals/array.rs:677]: > it's an inclusive-inclusive range?

Yes, it is

File: core/src/avm1/globals/array.rs (hunk 2 above)
Comment (123jjck) [reply core/src/avm1/globals/array.rs:683]: > `>` isn't normally possible, right?

Yes, you're right! Should I use `assert!` or `debug_assert!` for this?

File: core/src/avm1/globals/array.rs (hunk 3 above)
Comment (123jjck) [reply core/src/avm1/globals/array.rs:677]: > did the fast-path make no difference in perf in your case?

I didn’t specifically test a fast-path for two elements, but I kept it from the previous implementation

File: core/src/avm1/globals/array.rs (hunk 2 above)
Comment (adrian17) [reply core/src/avm1/globals/array.rs:683]: `assert` does sound nice, unless it kills the performance back.

File: core/src/avm1/globals/array.rs (hunk 3 above)
Comment (adrian17) [reply core/src/avm1/globals/array.rs:677]: I'm confused, you said you kept the fast path, but I don't see it in the diff.
(I'm not asking it to be added or not, just clarifying)

**Comment by adrian17** [comment]
I think it looks good, once you update the PR I can probably quickly test and approve it tomorrow c:

File: core/src/avm1/globals/array.rs (hunk 3 above)
Comment (123jjck) [reply core/src/avm1/globals/array.rs:677]: > I don't see it in the diff.

Sorry, you're right. I thought it wouldn't make much difference in an iterative algorithm.

**Comment by 123jjck** [comment]
Okay, now the tests are failing
I need more time to figure this out

P.S. And sorry for the commit names

**Comment by 123jjck** [comment]
I think we can't replace the normal check with assert because low >= high can occur when the pivot partition results in a subarray with no elements. (e.g., [5, 5, 5, 5, 5])

File: core/src/avm1/globals/array.rs (hunk 2 above)
Comment (123jjck) [reply core/src/avm1/globals/array.rs:683]: I think we can't replace the normal check with assert because low >= high can occur when the pivot partition results in a subarray with no elements. (e.g., [5, 5, 5, 5, 5])

Comment (adrian17) [reply core/src/avm1/globals/array.rs:683]: I know `low == high` can occur, but I meant that specifically `low > high`  shouldn't ever occur.

**Review by adrian17 — APPROVED** [review]
I don't think that `assert` is strictly critical, so I think this can go in as-is (let's just squash on merge).

**Comment by adrian17** [comment]
Thank you!
