### PR TITLE
core: Stop sounds attached to an unloaded root movie

### LINKED ISSUE #17059: Audio
### Describe the bug

I have audio issue like it cut out or not their at all 

### Expected behavior

I just listen to my favorite games

### Content Location

https://www.newgrounds.com/portal/view/813661 

### Affected platform

Browser's extension

### Operating system

IOS

### Browser

Chrome

### Additional information

_No response_

### LINKED ISSUE #17395: KR Wizard Flash Belt - Missing Sound
### Describe the bug

Reported by Mega Gamer: "I don’t hear the transformation sounds whenever I do a transformation."

### Expected behavior

The sound is expected to play.

### Content Location

https://www.newgrounds.com/portal/view/779798

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 126.0.6478.127

### Additional information

_No response_

### LINKED ISSUE #17718: [Regression] Text boxes stop music playback in Super Mario Bros Z Episode 6
### Describe the bug

In [Super Mario Bros Z Episode 6](https://github.com/user-attachments/files/16826051/smbzep6.zip), when a text box appears to show dialogue, the music playback is stopped. This is a regression as this didn't use to happen, and it isn't supposed to happen.
The music is supposed to keep playing while the text box is open.
The adobe flash player also keeps playing the music.

I'm not exactly sure when the regression was introduced, but I remember playing the episode back in June, and this issue wasn't present back then.

### Expected behavior

The music should keep playing

### Content Location

[smbzep6.zip](https://github.com/user-attachments/files/16826051/smbzep6.zip)

Also, https://www.newgrounds.com/portal/view/380713/format/flash

The ruffle web player on newgrounds also exhibits the regression.

### Affected platform

Desktop app, Web player

### Operating system

Linux (X11, ALSA/Pipewire)

### Browser

_No response_

### Additional information

_No response_

### LINKED ISSUE #18057: ドラDORAジャンケン (Dora DORA Janken) - Very minor audio regression
### Describe the bug

As of the July 8th 2024 nightly builds, tested on both web and desktop, there is the slightest regression that has occurred in this game where the sound effect on game-start does not play.
The only output from the logs via the desktop app that might be relevant are the warnings from symphonia about overflow, underflow, and invalid starting and end positions in the byte streams, but those are warnings I've always seen and had no issues.
Yes, this is an old version 5 SWF.

### Expected behavior

Transition sound should play on game start

### Content Location

[djk_0329.zip](https://github.com/user-attachments/files/17108474/djk_0329.zip)

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chromium Edge

### Additional information

2024-09-24T05:14:11.954312Z  WARN symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 91 bytes    
2024-09-24T05:14:13.996396Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:14.167027Z  WARN symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:14.337020Z  WARN symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:14.507021Z  WARN symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:14.677043Z  WARN symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:16.166683Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:16.964324Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:19.230101Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:20.542982Z  WARN run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes    
2024-09-24T05:14:22.309447Z  WARN run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 91 bytes    
2024-09-24T05:14:23.142786Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 91 bytes    
2024-09-24T05:14:24.676003Z  WARN run_frame:run_frame: symphonia_bundle_mp3::layer3: mpa: invalid main_data_begin, underflow by 65 bytes

### LINKED ISSUE #18181: Vanilla Nexus RPG - Sound FX Regression
### Describe the bug

carbonlad on NG reports: "My game was working quite well for awhile from October of last year , til the most recent ruffle update

I was really happy when they fixed the purple in my game(???) somehow

Now its just a minor bug of getting the sound effects to work, all sound effects work funny

E.g.

1) The Text from the NPC at the beginning wont beep off like it will in Zelda, but it used to

2) Most sound effects like attacks or item uses dont work

3) The BGM will play fine, no problem."

Note - the most recent Ruffle update on NG at this time was the 10/4 build but it could likely have been any other update in recent weeks, if any had to do with audio.

### Expected behavior

The sound is expected to work as before.

### Content Location

https://www.newgrounds.com/portal/view/846832

### Affected platform

Self-hosted version

### Operating system

Asked carbonlad

### Browser

_No response_

### Additional information

_No response_

### LINKED ISSUE #18327: [Linux] Audio stream cancelling
### Describe the bug

https://github.com/user-attachments/assets/e1164f71-74ef-4cfb-a2ba-32bfbc22d73e

### Expected behavior

https://github.com/user-attachments/assets/15830c2f-8aed-432e-9e8e-d6c51e96eba8

### Content Location

https://cache.armorgames.com/files/games/hobo-7-heaven-14404.swf

### Affected platform

Desktop app

### Operating system

Linux Mint 22

### Browser

_No response_

### Additional information

Started happening at version "ruffle-nightly-2024_07_08".
Using "linux-x86_64.tar.gz".

### PR DESCRIPTION
**Pull request by Toad06**
... instead of doing this for each unloaded display object.

Fixes #18327.
Fixes #18181.
Fixes #18057.
Fixes #17718.
Fixes #17395.
This should fix #17059 as well... but I'm not sure where the issues are supposed to be. 😅

I also checked against the files mentioned in #17016 and can confirm that they continue to stop sounds as expected. However, I was unable to test #16947 due to the web server being down. For #963, I tested it on [FlashArch](https://flasharch.com/en/archive/play/2f4ee6ce445533f1f46a1ec8090e463f), since the file appears to be no longer accessible on the official site.

[Super Monkey Ball Mini](https://wondertrio.com/games/monkeyball/index.html) is an interesting test case, as it experienced both issues in sequence:
- Before [#17016](https://github.com/ruffle-rs/ruffle/pull/17016), the music from the title screen continued playing when entering a level instead of stopping.
- After [#17016](https://github.com/ruffle-rs/ruffle/pull/17016), while the title screen music did stop correctly, some sound effects unexpectedly stopped (for example, when clicking on a level index) or failed to play altogether (such as the "Go" sound when starting a level).

### CODE REVIEW

File: core/src/backend/audio.rs [hunk 1]
```diff
@@ -532,6 +532,38 @@ impl<'gc> AudioManager<'gc> {
...
+    /// Stops any sound associated with the given Display Object and its children. The DO must represent the parent.
+    /// Sounds associated with DOs are an AVM1/Timeline concept and should not be called from AVM2 scripts.
+    pub fn stop_sounds_on_parent_and_children(
+        &mut self,
+        audio: &mut dyn AudioBackend,
+        display_object: DisplayObject<'gc>,
+    ) {
+        self.sounds.retain(move |sound| {
+            if let Some(other) = sound.display_object {
+                let stop = if DisplayObject::ptr_eq(other, display_object) {
```
Comment (Lord-McSweeney) [inline core/src/backend/audio.rs:544]: Could this be merged into something like
```
let mut other_do = Some(other);
while let Some(other) = other_do {
    if DisplayObject::ptr_eq(other_do, display_object) {
        audio.stop_sound(sound.instance);
        return false;
    }
    other_do = other.parent();
}
```
?

Comment (Toad06) [reply core/src/backend/audio.rs:544]: Nice solution! It's shorter and cleaner, and I believe it should work. I'll give it a try tomorrow. 😉

**Review by Lord-McSweeney — APPROVED** [review]

**Comment by torokati44** [comment]
Thank you! 🚀

**Comment by Toad06** [comment]
Thanks for the review and merge!
