### PR TITLE
web: Add query string to `Report Bug` link

### LINKED ISSUE #1753: Include error details when you click on report bug and/or open GitHub in a new tab
i realised that https://github.com/ruffle-rs/ruffle-rs.github.io was the wrong place after all as that repo is for the website and this issue is about the web player, and more specifically, the demo. _please forgive me for my sins_ 🙏 (especially if this is wrong too!!!)

i think these might help: https://github.com/sindresorhus/new-github-issue-url
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters
:)

### PR DESCRIPTION
**Pull request by JMcKiern**
This automatically fills in the issue report so that the user doesn't have to copy-paste the error details from Ruffle to GitHub. Closes #1753 

Let me know if there is a better Issue Title.

Also, it could be worth including a description from the user perhaps?

For example:
```
# Description

[Please explain what was happening when you encountered the error]
```

### CODE REVIEW

File: web/packages/core/src/ruffle-player.ts [hunk 1]
```diff
@@ -406,6 +407,10 @@ export class RufflePlayer extends HTMLElement {
 
                 if ("url" in options) {
                     console.log("Loading SWF file " + options.url);
+                    this.swfUrl = new URL(
+                        options.url,
+                        document.location.href
+                    ).href;
```
Comment (Herschel) [inline web/packages/core/src/ruffle-player.ts:413]: URL constructor can fail if you give it an invalid URL, for example, this blows up for me:
`player.load("http://? invalid ?");`
We need to handle this better in general, (cc #1824) but at least we probably shouldn't throw at this point. Could just wrap it in a try/catch for now, defaulting to options.url.

Comment (JMcKiern) [reply web/packages/core/src/ruffle-player.ts]: Sorry, I should have checked that. I've added the try-catch block now.

I don't think there's much point in adding an error message since whatever solution is proposed for #1282 while likely log the same error.

Let me know if you disagree and I can add a small error message.

**Comment by Herschel** [comment]
Thank you!
