### PR TITLE
avm2: Only look at valid Exceptions in verifier

### LINKED ISSUE #15920: League of Stickman
### Describe the bug

The game is loading, but it starts with the 'game-over' screen.

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x61ccf8 }) to handler FunctionObject(FunctionObject { ptr: 0x8e32b10, name: Ok("display::Anniu/onMouseClick()") }) : VerifyError: Error #1054: Illegal range or target offsets in exception handler.`

### Expected behavior

To work correctly. 

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=archive/4/league-of-stickman/game.swf&params=&name=League%20of%20Stickman)

[Flash](https://www.y8.com/games/league_of_stickman)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #15920

### CODE REVIEW

File: core/src/avm2/verify.rs [hunk 1]
```diff
@@ -131,16 +133,23 @@ pub fn verify_method<'gc>(
...
-                    worklist.push(exception.target_offset);
-                    seen_targets.insert(exception.target_offset as i32);
+                    if !seen_targets.contains(&(exception.target_offset as i32)) {
+                        worklist.push(exception.target_offset);
+                        seen_targets.insert(exception.target_offset as i32);
+                    }
+
+                    // Keep track of all the valid exceptions, and only verify
+                    // them- this is more lenient than avmplus, but still safe.
+                    if !seen_exception_indices.contains(&exception_index) {
```
Comment (adrian17) [inline core/src/avm2/verify.rs:150]: I think the entry() API would let you avoid a double lookup (contains -> insert)

Comment (Lord-McSweeney) [reply core/src/avm2/verify.rs:150]: This is a `HashSet` though
