### PR TITLE
avm2: Handle null result callback in Responder

### LINKED ISSUE #15247: AMF: Parameter result must be non-null (event fails to dispatch)
### Describe the bug

With certain AMF requests, the following error occurs:

```
[Panfu.log] remote > send: amfConnectionService.ping => 
ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "timer", class: flash.events::TimerEvent, ptr: 0xc43d858 }) to handler FunctionObject(FunctionObject { ptr: 0x7d37150, name: Ok("com.pandaland.util.manager::TimeoutManager$/onTimer()") }) : TypeError: Error #2007: Parameter result must be non-null.
```

Here is another example:

```
[Panfu.log] remote > send: amfActionService.performAction => 98010,fireworks
ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "fireworksSent", class: com.pandaland.events::AvatarEvent, ptr: 0xb1448f0 }) to handler FunctionObject(FunctionObject { ptr: 0x9a12978, name: Ok("com.pandaland.mvc.view.avatar::AvatarMediator/onFireworksSent()") }) : TypeError: Error #2007: Parameter result must be non-null.
```

### Expected behavior

There should be no error with these AMF requests and the event should be dispatched successfully.

### Content Location

The bug is reproducible on [our website](https://www.panfu.us), a ping is sent every minute when logged in, and the error is also output with every AMF request for the ping.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 121

### Additional information

_No response_

### LINKED ISSUE #17062: Panfu: Birthday cannot be changed
### Describe the bug

The following error appears in the console when you try to change your date of birth:

```
Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0xe53aa48 }) to handler FunctionObject(FunctionObject { ptr: 0xd3b16a8, name: Ok("com.pandaland.ui.button::Button/onClick()") }) : TypeError: Error #2007: Parameter result must be non-null.
```

### Expected behavior

It should be possible to change the birthday.

### Content Location

The bug can be reproduced on [our website](https://www.panfu.us). An account is required.

Click on your avatar, then click on the pencil and fill out the fields.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 126.0.6478.127

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by robinmiau**
Fixes #15247 & #17062

Previously, passing `null` as the `result` callback to `Responder` threw:
```
Error #2007: Parameter result must be non-null
```

The argument is now optional and silently ignored if it is not callable, matching Flash's behaviour.

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Thank you for the contribution!

File: core/src/avm2/globals/flash/net/responder.rs [hunk 1]
```diff
@@ -11,12 +11,12 @@ pub fn init<'gc>(
 
     let responder = this.as_responder().expect("Must be Responder object");
 
-    let result = args.get_object(activation, 0, "result")?;
+    let result = args.try_get_object(0);
     let status = args.try_get_object(1);
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/flash/net/responder.rs]: nit: These can probably use `args.try_get_function`

**Comment by Lord-McSweeney** [comment]
Could you add a test case for this? There are some instructions in `tests/README.md`. Something that checks that `trace(new Responder(null, null));` traces `[object Responder]` instead of erroring would be enough.

File: core/src/avm2/globals/flash/net/responder.rs (hunk 1 above)
Comment (robinmiau) [reply core/src/avm2/globals/flash/net/responder.rs]: should I update them?

Comment (Lord-McSweeney) [reply core/src/avm2/globals/flash/net/responder.rs]: Yes, please do

Comment (robinmiau) [reply core/src/avm2/globals/flash/net/responder.rs]: Done!

Comment (robinmiau) [reply core/src/avm2/globals/flash/net/responder.rs]: I've now fixed all the errors from the failing tests. I hope everything is fine now!

File: tests/tests/swfs/avm2/responder_null_callbacks/Test.as [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package {
+    public class Test {}
```
Comment (kjarosh) [inline tests/tests/swfs/avm2/responder_null_callbacks/Test.as]: The test throws an error in Flash Player (which is missing from output.txt):

```
TypeError: Error #2023: Class Test$ must inherit from Sprite to link to the root.
```

You need to make `Test` extend `Sprite` to get rid of the error.

Comment (robinmiau) [reply tests/tests/swfs/avm2/responder_null_callbacks/Test.as]: Done, I also recompiled the test.swf

**Review by kjarosh — APPROVED** [review]
LGTM, thank you!
