### PR TITLE
web: Don't use direct eval, use indirect new Function(...) instead

### LINKED ISSUE #8330: New Club Penguin not supported ruffle player
### Describe the bug

https://user-images.githubusercontent.com/80902993/196750362-eb8831bc-c234-41c8-aa41-40d783b669d0.mp4

it's not working, because this is multi files, this is actionsupport 3.0
i know ruffle player multiplayer is not working

### Expected behavior

Screenshot 2022-10-19 192944
you know ''Download'' and ''Launch NewCP App'' it's can work with flash player, his server it's working

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge

### Additional information

from https://newcp.net/en/

### PR DESCRIPTION
**Pull request by Dinnerbone**
This fixes #8330 (club penguin / newcp.net). It works surprisingly well, minor issues so far - mostly audio and text. Decent performance too!

It looks like my earlier PR to make LocalConnection likely would have fixed Club Penguin in general, but this specific site uses some javascript that doesn't work in strict mode. This change (thanks @evilpie for the recommendation to use Function!) makes it work!

The site needs a proxy to get working, which I'll leave as an exercise to the site owners.

image

### CODE REVIEW

File: web/packages/core/src/ruffle-imports.ts [hunk 1]
```diff
@@ -65,14 +65,7 @@ export function copyToAudioBufferInterleaved(
  *
  * @internal
  */
-// @ts-expect-error defined but not used
 // eslint-disable-next-line @typescript-eslint/no-explicit-any,@typescript-eslint/no-unused-vars
 export function callExternalInterface(name: string, args: any[]): any {
-    // [NA] Yes, this is direct eval. Yes, this is a Bad Thing when it comes to security.
```
Comment (evilpie) [inline web/packages/core/src/ruffle-imports.ts:71]: `new Function` is still basically eval, please keep the comment.

File: web/packages/core/src/ruffle-imports.ts [hunk 2]
```diff
@@ -65,14 +65,7 @@ export function copyToAudioBufferInterleaved(
  *
  * @internal
  */
-// @ts-expect-error defined but not used
 // eslint-disable-next-line @typescript-eslint/no-explicit-any,@typescript-eslint/no-unused-vars
```
Comment (evilpie) [inline web/packages/core/src/ruffle-imports.ts:68]: You can probably remove `no-unused-vars` now?

**Review by evilpie — APPROVED** [review]
