### PR TITLE
Don't panic when the movie root is removed

### LINKED ISSUE #5208: Error on chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/player.html
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:481:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:481:14
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/player.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::h0b0859852caeb5a6 (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[916]:0x244248)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[1173]:0x2a2441)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc9102d6ce52f2ea2 (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[4043]:0x42f0a9)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[2909]:0x3c3d6c)
    at rust_begin_unwind (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[4257]:0x434ade)
    at core::panicking::panic_fmt::h1fea623755fffed7 (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[4416]:0x43bae3)
    at core::option::expect_failed::h5a948c549ae5374a (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[3990]:0x42d802)
    at ruffle_core::display_object::stage::Stage::root_clip::h9f953e38641135d8 (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[2856]:0x3c05c9)
    at ruffle_web::Ruffle::tick::hb385ab9d079e798d (chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/dist/4d2f11ba93ccfb2ca3ee.wasm:wasm-function[515]:0x16539c)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://cmgohaobbaodbgmechhfamiekhlniadb/player.html?url=https://static.familyspace.ru/swf/tree/tree.test.domain.swf
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-02
Channel: nightly
Built: 2021-09-02T00:12:32.691Z
Commit: ec85e18e095e3d728b69cdf571b171aa1e19e3d2
Is extension: true

### LINKED ISSUE #5330: Error on chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/player.html
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:481:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:481:14
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/player.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h79e4330f0ce30987 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[950]:0x2779e7)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[1200]:0x2cf992)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h593050f4ffa2b904 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[4197]:0x45f4f1)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[3029]:0x3f8bd4)
    at rust_begin_unwind (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[4415]:0x465020)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[4598]:0x46c5b9)
    at core::option::expect_failed::h66afff61e82fdd86 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[4142]:0x45dbad)
    at ruffle_web::Ruffle::tick::h2264033552e64de2 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[526]:0x180667)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h9c124272a64adaa9 (chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/dist/fcf929249022847b08a7.wasm:wasm-function[5127]:0x47818e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://gfhjhnbngajgoncgcpooiehcgahagklk/player.html?url=https://static.familyspace.ru/swf/tree/tree.test.domain.swf
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-14
Channel: nightly
Built: 2021-09-14T00:12:54.264Z
Commit: a882f85d14bd7d3d8e9d372dd3549e6e9fddc598
Is extension: true

### LINKED ISSUE #5832: Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:544:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:544:14
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h28627feee31e90eb (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[1024]:0x3123b8)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[1239]:0x36c306)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha861918671b1460e (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[4743]:0x51e78b)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[3321]:0x4d7d22)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[4806]:0x521080)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[5018]:0x52bcf7)
    at core::option::expect_failed::h15ce9e60c302a5c5 (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[5086]:0x52cdfb)
    at ruffle_web::Ruffle::tick::hb2b3b01b33be7c87 (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[581]:0x216eba)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h942e58ba84749bb6 (http://www.freeworldgroup.com/ruffle/1f1d6851f1b81dfd26a5.wasm:wasm-function[5579]:0x5386dc)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-09
Channel: nightly
Built: 2021-12-09T00:11:45.589Z
Commit: 0a25ebbc32faf2ba4f21bc2c4a647d0baa1d5e6b
Is extension: false

### LINKED ISSUE #5948: Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:544:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:544:14
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/player.js:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[1000]:0x30efb6)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[1192]:0x35318b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[4707]:0x50c322)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[3243]:0x4b900c)
    at rust_begin_unwind (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[4770]:0x50d870)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[4983]:0x518753)
    at core::option::expect_failed::h15ce9e60c302a5c5 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[5051]:0x519590)
    at ruffle_web::Ruffle::tick::hb9d842e238c03a03 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[602]:0x22e0e6)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf1137b90d4f64c37 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6a4730a83caca4e15604.wasm:wasm-function[5549]:0x524f3a)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https://2f63df7c-a-62cb3a1a-s-sites.googlegroups.com/site/g4m3store/zombocalypse-2.1.swf?attachauth=ANoY7cronUevjRsfhJm1ZfxTFTVaoUQ-wjbWmyqa_IFuB53d1GvSDHbrmqkInB__kEL0wXEFoekEctb7Ojt6KgAmQS02DTfie14Cs2M7zHJPJOLP0aSQmYukNjKVsvoB3WyA3AUFGi5DWMhIuNwO-zJ8SJHhFOWDHAu-JFyCRiFNH8jEUbMHRugaq3c4Xv3sCmAOu150VPXz27ja7HoagCgV_Azitm099g%3D%3D&attredirects=0
SWF URL: https://2f63df7c-a-62cb3a1a-s-sites.googlegroups.com/site/g4m3store/zombocalypse-2.1.swf?attachauth=ANoY7cronUevjRsfhJm1ZfxTFTVaoUQ-wjbWmyqa_IFuB53d1GvSDHbrmqkInB__kEL0wXEFoekEctb7Ojt6KgAmQS02DTfie14Cs2M7zHJPJOLP0aSQmYukNjKVsvoB3WyA3AUFGi5DWMhIuNwO-zJ8SJHhFOWDHAu-JFyCRiFNH8jEUbMHRugaq3c4Xv3sCmAOu150VPXz27ja7HoagCgV_Azitm099g==

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-18
Channel: nightly
Built: 2021-12-18T00:12:38.923Z
Commit: a25a25adbcb8aa3440ba12ddf5a65b381eeae881
Is extension: true

### LINKED ISSUE #6180: Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:545:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:545:14
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4996]:0x4dfa20)
    at core::option::expect_failed::hdf65ec749c93533c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[5066]:0x4e0bb1)
    at ruffle_web::Ruffle::tick::hf8a4913ed3d1fe2b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[612]:0x2210c6)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h66b090fd1f9bd1c2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[5564]:0x4ec9ab)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[5136]:0x4e1c5c)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fstatic.familyspace.ru%2Fswf%2Ftree%2Ftree.test.domain.swf
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-31
Channel: nightly
Built: 2022-01-31T00:17:51.537Z
Commit: 83cc9dc30834acdf8bc03c9fe7392713a7e53792
Is extension: true

### LINKED ISSUE #6778: Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:568:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:568:14
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7706)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[1012]:0x2ab733)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[1445]:0x31f9ca)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[4923]:0x479c8d)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[3241]:0x41d211)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[5005]:0x47db66)
    at core::option::expect_failed::h52436cb58dfe4ec3 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[5624]:0x48bac1)
    at ruffle_core::display_object::stage::Stage::root_clip::h8b428fe615367dd4 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[3560]:0x433eed)
    at ruffle_web::Ruffle::tick::h4000be57199ea5b7 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[550]:0x1c64ec)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h499560f5f1a2f344 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[5797]:0x49426b)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fstatic.familyspace.ru%2Fswf%2Ftree%2Ftree.test.domain.swf
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-20
Channel: nightly
Built: 2022-04-20T00:19:00.226Z
Commit: 7cbba5bc8ff38a9a422664fd6b595af39b6bffe7
Is extension: true

### LINKED ISSUE #9907: Error on https://www.gameflare.com/embed/comic-book-cody/
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameflare.com/emulators/ruffle/core.ruffle.318c287647bc6ddfd4a5.js:1:46442)
    at std::sync::once::Once::call_once::{{closure}}::he918ee3086b261a7 (wasm://wasm/0294aade:wasm-function[2039]:0x4f07fb)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294aade:wasm-function[1972]:0x4e12ad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2612a5ee62d4acb8 (wasm://wasm/0294aade:wasm-function[7469]:0x7b46b8)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294aade:wasm-function[5256]:0x70b66b)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294aade:wasm-function[7798]:0x7c395a)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0294aade:wasm-function[9014]:0x7eef3f)
    at ruffle_core::display_object::stage::Stage::root_clip::h7224dcdb6873ec89 (wasm://wasm/0294aade:wasm-function[5250]:0x70a7a9)
    at ruffle_web::Ruffle::tick::hc071183f2d30a9f1 (wasm://wasm/0294aade:wasm-function[672]:0x245258)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0f689e8c306409dd (wasm://wasm/0294aade:wasm-function[9482]:0x8010b2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/comic-book-cody/
SWF URL: https://data.gameflare.com/games/4090/zp2wjnuZhppPNT.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-06
Channel: nightly
Built: 2023-03-06T00:20:07.108Z
Commit: 806c0fe052cd26a88b6a64353a15155a5f27b1e8
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 5772341

### PR DESCRIPTION
**Pull request by Dinnerbone**
So there's two key things to the whole rootless movie thing:
- AVM1 has, as far as I can tell, no way to remove the root movie. I don't know what the behaviour should be for AVM1 activations when there's no root movie as I haven't found a way to test it. I added a panic for when we try to do that, and we'll just have to watch for it and see how it was being used.
- AVM2 not only allows you to remove the root movie, but many games do this deliberately as either a sitelock or "lazy root swap" technique. It's not an error to operate entirely without a movie in AVM2, as things can execute as orphans (thanks Aaron!)

Every movie with this error needs to be retested to see if it's fixed, however from my own testing I can see that some movies error from unrelated things before they have a chance to reattach root, so some things might go from panicking to just being blocked on something else.

Confirmed fixes:
Fixes #9907
Fixes #5208
Fixes #5330 
Fixes #5832
Fixes #5948 (further blocked by TypeError #1009)
Fixes #6180 (no idea what that swf is supposed to do)
Fixes #6778 (same as above)
And then I got tired for now. It fixes a lot.

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Seems to regress #9866 (only shows the background color now)

**Comment by Lord-McSweeney** [comment]
Progresses #9226, though it doesn't get into the game and there's a lot of `WARN ruffle_core::timer: Ignoring timers as there's no root movie` spam.

**Comment by Dinnerbone** [comment]
> Seems to regress #9866 (only shows the background color now)

This appears to be the case on master too.

**Comment by Dinnerbone** [comment]
> Progresses #9226, though it doesn't get into the game and there's a lot of `WARN ruffle_core::timer: Ignoring timers as there's no root movie` spam.

Doesn't seem to change it for me? It's the same as on master.

File: core/src/timer.rs [hunk 1]
```diff
@@ -41,7 +41,12 @@ impl<'gc> Timers<'gc> {
             return None;
         }
 
-        let level0 = context.stage.root_clip();
+        let level0 = if let Some(level0) = context.stage.root_clip() {
+            level0
+        } else {
+            tracing::warn!("Ignoring timers as there's no root movie");
+            return None;
```
Comment (Aaron1011) [inline core/src/timer.rs:48]: This should be gated behind `!context.is_actionscript_3() `, since we can still run Avm2 timers without a root movie

Comment (Dinnerbone) [reply core/src/timer.rs:48]: Yeah realized that now and working on a fix!

Comment (Dinnerbone) [reply core/src/timer.rs]: Fixed (but differently, I run the AVM2 timers only)

File: core/src/context_menu.rs [hunk 2]
```diff
@@ -34,9 +34,13 @@ impl<'gc> ContextMenuState<'gc> {
         &self.callbacks[index]
     }
     pub fn build_builtin_items(&mut self, item_flags: BuiltInItemFlags, stage: Stage<'gc>) {
-        let root_mc = stage.root_clip().as_movie_clip();
+        let root_mc = if let Some(root_clip) = stage.root_clip().and_then(|c| c.as_movie_clip()) {
+            root_clip
+        } else {
+            return;
+        };
```
Comment (Bale001) [inline core/src/context_menu.rs:41]: nit: This can just be
```suggestion
        let Some(root_mc) = stage.root_clip().and_then(|c| c.as_movie_clip()) else {
            return;
        };
```

**Review by Bale001 — APPROVED** [review]

File: core/src/context_menu.rs (hunk 2 above)
Comment (Dinnerbone) [reply core/src/context_menu.rs:41]: I had no idea that syntax worked!
