### PR TITLE
avm1: Fix various opcodes

### LINKED ISSUE #3833: Error on https://unblockedgames.blogbucket.org/streets-of-vallaha-hacked/
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:536:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:536:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unblockedgames.blogbucket.org/ruffle/ruffle.js:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (<anonymous>:wasm-function[1187]:0x283764)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (<anonymous>:wasm-function[1773]:0x2fe727)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (<anonymous>:wasm-function[5273]:0x40ad6b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (<anonymous>:wasm-function[4049]:0x3dc8da)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (<anonymous>:wasm-function[4752]:0x3fd4e3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (<anonymous>:wasm-function[5646]:0x410a83)
    at rust_begin_unwind (<anonymous>:wasm-function[5517]:0x40f0c7)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (<anonymous>:wasm-function[5648]:0x410ae7)
    at core::panicking::panic::h5da66f104e83c46a (<anonymous>:wasm-function[5445]:0x40de5f)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://files.blogbucket.org/2017/valhallahacked.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://unblockedgames.blogbucket.org/streets-of-vallaha-hacked/
SWF URL: https://files.blogbucket.org/2017/valhallahacked.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13597.105.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.208 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-28
Channel: nightly
Built: 2021-03-28T00:41:48.808Z
Commit: 0063f40af9cd6dd39038d67880db1d996176c309

### PR DESCRIPTION
**Pull request by relrelb**
Fixes #3833.

### CODE REVIEW

File: core/src/avm1/activation.rs [hunk 1]
```diff
@@ -806,6 +806,7 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
         let fn_name_value = self.context.avm1.pop();
         let fn_name = fn_name_value.coerce_to_string(self)?;
         let num_args = self.context.avm1.pop().coerce_to_f64(self)? as usize; // TODO(Herschel): max arg count?
+        let num_args = num_args.min(self.context.avm1.stack.len());
```
Comment (Herschel) [inline core/src/avm1/activation.rs:809]: From testing, `num_args` seems like it should use `coerce_to_u32` (wraps at `4294967297`). This also means that `-1` ends up acting like `u32::MAX` and would pop all values off of the stack.

File: core/src/avm1/activation.rs [hunk 2]
```diff
@@ -829,9 +830,10 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
     }
 
     fn action_call_method(&mut self) -> Result<FrameControl<'gc>, Error<'gc>> {
-        let method = self.context.avm1.pop();
+        let method_name = self.context.avm1.pop();
         let object_val = self.context.avm1.pop();
         let num_args = self.context.avm1.pop().coerce_to_f64(self)? as usize; // TODO(Herschel): max arg count?
```
Comment (Herschel) [inline core/src/avm1/activation.rs:835]: Ditto, `coerce_to_u32`.

File: core/src/avm1/activation.rs [hunk 3]
```diff
@@ -1500,25 +1503,38 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
...
-        let mut interfaces = vec![];
+        let constructor = self.context.avm1.pop().coerce_to_object(self);
+        let count = self.context.avm1.pop();
+        // Old Flash Players (at least FP9) used to coerce objects as well. However, this was
+        // changed at some point and instead the following is logged:
+        // "Parameters of type Object are no longer coerced into the required primitive type - number."
+        // Newer Flash Players coerce only primitives, and treats objects as 0.
+        let count = if count.is_primitive() {
+            count.coerce_to_f64(self)? as usize
+        } else {
```
Comment (Herschel) [inline core/src/avm1/activation.rs:1524]: ImplementsOp seems to not pop anything if count >= 2147483648

File: core/src/avm1/activation.rs [hunk 4]
```diff
@@ -1687,6 +1703,7 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
         let method_name = self.context.avm1.pop();
         let object_val = self.context.avm1.pop();
         let num_args = self.context.avm1.pop().coerce_to_f64(self)? as usize;
+        let num_args = num_args.min(self.context.avm1.stack.len());
```
Comment (Herschel) [inline core/src/avm1/activation.rs:1706]: `coerce_to_u32`

File: core/src/avm1/activation.rs [hunk 5]
```diff
@@ -1720,6 +1750,7 @@ impl<'a, 'gc, 'gc_context> Activation<'a, 'gc, 'gc_context> {
         let fn_name_val = self.context.avm1.pop();
         let fn_name = fn_name_val.coerce_to_string(self)?;
         let num_args = self.context.avm1.pop().coerce_to_f64(self)? as usize;
+        let num_args = num_args.min(self.context.avm1.stack.len());
```
Comment (Herschel) [inline core/src/avm1/activation.rs:1753]: `coerce_to_u32`

**Review by Herschel — CHANGES_REQUESTED** [review]
If possible, could you add a test for the `NewMethod` undefined case?

I figure this was a good time to go through and figure out the wrapping behavior for the arg counts in all of these ops, so I made hand-edited SWFs that pushed negative or large doubles for the arg count to see the behavior. Wrote my notes on each op. Mostly:
 * Function calls do a `coerce_to_u32` for their arg count. This means negative values will coerce to large u32 value and effectively pop the entire stack.
 * Other ops like `InitArray` and `InitObject` only work from 0 to 2147483647. >= 2147483648 causes the op to bail out.

**Comment by Herschel** [comment]
Thought it might be useful to post the actual test FLAs.
InitObject with negative num_args (pushes undefiend):
[initobject-negative.zip](https://github.com/ruffle-rs/ruffle/files/6412114/initobject-negative.zip)

InitObject with 4294967296.0 num_args (pushes undefined):
[initobject-large.zip](https://github.com/ruffle-rs/ruffle/files/6412115/initobject-large.zip)

NewObject with -1 num_args (coerces to 4294967295.0, effectively `new Object(stack1, stack2, stack3, ...)`:
[newobject-large.zip](https://github.com/ruffle-rs/ruffle/files/6412125/newobject-large.zip)

NewObject with 4294967296.0 num_args (wraps to 0):
[newobject-large2.zip](https://github.com/ruffle-rs/ruffle/files/6412118/newobject-large2.zip)


Here's the code I used to generate these.
```
use std::fs::File;

use swf::avm1::types::{Action, Function, Value};
use swf::*;

type Error = Box<dyn std::error::Error>;

fn main() -> Result<(), Error> {
    const VERSION: u8 = 8;

    let func_actions = vec![Action::Push(vec![Value::Str("2".into())]), Action::Return];
    let func_data = write_actions(&func_actions)?;

    let actions = vec![

        Action::Push(vec![
            Value::Str("a".into()),
            Value::Str("b".into()),
            Value::Str("c".into()),
            Value::Double(-3.0),
        ]),
        
        Action::InitObject,
        Action::Trace,
        Action::Trace,
        Action::Trace,
        Action::Trace,
       
    ];
    let action_data = write_actions(&actions)?;

    let tags = vec![
        Tag::FileAttributes(FileAttributes {
            use_direct_blit: false,
            use_gpu: false,
            has_metadata: false,
            is_action_script_3: false,
            use_network_sandbox: false,
        }),
        Tag::SetBackgroundColor(Color::from_rgb(0xeeeeee, 255)),
        Tag::DoAction(&action_data),
        Tag::ShowFrame,
    ];
    let swf = Swf {
        header: Header {
            compression: Compression::None,
            version: VERSION,
            uncompressed_length: 0,
            stage_size: Rectangle {
                x_min: Default::default(),
                y_min: Default::default(),
                x_max: Twips::from_pixels(800.0),
                y_max: Twips::from_pixels(600.0),
            },
            frame_rate: 30.0,
            num_frames: 1,
        },
        tags,
    };
    let mut swf_data = vec![];
    write_swf(&swf, &mut swf_data)?;
    std::fs::write("out.swf", &swf_data)?;
    Ok(())
}

fn write_actions(actions: &[Action]) -> Result<Vec<u8>, Error> {
    const VERSION: u8 = 8;
    let mut action_data = vec![];
    let mut writer = swf::avm1::write::Writer::new(&mut action_data, VERSION);
    for action in actions {
        writer.write_action(&action)?;
    }
    Ok(action_data)
}
```
