### PR TITLE
avm2: Throw null param error in navigateToURL

### LINKED ISSUE #14733: Buttons redirecting to /null [404 page]
### Describe the bug

There are several games that are working, but, if you press the "Play" button, you will be redirected via _blank to a "/null" page, so the player after pressing the "Play" button will see a 404 Not Found page.

There are multiple games like that, but I added just 4 examples. For each one, after pressing the "Play" button, the bug will occur.

### Expected behavior

Normally, the game should start without redirecting the player to a 404 Not Found page.

### Content Location

- https://www.play-games.com/embed/6551.html
- https://www.play-games.com/embed/25978.html
- https://www.play-games.com/embed/13208.html
- https://www.play-games.com/embed/14265.html

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by n0samu**
Fixes #14733

### CODE REVIEW

File: core/src/avm2/globals/flash/net.rs [hunk 1]
```diff
@@ -29,15 +30,20 @@ pub fn navigate_to_url<'gc>(
...
-    );
-
-    Ok(Value::Undefined)
+    match request.get_public_property("url", activation)? {
+        Value::Null | Value::Undefined => Err(Error::AvmError(type_error(
+            activation,
+            "Error #2007: Parameter url must be non-null.",
+            2007,
+        )?)),
+        other => {
```
Comment (evilpie) [inline core/src/avm2/globals/flash/net.rs:39]:
```suggestion
        url => {
```

**Review by evilpie — APPROVED** [review]

File: core/src/avm2/globals/flash/net.rs [hunk 2]
```diff
@@ -29,15 +30,20 @@ pub fn navigate_to_url<'gc>(
...
-        .coerce_to_string(activation)?;
-
-    activation.context.navigator.navigate_to_url(
-        &url.to_utf8_lossy(),
-        &target.to_utf8_lossy(),
-        None,
-    );
-
-    Ok(Value::Undefined)
+    match request.get_public_property("url", activation)? {
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/flash/net.rs:33]: Have you checked that this errors when calling `navigateToURL` and not when setting the property on `URLRequest`?

File: core/src/avm2/globals/flash/net.rs [hunk 3]
```diff
@@ -29,15 +30,20 @@ pub fn navigate_to_url<'gc>(
...
+        Value::Null | Value::Undefined => Err(Error::AvmError(type_error(
```
Comment (Lord-McSweeney) [inline core/src/avm2/globals/flash/net.rs:34]: It can never be `undefined`, this is a `String` property

File: core/src/avm2/globals/flash/net.rs (hunk 2 above)
Comment (n0samu) [reply core/src/avm2/globals/flash/net.rs:33]: Yes.

**Review by Lord-McSweeney — APPROVED** [review]
