### PR TITLE
core: Fix EditText width and height scaling (close #3001)

### LINKED ISSUE #3001: DefineEditText doesn’t follow alignment
https://www.mejorar-presentaciones.tk/mejorar-presentaciones-loader.swf contains a progress bar which hasn’t centered text:

not-centered

as Flash projector displays it:

centered

The compiler from SWFTools defines an editext which is marked as centered.

I don’t know which information could help to fix this issue.

Many thanks for your help and your excellent work.

### PR DESCRIPTION
**Pull request by hatal175**

### CODE REVIEW

File: core/src/display_object/edit_text.rs [hunk 1]
```diff
@@ -1657,27 +1657,33 @@ impl<'gc> TDisplayObject<'gc> for EditText<'gc> {
     }
 
     fn width(&self) -> f64 {
-        self.0.read().bounds.width().to_pixels()
+        let edit_text = self.0.read();
+        let text_width = edit_text.bounds.width();
+        text_width.to_pixels() * (edit_text.base.transform.matrix.a as f64)
```
Comment (Herschel) [inline core/src/display_object/edit_text.rs:1662]: This needs to transform the bounds by the matrix using something like `BoundingBox::transform`. For example:

```
import flash.geom.Matrix;
var matrix:Matrix = new Matrix();
matrix.c = 1.5; // still affects the width
txt.transform.matrix = matrix;
// Will be something like 2.5 times the original width, because now it is skewed and the width should consider the entire AABB.
trace(txt.width); 
```

File: core/src/display_object/edit_text.rs [hunk 2]
```diff
@@ -1657,27 +1657,33 @@ impl<'gc> TDisplayObject<'gc> for EditText<'gc> {
...
     }
 
     fn set_width(&self, gc_context: MutationContext<'gc, '_>, value: f64) {
         let mut write = self.0.write(gc_context);
+        let scaled_value = value / (write.base.transform.matrix.a as f64);
 
-        write.bounds.set_width(Twips::from_pixels(value));
+        write.bounds.set_width(Twips::from_pixels(scaled_value));
```
Comment (Herschel) [inline core/src/display_object/edit_text.rs:1669]: I think this should change the bounds directly without affecting the matrix; the matrix will transform the bounds additionally during rendering. For example:
```
import flash.geom.Matrix;
trace(txt.width);  // 100
var matrix:Matrix = new Matrix();
matrix.a = 1.5;
txt.transform.matrix = matrix;
trace(txt.transform.matrix); // a = 1.5
trace(txt.width);            // 150
txt.width = 50;	
trace(txt.width);			 // 75	
trace(txt.transform.matrix); // still a = 1.5
// internally the bounds will have width = 50, multiplied 1.5 when rendering
```

**Review by Herschel — CHANGES_REQUESTED** [review]
I believe the width/height getters should calculate the enclosing AABB of the textfield, while the setters only affect the `bounds` directly without considering the matrix.

(TODO for some future PR: This final rendering is affected if device fonts are used vs. embedded outline fonts; glyph fonts will not stretch based on the matrix of the textfield, while outline fonts will. For example, a text field with a=1.5 in the matrix will renders 150% stretched glyphs with an outline font, but unstretched with a glyph font. The bounds of the textfield are always affected by the matrix.)

**Comment by hatal175** [comment]
Just making sure since I mostly copy pasted this, how does this compare with the x and y setter/getter which do make their changes with consideration to the matrix tx,ty transform members?

**Comment by hatal175** [comment]
@Herschel Regarding my question?

**Comment by hatal175** [comment]
Fixed and added unitests.

**Comment by Herschel** [comment]
Sorry for the delay!

> Just making sure since I mostly copy pasted this, how does this compare with the x and y setter/getter which do make their changes with consideration to the matrix tx,ty transform members?

I think this is a difference of expected behavior; a user would expect increasing `textField.width` to make the text field have a bigger area (change the bounds), as oppose to make the rendered glyphs stretch (changing `matrix.a`).

Thank you!

**Review by Herschel — APPROVED** [review]
