### PR TITLE
avm2: Hand out stack slices to Activations instead of accessing a global stack

### LINKED ISSUE #20312: Error on https://www.spiele-umsonst.de/brilliant-crystals-t2785.html
# Error Info
Error name: Error
Error message: panicked at core/src/avm2.rs:740:13:
Native stack underflow
Error stack:
```
Error: panicked at core/src/avm2.rs:740:13:
Native stack underflow
    at imports.wbg.__wbg_new_c68d7209be747379 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/421.js:2824:21)
    at ruffle_web.wasm.js_sys::Error::new::h04fa0d6016be2756 (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[12608]:0x947e78)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hb45a8ba6882ea19c (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[9760]:0x8fd4b4)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h4501cceb7dbe383d (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[6821]:0x864072)
    at ruffle_web.wasm.core::panicking::panic_fmt::h619600efce2da276 (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[10595]:0x91607e)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::hdf63f0aaf1b4ade3 (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[892]:0x237c5)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h8ea21718cc5d4e77 (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[1515]:0x3f971d)
    at ruffle_web.wasm.ruffle_core::avm2::object::class_object::ClassObject::run_class_initializer::h47c907d33e288c2a (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[4663]:0x76fb4f)
    at ruffle_web.wasm.ruffle_core::avm2::object::class_object::ClassObject::from_class::h939956dd46da69dc (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[3839]:0x6e828e)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::hdf63f0aaf1b4ade3 (wasm://wasm/ruffle_web.wasm-030e3f66:wasm-function[892]:0x1d004)
```
AVM2 stack:
```
    at each ::in $cinit()
    at global$init() [TU=each /in ]
    at ninjakiwi.utils::StandardStuff$cinit()
    at global$init() [TU=]
    at Game()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti (0x00001C82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.spiele-umsonst.de/brilliant-crystals-t2785.html#
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/brilliantcrystals.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: 0.1.0 nightly 2025-04-27
Channel: nightly
Built: 2025-04-27T00:07:07.546Z
Commit: 338fad2ec7aac03412ee037ec6329b681cf212c3
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: #000066
isActionScript3: true
uncompressedLength: 6500097

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
This makes `FunctionArgs` easier to use and allows us to skip a pop+push in `op_get_slot`. Stack accesses in general should be faster as the actual stack pointer is stored directly on Activation now (as opposed to behind an `&mut UpdateContext` and `&mut Avm2`).

ChessDemons startup time is reduced ~5% for me and `getslot` is 10% faster. The AVM stack size increase fixes #20312.

TODO:
- [x] Clean up stack code
- [x] Switch from `Lock` to `Cell`?
- [x] Rename `AvmStack` and `AvmStackFrame`?

### CODE REVIEW

File: core/src/avm2/stack.rs [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+        // There should be no values on the value stack when collection is triggered
+        assert!(self.stack_pointer.get() == 0);
+    }
+}
+
+/// A stack frame for a particular method. Despite its name, this stores both
+/// method locals and method stack.
+pub struct StackFrame<'a, 'gc> {
+    data: &'a [Cell<Value<'gc>>],
+    stack_pointer: Cell<usize>,
```
Comment (adrian17) [inline core/src/avm2/stack.rs:96]: I don't think this actually needs to be a Cell. This does require making most of the mutating methods `&mut self`, but tried and it just works. (~~and technically it does remove a small optimization barrier from the optimizer, which could help~~ actually I don't know whether this helps on harms opts; by intuition, removing `Cell` helps, on the other this removes the compiler's knowledge that `data` won't be set to another slice)

File: core/src/avm2/stack.rs [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+}
+
+impl<'a, 'gc> StackFrame<'a, 'gc> {
+    pub fn empty() -> StackFrame<'a, 'gc> {
+        // `Box::new([])` doesn't actually allocate
+        Self {
+            data: Box::leak(Box::new([])),
```
Comment (adrian17) [inline core/src/avm2/stack.rs]: For me it works if I do `&[]` here.

File: core/src/avm2/stack.rs [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+    }
+
+    /// Peek the n-th value from the end of the operand stack.
+    #[inline(always)]
+    pub fn peek(&self, index: usize) -> Value<'gc> {
+        self.data[self.stack_pointer.get() - index - 1].get()
+    }
+
+    #[inline(always)]
+    pub fn stack_top(&self) -> &Cell<Value<'gc>> {
```
Comment (adrian17) [inline core/src/avm2/stack.rs]: You can make this `-> &'a Cell` instead, which removes the need for `.copied()` in `op_get_slot`.

File: core/src/avm2/stack.rs [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+
+        let subslice = &stack_data[stack_pointer.get()..stack_pointer.get() + frame_size];
+
+        stack_pointer.set(stack_pointer.get() + frame_size);
+
+        // Ensure the StackFrame returned to the caller does not have any
+        // old values on it, as these may contain Gc pointers that have already
+        // been collected.
+        for value in subslice {
+            value.set(Value::Undefined);
```
Comment (adrian17) [inline core/src/avm2/stack.rs:69]: Is this a sanity-check memset? We didn't do it before, right?
Bytecode can access not-previously-set values, yes, but we already pre-initialize them in `init_from_method` etc. Why is this needed now?

File: core/src/avm2/stack.rs [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+        }
+
+        StackFrame::for_data(subslice)
+    }
+
+    pub fn dispose_stack_frame(&self, stack_frame: StackFrame<'_, 'gc>) {
```
Comment (adrian17) [inline core/src/avm2/stack.rs:75]: IMO a bit pointless to take it by move if the only place we call this uses `.copied()`. How about either passing a `&`, or if you want it to be super safe then maybe change the `.copied()` into `.take()` that sets the values to empty to prevent accidental reuse?
(but that is additional work after each call for a tiny safety measure so up to you)

**Review by adrian17 — COMMENTED** [review]
It's unfortunate that we need to create the stack frame before running the optimizer instead of just at the start of runtime - to be sure, is there any chance it could be initialized as empty, then the stack frame is obtained and `.stack` is set only in `run_actions()`?

File: core/src/avm2/activation.rs [hunk 6]
```diff
@@ -1672,14 +1665,23 @@ impl<'a, 'gc> Activation<'a, 'gc> {
     }
 
     fn op_get_slot(&mut self, index: u32) -> Result<(), Error<'gc>> {
-        let object = self
-            .pop_stack()
+        // `clone`ing the stack frame is free; it returns a reference to the
+        // original frame.
+        let stack_ref = self.stack.clone();
+        let stack_top = stack_ref.stack_top();
```
Comment (adrian17) [inline core/src/avm2/activation.rs]: BTW, we could do a similar trick for most `coerce_*` and `increment_*` ops, right?
Definitely not as impactful ofc.

File: core/src/avm2/stack.rs (hunk 5 above)
Comment (Lord-McSweeney) [reply core/src/avm2/stack.rs:75]: I changed it to a `take` function, I don't think it'll be much more work, especially since everything is being inlined

**Review by adrian17 — APPROVED** [review]
