### PR TITLE
avm1: Correct `MovieClipLoader` methods

### LINKED ISSUE #917: MovieClipLoader.loadClip/unloadClip should accept a String path
MovieClipLoader.loadClip can also take a String target path:
```
var mcl = new MovieClipLoader();
mcl.loadClip("test.swf", "_root.mc");
```
does not work currently because Ruffle expects an object.

### PR DESCRIPTION
**Pull request by relrelb**
Fixes #917.

### CODE REVIEW

**Review by Herschel — APPROVED** [review]
Thank you!

File: core/src/avm1/globals/movie_clip_loader.rs [hunk 1]
```diff
@@ -42,91 +42,116 @@ pub fn load_clip<'gc>(
...
+                    activation.resolve_target_display_object(start_clip, *target, true)?
+                }
+                Value::Number(level_id) => {
+                    // Levels are rounded down.
+                    // TODO: What happens with negative levels?
+                    Some(activation.resolve_level(*level_id as i32))
+                }
+                Value::Object(object) => object.as_display_object(),
+                _ => None,
+            };
```
Comment (Herschel) [inline core/src/avm1/globals/movie_clip_loader.rs:59]: Maybe extract this logic into a fn since it's used by several of the methods?

Comment (relrelb) [reply core/src/avm1/globals/movie_clip_loader.rs:59]: Unfortunately, they have subtle differences:
* `load_clip` uses `resolve_level`.
* `unload_clip` and `get_progress` use `child_by_depth`
* `get_progress` returns `undefined` for non-DisplayObject objects.

It might be possible, but I doubt how better it will be.

**Review by Herschel — APPROVED** [review]
Thank you!
