### PR TITLE
web: Fixes and improvements in `navigate_to_url`

### LINKED ISSUE #1102: web: unloadMovie("") sometimes reloads the page
Seems to only happen when the P-code source is:
`GetUrl "" ""`

The issue does not happen with Flash (both the projector and the plugin) and on Windows with Ruffle. So nothing happens when unloadMovie("") is called on these targets using the following sample.
[page_reload.zip](https://github.com/ruffle-rs/ruffle/files/5169495/page_reload.zip)

### LINKED ISSUE #2214: web: Navigating to another URL shouldn't upgrade protocol to https
https://www.newgrounds.com/portal/view/73449

On this game, click the "I-Mockery" logo just after the game starts: the browser will display a security warning because i-mockery.com has no https certificate. 

In `\DefineButton2 (1577)\BUTTONCONDACTION`:
`getUrl("http://www.i-mockery.com", "_blank");`

The upgrade happens because `upgradeToHttps` option is enabled and Newgrounds served the file using the https protocol. However, this is something that probably shouldn't happen in this situation. Related to PR  #1930.

And one last important thing: Happy New Year to all the devs and thanks for the great work made over the last year! 🤩

### PR DESCRIPTION
**Pull request by Toad06**
This PR is a bit experimental for me as it implies changes on the Rust side, which is a language I'm absolutely not familiar with. But I feel like I had to give it a try. :) Hope it's not too bad. Here are the changes:

- Fix #1102: `window.location().assign(&window_url);` refreshes the page if the URL is an empty string. To match Flash's behavior (which does nothing in this situation), the PR just checks if `window_url` is all but an empty string. Also, it appears that an URL only containing blank spaces defaults to "./" in Flash, so I've added this special case as well.

- Fix #2214: Upgrading to HTTPS could lead the browser to display a security warning on sites that don't use a certificate, so this PR only enables the upgrade to HTTPS when Ruffle has to deal with forms. Speaking of forms, they didn't send any data because of a little mistake: `<hidden>` elements were created instead of `<input>`.

- Finally, a more reliable way to execute JavaScript code is added. For instance, these wouldn't work currently:

`getURL("javascript:myVar=999");`
In Firefox, the whole page would be replaced by "999".

```
getURL("javascript:myUnloadFunc()");
getURL("page.html");
```
`myUnloadFunc()` wouldn't be executed.

### CODE REVIEW

File: web/src/navigator.rs [hunk 1]
```diff
@@ -43,61 +43,91 @@ impl NavigatorBackend for WebNavigatorBackend {
...
 
-                    form.set_attribute(
-                        "method",
-                        match navmethod {
-                            NavigationMethod::GET => "get",
-                            NavigationMethod::POST => "post",
-                        },
-                    );
+                if target.is_empty() || target == "_self" || target == "undefined" {
+                    let code = url.replacen("javascript:", "", 1);
```
Comment (Herschel) [inline web/src/navigator.rs:59]: Could this be `if let Some(url) = url.trim().strip_prefix("javascript:")`?

File: web/src/navigator.rs [hunk 2]
```diff
@@ -43,61 +43,91 @@ impl NavigatorBackend for WebNavigatorBackend {
...
 
-                    form.set_attribute("action", &url);
+                    let script = document.create_element("script").unwrap();
+                    script.set_inner_html(&code);
 
-                    if let Some(target) = window_spec {
-                        form.set_attribute("target", &target);
+                    let _append = body.append_child(&script);
+                    let _remove = body.remove_child(&script);
```
Comment (Herschel) [inline web/src/navigator.rs:65]: I believe this should only be allowed if `allowScriptAccess` is true. We can pass `allow_script_access` to the NavigatorBackend when we make the player in `lib.rs`.

Also, I think we could move this to a separate `run_script` method (because it will possibly be used elsewhere).

File: web/src/navigator.rs [hunk 3]
```diff
@@ -43,61 +43,91 @@ impl NavigatorBackend for WebNavigatorBackend {
...
+                };
+
+                let form_url = if let Ok(parsed_url) = Url::parse(&url) {
+                    self.pre_process_url(parsed_url).to_string()
+                } else {
+                    url.to_string()
+                };
+
+                //TODO: Should we return a result for failed opens? Does Flash care?
+                #[allow(unused_must_use)]
```
Comment (Herschel) [inline web/src/navigator.rs:83]: Instead of allowing the warning, try: `let _ = foo();` is the Rust way to explicity say "I'm not using this".

**Review by Herschel — CHANGES_REQUESTED** [review]

**Comment by Toad06** [comment]
Thanks for the review. I think I've addressed most of the requested changes.

For `allowScriptAccess`, you're absolutely correct. However, navigation also seems affected depending on the values of the parameters. For instance, with `allowScriptAccess` set to false:

this works:
`getURL("a.html","_blank","GET");`

this doesn't work:
`getURL("a.html","_self","GET");`

I think we could hold off that for a future PR if you don't mind? As I feel like Flash's weirdness requires us to make additional testings... :) I can't promise I'll be able to implement that myself (I will try) but at least I'll open an issue with my observations.

**Comment by Herschel** [comment]
`allowScriptAccess` difference between `"_blank"` and `"_self"` and other small things can be for a future PR, but mainly I'm concerned about `run_script` -- this should definitely check `allowScriptAccess`. Otherwise malicious SWFs could run arbitrary scripts on the page.

**Comment by Toad06** [comment]
Should be good now.
