### PR TITLE
avm1: fix String.substr behaviour for negative lengths

### LINKED ISSUE #3626: String.substr with negative length should work but does not
**Describe the bug**
If you have a ActionScript string named str, str.substr(0, -4) is supposed to be the same as str.substr(0, str.length-4), but in Ruffle, that is not the case. This can cause a number of issues. A description of where I first encountered the bug is #3612, but I closed that issue because it was edited too much so looked strange.

**Expected behavior**
str.substr(0, -4) should have gotten all but the last 4 characters of the string, but instead returned an empty string.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
All versions

**What platform are you using?**
This relates to core functionality so it doesn't matter but Window, Google Chrome

### PR DESCRIPTION
**Pull request by midgleyc**
Fixes #3626.

While not documented, using a negative length in substr treats it as a negative index to some degree. If the first argument is 0, it always does, which I hope is most cases in the wild.

There is some strange behaviour that I've marked in the test and implemented accordingly:
```
// var str = "hello world"
// str.substr(3, -3)

// str.substr(3, -4)
lo worl
// str.substr(3, -5)
lo wor
```
This at least happens in Flash Player 6, which is all I can create.

### CODE REVIEW

File: core/src/avm1/globals/string.rs [hunk 1]
```diff
@@ -439,7 +439,11 @@ fn substr<'gc>(
 
     let len = match args.get(1) {
         None | Some(Value::Undefined) => this_len,
-        Some(n) => string_index(n.coerce_to_i32(activation)?, this_len),
+        Some(n) => string_index_substr(
+            args.get(0).unwrap().coerce_to_i32(activation)?,
```
Comment (Herschel) [inline core/src/avm1/globals/string.rs:443]: Because `coerce_to_i32` can have a side effect (e.g. an object with a `valueOf` function), let's store `args.get(0).coerce_to_i32` in a variable and use it both in the `string_wrapping_index` call and the `string_index_substr` call, instead of recalculating it.

**Review by Herschel — CHANGES_REQUESTED** [review]

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Comment by adrian17** [comment]
FYI, looks like there still is an inconsistency when the strings are too short?

```js
trace("//substr(-3)")
trace("0".substr(-3));
trace("//substr(-0, 3)")
trace("0".substr(0, -3));
```
Flash:
```
//substr(-3)
0
//substr(-0, 3)

```
Ruffle:
```
//substr(-3)

//substr(-0, 3)
0
```
