### PR TITLE
avm2: Use proper scale for `Graphics.beginBitmapFill` (fix #10628)

### LINKED ISSUE #10628: Graphics.beginBitmapFill() is not working for images
### Describe the bug

Despite supposedly being implemented in #10123, Graphics.beginBitmapFill() does not seem to be working, at least for images / image data. [The example from the Adobe documentation](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html#beginBitmapFill()) shows nothing but a blank screen in Ruffle, but it works in Flash Player.

### Expected behavior

The code should display the `image1.jpg` file.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

I found this while investigating why the graphics are messed up in #9535. Here is an example based on the code from that game: [beginBitmapFill.zip](https://github.com/ruffle-rs/ruffle/files/11186672/beginBitmapFill.zip)
The developer's logo should be displayed, but Ruffle again shows nothing but a blank screen.

### PR DESCRIPTION
**Pull request by Herschel**
The scale matrix was incorrectly using the bitmap dimensions when it should be scaled based on twips (x20). Fixes #10628.

FIXME future PR: This code is mostly duplicated between AVM1 and AVM2, would be nice to move the common code somewhere.

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
I can confirm that this fixes the last part of https://github.com/ruffle-rs/ruffle/issues/9735, fixes the preloader graphic on https://github.com/ruffle-rs/ruffle/issues/8543, and completely fixes #9549.

**Comment by n0samu** [comment]
This also fixes #10379 and fixes the graphics in Tilt (#10183) 🎉

**Comment by n0samu** [comment]
And it also fixes the missing ground texture in Earn to Die (#10516)

File: core/src/avm2/globals/flash/display/graphics.rs [hunk 1]
```diff
@@ -72,8 +72,8 @@ pub fn begin_bitmap_fill<'gc>(
             height: bitmap.height() as u16,
         };
         let scale_matrix = Matrix::scale(
-            Fixed16::from_f64(bitmap.width as f64),
-            Fixed16::from_f64(bitmap.height as f64),
+            Fixed16::from_f64(Twips::TWIPS_PER_PIXEL as f64),
```
Comment (relrelb) [inline core/src/avm2/globals/flash/display/graphics.rs:75]: I think this can be just `Twips::TWIPS_PER_PIXEL.into()`, reducing the `i32`-to-`f64` conversion and back.

Comment (Herschel) [reply core/src/avm2/globals/flash/display/graphics.rs]: Thanks! Had to cast `as i16` first.

**Review by Aaron1011 — APPROVED** [review]

**Review by Dinnerbone — APPROVED** [review]
