### PR TITLE
avm2: Remove focus from an EditText when it unloads (close #12092)

### LINKED ISSUE #12092: Homestuck "John: Enter Village" - Softlock after textbox disappears
### Describe the bug

https://mrcheeze.github.io/homestuck-ruffle-tester/#03077 / https://mrcheeze.github.io/homestuck-ruffle-tester/flash/03077.swf

To reproduce:

* Walk north, east, north, east, with WASD or arrow keys to get to this area:
image
* Press Ctrl-Shift-T to open the secret trickster code textbox.
* Type the code shoosh:doof
* As soon as you do, the textbox will instantly disappear (without having to press enter, etc) and you transform into a different character.

The bug is that after the textbox disappears, you are supposed to regain control and be able to move around again. Instead, all keyboard input is completely ignored after it disappears, and you are softlock.

### Expected behavior

As above, but after entering shoosh:doof and turning into a different character, you should be able to move with WASD/arrow keys and attack with space (as you were before).

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Mozilla Firefox

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MrCheeze**
Since https://github.com/ruffle-rs/ruffle/pull/9911 , a textbox that unloads in AVM2 has incorrectly been holding the focus, preventing you from using keyboard input for anything else (see https://github.com/ruffle-rs/ruffle/issues/12092 ).

Since there is no avm2_unload function as such, I copied what [movie_clip](https://github.com/ruffle-rs/ruffle/blob/cd2d01bf6f2565e1aa442da671ca7e27ed186629/core/src/display_object/movie_clip.rs#L2718) and [loader_display](https://github.com/ruffle-rs/ruffle/blob/cd2d01bf6f2565e1aa442da671ca7e27ed186629/core/src/display_object/loader_display.rs#L145) do, of putting the AVM2 "unload-like" logic inside set_parent.

Extra note: I found that:
* parent.removeChild(textfield) removes the focus but does not fire a FOCUS_OUT event
* RemoveObject on the timeline removes the focus *and* fires a FOCUS_OUT event

Which doesn't impact this PR, since FocusEvent isn't implemented at all, but is somewhat surprising....

### CODE REVIEW

File: core/src/display_object/edit_text.rs [hunk 1]
```diff
@@ -1681,6 +1681,21 @@ impl<'gc> TDisplayObject<'gc> for EditText<'gc> {
         self.0.write(context.gc_context).object = Some(to.into());
     }
 
+    fn set_parent(&self, context: &mut UpdateContext<'_, 'gc>, parent: Option<DisplayObject<'gc>>) {
+        let had_parent = self.parent().is_some();
+        self.base_mut(context.gc_context)
+            .set_parent_ignoring_orphan_list(parent);
+        let has_parent = self.parent().is_some();
+
+        if context.is_action_script_3() && had_parent && !has_parent {
```
Comment (Lord-McSweeney) [inline core/src/display_object/edit_text.rs:1690]: `self.movie().is_action_script_3` for mixed AVM

Comment (MrCheeze) [reply core/src/display_object/edit_text.rs]: Updated. That makes the condition here temporarily different from in movie_clip set_parent, but https://github.com/ruffle-rs/ruffle/pull/11005 makes the conditions the same again.

File: core/src/display_object/edit_text.rs [hunk 2]
```diff
@@ -1681,6 +1681,21 @@ impl<'gc> TDisplayObject<'gc> for EditText<'gc> {
         self.0.write(context.gc_context).object = Some(to.into());
     }
 
+    fn set_parent(&self, context: &mut UpdateContext<'_, 'gc>, parent: Option<DisplayObject<'gc>>) {
+        let had_parent = self.parent().is_some();
+        self.base_mut(context.gc_context)
+            .set_parent_ignoring_orphan_list(parent);
+        let has_parent = self.parent().is_some();
```
Comment (Dinnerbone) [inline core/src/display_object/edit_text.rs:1688]: Nit: Is there any scenario where `parent` != `self.parent()` on this line? Save's us a bit of indirection 😅

**Review by Dinnerbone — APPROVED** [review]
