### PR TITLE
avm1: XML sendAndLoad

### LINKED ISSUE #3942: Xml.sendAndLoad not working
Does Ruffle support “Xml.sendAndLoad”?

My code is:
```
var post:XML = new XML();
post.ignoreWhite = true;
var node:XMLNode = post.createElement("root");
post.appendChild(node);

var resp:XML = new XML();
resp.ignoreWhite = true;

var listener:Object = new Object();
listener.load = function(event:Object) {		
	//my_code
}
resp.addEventListener("load", listener);
post.sendAndLoad("rpc/key/", resp);

```
The “rpc/key” must invoke the rpc/key/key.py in the remote server.

This code works successfully in with Adobe Flash Player. I confirm this seeing the syslog message.

When execute my code in Ruffle, the server does not receive the call (in this case, I don’t see any related message in syslog).

### PR DESCRIPTION
**Pull request by midgleyc**
Should fix #3942, progresses on #2986.

Heavily inspired by the corresponding behaviour in LoadVars.

The spec says that `contentType` is used as the `content-type` header; I found it was ignored and `application/x-www-form-urlencoded` used no matter what.

Flash sends particular headers by default; I just left it doing whatever the current implementation does. The XML sent isn't byte-for-byte identical to Flash but I figured that is probably a Ruffle bug.

Examples of a request: request, headers, body

Flash:
```
HTTP 1.1 POST /xml/send_and_load
{
  referer: 'http://localhost:8080/xml/send_and_load',
  'content-type': 'application/x-www-form-urlencoded',
  'content-length': '34',
  'user-agent': 'Shockwave Flash',
  host: 'localhost:8080',
  'cache-control': 'no-cache'
}
<translate text="Hello, world!" />
```

Ruffle:
```
HTTP 1.1 POST /xml/send_and_load
{
  host: 'localhost:8080',
  accept: '*/*',
  'accept-encoding': 'deflate, gzip',
  'user-agent': 'curl/7.75.0-DEV isahc/1.3.0',
  'content-length': '34',
  'content-type': 'application/x-www-form-urlencoded'
}
<translate  text="Hello, world!"/>
```

### CODE REVIEW

File: core/src/avm1/globals/xml.rs [hunk 1]
```diff
@@ -1066,6 +1074,51 @@ pub fn xml_status<'gc>(
...
+            target_clip,
+            fetch,
+        )
+    } else {
+        activation.context.load_manager.load_form_into_load_vars(
+            activation.context.player.clone().unwrap(),
+            loader_object,
+            fetch,
+        )
+    };
```
Comment (Herschel) [inline core/src/avm1/globals/xml.rs:1115]: Is this part left over from LoadVars? I think this should be unreachable, so perhaps the `spawn_xml_fetch` should take a `xml_result: XmlNode` directly.

Comment (Herschel) [reply core/src/avm1/globals/xml.rs:1115]: Ah, I see, you can actually pass a `LoadVars` along here and it receives the data just the same.

**Review by Herschel — APPROVED** [review]
Thank you!
