### PR TITLE
core: Improve spurious key ignoring logic

### LINKED ISSUE #22046: key-up works incorrectly in combination with shift
### Describe the bug

This issue can be seen on https://homestuck.com/002153 .

Start holding W/A/S/D, start holding shift, release wasd, release shift. Alternatively, start holding shift, start holding wasd, release shift, release wasd. Either way, the same bug will happen, the player keeps moving in the held direction.

### Expected behavior

This issue does not happen in flash player, where the player stops moving when you release wasd regardless of shift state.

### Content Location

https://homestuck.com/flashes/actTwo/00253.swf

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Mozilla Firefox 144.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #22046

### CODE REVIEW

**Comment by kjarosh** [comment]
Could you add a test for this specific case from the issue? (Also we need to make sure other tests pass)

File: core/src/input.rs [hunk 1]
```diff
@@ -73,7 +73,10 @@ impl ClickEventData {
 }
 
 pub struct InputManager {
-    key_descriptors_down: HashSet<KeyDescriptor>,
+    /// Tracks which physical keys (identified by physical key + location) are currently pressed.
+    /// This allows us to match key-up events even when the logical key changes
+    /// due to modifier state changes (e.g., shift pressed/released).
```
Comment (kjarosh) [inline core/src/input.rs]: This comment does make sense in the context of this PR, but it doesn't when you just read the doc without this context.

File: core/src/input.rs [hunk 2]
```diff
@@ -157,22 +160,34 @@ impl InputManager {
             }
 
             PlayerEvent::KeyDown { key } => {
-                self.key_descriptors_down.insert(key);
+                // Track the physical key + location, so we can match key-up events
+                // even when the logical key changes due to modifier state changes
+                // (e.g., shift pressed/released).
```
Comment (kjarosh) [inline core/src/input.rs]: I think you can skip this comment in favor of the doc.

File: core/src/input.rs [hunk 3]
```diff
@@ -157,22 +160,34 @@ impl InputManager {
...
                     key_char,
                     key_location,
                 }
             }
             PlayerEvent::KeyUp { key } => {
-                if !self.key_descriptors_down.remove(&key) {
+                // Match key-up events by physical key and location, not the exact
+                // KeyDescriptor. This handles cases where modifier state changes
+                // between key-down and key-up (e.g., shift pressed/released),
+                // which would change the logical key (e.g., 'w' -> 'W').
```
Comment (kjarosh) [inline core/src/input.rs]: This too.

File: tests/tests/swfs/avm2/asymmetric_key_events/output.txt [hunk 4]
```diff
@@ -0,0 +1,8 @@
+keyDown 87 119
```
Comment (kjarosh) [inline tests/tests/swfs/avm2/asymmetric_key_events/output.txt:1]: I'm getting a different `output.txt` from FP, you're missing `textInput` events

Comment (SuchAFuriousDeath) [reply tests/tests/swfs/avm2/asymmetric_key_events/output.txt:1]: Yeah, I forgot to add TextInput events into input.json. Sorry :(

File: tests/framework/src/runner/automation.rs [hunk 5]
```diff
@@ -117,53 +117,149 @@ pub fn perform_automated_event(evt: &AutomatedEvent, player: &mut Player) {
...
+        AutomatedKey::LeftControl => (
+            LogicalKey::Named(NamedKey::Control),
+            PhysicalKey::ControlLeft,
+        ),
+        AutomatedKey::LeftShift => (LogicalKey::Named(NamedKey::Shift), PhysicalKey::ShiftLeft),
+        AutomatedKey::NumLock => (LogicalKey::Named(NamedKey::NumLock), PhysicalKey::NumLock),
+        AutomatedKey::NumpadDelete => (LogicalKey::Named(NamedKey::Delete), PhysicalKey::Delete),
+        AutomatedKey::NumpadDown => (
+            LogicalKey::Named(NamedKey::ArrowDown),
+            PhysicalKey::ArrowDown,
```
Comment (kjarosh) [inline tests/framework/src/runner/automation.rs]: This doesn't look right. Have you consulted the W3C recommendation? https://www.w3.org/TR/uievents-code/#code-value-tables

Comment (SuchAFuriousDeath) [reply tests/framework/src/runner/automation.rs]: Well, I have now :sweat_smile:
