### PR TITLE
audio: Refactor ADPCM decoder

### LINKED ISSUE #5030: integer overflow in ADPCM decoder
**Describe the bug**
In debug builds some ADPCM sounds cause a crash (see the stacktrace below). In production builds the audio output is slightly corrupted with spurious clicking sounds.

It can be reproduced using [the attached SWF file](https://github.com/ruffle-rs/ruffle/files/6957529/swf_file.zip), just play it. The embedded sound file was generated with audacity (white noise, amplitude 0.7) and then exported in Flash as stereo 5-bit 5khz ADPCM.

If you want a more real-life example, the crash can also be triggered in "Garfield's Scary Scavenger Hunt" ([here](https://igrezadecu.com/garfield/igrice/garfield-igrice.html) or in BlueMaxima's Flashpoint). You need to go far left, then forward until you get to the cemetery, then click on the leftmost tombstone.

```
thread 'cpal_wasapi_out' panicked at 'attempt to add with overflow', C:\Users\xenu\Documents\git\ruffle\core\src\backend\audio\decoders\adpcm.rs:84:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\panicking.rs:50
   3: ruffle_core::backend::audio::decoders::adpcm::{{impl}}::SAMPLE_DELTA_CALCULATOR::{{closure}}<std::io::cursor::Cursor<ruffle_desktop::audio::ArcAsRef>>
             at C:\Users\xenu\Documents\git\ruffle\core\src\backend\audio\decoders\adpcm.rs:84
   4: core::ops::function::FnOnce::call_once<closure-3,tuple<i16, i32>>
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\ops\function.rs:227
   5: ruffle_core::backend::audio::decoders::adpcm::AdpcmDecoder<std::io::cursor::Cursor<ruffle_desktop::audio::ArcAsRef>>::next_sample<std::io::cursor::Cursor<ruffle_desktop::audio::ArcAsRef>>
             at C:\Users\xenu\Documents\git\ruffle\core\src\backend\audio\decoders\adpcm.rs:137
   6: ruffle_core::backend::audio::decoders::adpcm::{{impl}}::next<std::io::cursor::Cursor<ruffle_desktop::audio::ArcAsRef>>
             at C:\Users\xenu\Documents\git\ruffle\core\src\backend\audio\decoders\adpcm.rs:183
   7: alloc::boxed::{{impl}}::next<Decoder,alloc::alloc::Global>
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\alloc\src\boxed.rs:1480
   8: dasp_signal::{{impl}}::next<alloc::boxed::Box<Decoder, alloc::alloc::Global>>
             at C:\Users\xenu\.cargo\git\checkouts\dasp-1b669b0877b42fca\f05a703\dasp_signal\src\lib.rs:1591
   9: dasp_signal::interpolate::{{impl}}::next<dasp_signal::FromIterator<alloc::boxed::Box<Decoder, alloc::alloc::Global>>,dasp_interpolate::linear::Linear<[i16; 2]>>
             at C:\Users\xenu\.cargo\git\checkouts\dasp-1b669b0877b42fca\f05a703\dasp_signal\src\interpolate.rs:132
  10: ruffle_desktop::audio::CpalAudioBackend::mix_audio<f32>
             at C:\Users\xenu\Documents\git\ruffle\desktop\src\audio.rs:296
  11: ruffle_desktop::audio::{{impl}}::init::{{closure}}
             at C:\Users\xenu\Documents\git\ruffle\desktop\src\audio.rs:114
  12: cpal::traits::DeviceTrait::build_output_stream::{{closure}}<cpal::platform::platform_impl::Device,f32,closure-1,closure-0>
             at C:\Users\xenu\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.3\src\traits.rs:159
  13: cpal::host::wasapi::stream::process_output
             at C:\Users\xenu\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.3\src\host\wasapi\stream.rs:485
  14: cpal::host::wasapi::stream::run_output
             at C:\Users\xenu\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.3\src\host\wasapi\stream.rs:329
  15: cpal::host::wasapi::stream::{{impl}}::new_output::{{closure}}<closure-0,closure-0>
             at C:\Users\xenu\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.3\src\host\wasapi\stream.rs:136
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by relrelb**

### CODE REVIEW

File: core/src/backend/audio/decoders/adpcm.rs [hunk 1]
```diff
@@ -95,108 +39,81 @@ impl<R: Read> AdpcmDecoder<R> {
...
             bits_per_sample,
             sample_num: 0,
-            left_sample: 0,
-            left_step: 0,
-            left_step_index: 0,
-            right_sample: 0,
-            right_step: 0,
-            right_step_index: 0,
-            decoder: Self::SAMPLE_DELTA_CALCULATOR[bits_per_sample - 2],
+            channels: (0..num_channels)
```
Comment (Herschel) [inline core/src/backend/audio/decoders/adpcm.rs:49]: Could derive `Clone` and `Defualt` for `Channel` and then `vec![Default::default(); num_channels]`

File: core/src/backend/audio/decoders/adpcm.rs [hunk 2]
```diff
@@ -95,108 +39,81 @@ impl<R: Read> AdpcmDecoder<R> {
...
+                    delta += step;
+                }
+
+                step >>= 1;
+
+                k >>= 1;
+                if k == 0 {
+                    break;
+                }
+            }
```
Comment (Herschel) [inline core/src/backend/audio/decoders/adpcm.rs:94]: I think I'd prefer doing either the function pointers or a match here (maybe with a macro to avoid repeated code) -- since this is an inner mixing loop we should care a little bit about making it optimized.

Comment (relrelb) [reply core/src/backend/audio/decoders/adpcm.rs]: Reverted it for now as I'm not too expert in Rust macros. I think we should somehow run benchmarks on this to get maximum performance.

**Comment by midgleyc** [comment]
With the delta calculation back how it was this looks good to me. I like the channel simplification.
