### PR TITLE
AVM2: Implement System.setClipboard

### LINKED ISSUE #8435: Achievement Unlocked 2: Cannot start game
### Describe the bug

In [Achievement Unlocked 2](https://www.newgrounds.com/portal/view/553791/format/flash?emulate=flash), clicking "Free Play" or "Time Trial" on the main menu just goes to a white screen, so the game cannot be started. This error appears in the console:
`Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x2000028 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x19832ac }))) : RustError("Cannot call null or undefined method ::setClipboard of class Class") `

### Expected behavior

The game should start. I think it would even work if the setClipboard method was stubbed out.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 106

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by CUB3D**
Implements [System.setClipboard()](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/System.html#setClipboard())

Fixes #8435

### CODE REVIEW

File: core/src/avm2/globals/flash/system/system.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+use crate::avm2::value::Value;
+use crate::avm2::Error;
+
+/// Implements `flash.system.System.setClipboard` method
+pub fn set_clipboard<'gc>(
+    activation: &mut Activation<'_, 'gc, '_>,
+    _this: Option<Object<'gc>>,
+    args: &[Value<'gc>],
+) -> Result<Value<'gc>, Error<'gc>> {
+    //TODO: in FP9+ this function only works when called from a button handler in the Plugin due to
```
Comment (adrian17) [inline core/src/avm2/globals/flash/system/system.rs:14]: Can you copy this comment to `fn set_clipboard_content` in web? As this will especially matter when clipboard is implemented there

**Comment by Lord-McSweeney** [comment]
An AVM1 version of this would fix #6476.
