### PR TITLE
Chunked Preloading, too

### LINKED ISSUE #7537: https://z0r.de/1703 is not working
### Describe the bug

https://z0r.de/1703 just shows a grey screen.
As per discussion in https://github.com/ruffle-rs/ruffle/issues/720, this loop has been working sometime, but now it's not.
F12 shows nothing
Nightly 2022-07-31

image

### Expected behavior

Sound and visuals, not a still grey screen

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 103.0.5060.134

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kmeisthax**
homestuck preloader but as3

Supercedes and closes #4925. Primary difference is that we no longer use `await background` in async context to separate preload chunks. Instead, the `Player` budgets preloading time itself on every `run_frame`. This ensures that even `tick`-naive frontends will do *some* preloading work.

Frontends that want preloading to run in lockstep with the movie can get the old behavior back by one of two ways:

 * Calling `Player.preload` with no execution limit before `run_frame`. The `exporter` and `scanner` do this on every frame, which is identical to the old loading behavior.
 * Calling `Player.preload` with an already-exhausted execution limit repeatedly until preloading is complete, again before `run_frame`. `tests` does this to generate the worst-case preloading behavior.

Since ProgressEvents in AS3 were implemented since I abandoned the old chunked preloading PR, I've also implemented them here. This fixes #7537 and other movies with broken preloaders that require progress to be reported for more than one frame.

### CODE REVIEW

File: core/src/limits.rs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+                self.current_action_limit = self.max_actions_per_check;
+            }
+        }
+
+        false
+    }
+
+    /// Determine if the execution limit was exhausted without deducting any
+    /// actions.
+    pub fn is_exhausted(&mut self, context: &mut UpdateContext<'_, '_, '_>) -> bool {
```
Comment (Aaron1011) [inline core/src/limits.rs:98]: This doesn't appear to be used anywhere

File: core/src/avm2/object/loaderinfo_object.rs [hunk 2]
```diff
@@ -177,14 +183,29 @@ impl<'gc> LoaderInfoObject<'gc> {
...
-                    "Encountered AVM2 error when broadcasting `complete` event: {}",
-                    e
-                );
+        if !self.0.read().complete_event_fired {
+            // NOTE: We have to check load progress here because this function
+            // is called unconditionally at the end of every frame.
+            let should_complete = match self.0.read().loaded_stream {
+                Some(LoaderStream::Swf(_, root)) => root
+                    .as_movie_clip()
+                    .map(|mc| mc.loaded_bytes() >= mc.total_bytes())
```
Comment (Aaron1011) [inline core/src/avm2/object/loaderinfo_object.rs:194]: Can we ever have a movie where `loaded_bytes` is greater than `total_bytes`?

Comment (kmeisthax) [reply core/src/avm2/object/loaderinfo_object.rs:194]: We shouldn't, this is just paranoia on my part.

File: core/src/limits.rs [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+/// execution limits.
+///
+/// What constitutes an "action" is up to the user of this structure. It may
+/// cover individual interpreter opcodes, bytes decoded in a data stream, or so
+/// on.
+pub struct ExecutionLimit {
+    /// How many actions remain before the next timelimit check.
+    ///
+    /// If `None`, then the execution limit is not enforced.
+    current_action_limit: Option<usize>,
```
Comment (adrian17) [inline core/src/limits.rs:23]: This is not the same as AVM1 actions, right? I saw it was used as equivalent to byte count at some other spot in code. Maybe some other name would be less ambiguous here.

Comment (kmeisthax) [reply core/src/limits.rs:23]: When I originally wrote this code I imagined it handling both the AVM and SWF execution limits, and I didn't call it `bytes` as I felt that would be too concrete. `actions` seemed generic enough to cover both counting AVM instructions and SWF tag bytes.

Of course, the aforementioned refactoring probably won't happen now so `bytes` might be fine.

**Comment by Toad06** [comment]
This looks good based on testing, apart from [this file](https://github.com/ruffle-rs/ruffle/files/9535095/file.zip) that now draws a blank screen with the following errors:

```
Tried to instantiate non-registered character ID 358
Unable to instantiate display node id 358, reason being: Character id doesn't exist
Tried to instantiate non-registered character ID 359
Unable to instantiate display node id 359, reason being: Character id doesn't exist
```

On Web, it's possible to bypass the issue by clicking Play/Rewind/Forward in the context menu.

**Comment by kmeisthax** [comment]
@Toad06 The movie's preloader is the following code:

```
ifFrameLoaded(7)
{
   gotoAndStop(8);
}
r = this.getBytesLoaded() / this.getBytesTotal();
barre._width = r * 380;
```

This *seems* broken on first glance, but it's more likely just something in Flash we don't implement yet. I'm assuming that it's reasonable in Flash to park the playhead on an unloaded frame and have the tags run as they download.

I could work around this by making `ifFrameLoaded` check the frame *after* the request, but it probably won't work for all movies.

File: core/src/limits.rs (hunk 3 above)
Comment (kmeisthax) [reply core/src/limits.rs]: I'm renaming 'actions' to 'operations' here to remove the ambiguity

**Review by Herschel — COMMENTED** [review]
My initial instinct is that `PreloadProgress` feels like it would be better as part of `SwfMovie` or the `Loader` itself instead of `MovieClipStatic`, as its really only root SWFs are in charge of preloading:
 * `DefineX` definitions tags can only exist at the top SWF level, and not nested within child `DefineSprite` tags.
   * (We don't enforce this currently, but this seems like a decent time to start considering it).
 * This means we don't have to worry about arbitrary recursion, there's really only one level (the root SWF and its children definition tags).
 * Similarly, `_framesloaded` for a non-root clip will always be observed as `_totalframes`.
 * So it seems a bit wasteful to store these `PreloadProgress` values for every clip.

I agree that ExecutionLimits seems slightly over-complicated for the task at hand. I can see the idea of using it for AVM ScriptLimits as well, but I'd somewhat prefer keeping it simple first. Simply using the `time_limit` and checking the duration after every SWF definition tag should be fine, without the `max_ops_per_check` part -- it's not performance critical like AVM bytecodes, and the number of bytes doesn't necessarily correlate to the amount of processing anyway (for example, a `DefineSound` tag can be lots of megabytes, but is simply passing a slice to the audio backend, while a `DefineShape` tag can be relatively small but may go through the tessellation process).

Otherwise this seems great, thank you! I don't feel too strongly about the above, and I'm AFK this weekend so am not able to test this deeply, so please feel free to merge if you feel its okay.

**Comment by Herschel** [comment]
> I'm assuming that it's reasonable in Flash to park the playhead on an unloaded frame and have the tags run as they download.

You can never go to a frame that's not loaded yet, instead the playhead will go to the farthest loaded frame (and continue playing from that frame as normal, as tags download). So if the farthest frame loaded is 7, `gotoAndStop(8)` would actually stop on frame 7 IIRC (Not able to test ATM, so take with a grain of salt!)

File: tests/tests/swfs/avm2/loader_loadbytes_events/.project [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+	</projects>
+	<buildSpec>
+		<buildCommand>
+			<name>com.adobe.flexbuilder.project.flexbuilder</name>
+			<arguments>
+			</arguments>
+		</buildCommand>
+	</buildSpec>
+	<natures>
+		<nature>com.adobe.flexbuilder.project.actionscriptnature</nature>
```
[the remark this answers is not in the document]
Comment (kmeisthax) [reply tests/tests/swfs/avm2/loader_loadbytes_events/.project:15]: This is what I get for building the test in Flash Builder instead of figuring out how to install the Flex SDK on Windows

**Comment by kmeisthax** [comment]
Ok, it looks like there were a few things that weren't implemented:

 * I forgot to change `clamped_frame` to clamp based on `frames_loaded`. That's been fixed.
 * `ActionWaitForFrame` and `ActionWaitForFrame2` weren't actually implemented. I made it check the target clip's frame count under the assumption that it respects `tellTarget`.

@Toad06 I wasn't able to actually validate the behavior of the movie you tested beyond its initial preloader, it appears to try to do something with `LoadVars` and then errors out.

**Comment by Toad06** [comment]
> @Toad06 I wasn't able to actually validate the behavior of the movie you tested beyond its initial preloader, it appears to try to do something with `LoadVars` and then errors out.

Thanks for checking! In fact, it's not possible to go beyond the title screen in master as well, this is the reason why I haven't attached the other files - but I should have mentioned that, sorry. The issue is that the file loads data from a php file (this part works) and an external image as a background (this part works too)... but `getBytesTotal` and `getBytesLoaded` currently always return 0 for external images, so the game thinks the image is still loading and the level never starts. #6552 is the bug report I made.

By the way, I tried the PR again and noticed some fixes or improvements in z0r loops: 👍
- [2021](https://z0r.de/L/z0r-de_2021.swf) (issue 2435 - now works on web and desktop).
- [916](https://z0r.de/L/z0r-de_916.swf) (mentioned in issues 6144 and 7525 - works on web but issue persists on desktop)
- [1115](https://z0r.de/L/z0r-de_1115.swf) (issue 6144 - randomly works on web but issue persists on desktop).

**Comment by kmeisthax** [comment]
Alright, I'm going to prep this PR to merge in, then.
