### PR TITLE
avm2: Ignore errors when setting properties in amf deserializer

### LINKED ISSUE #16718: Dragon Age Journey - Freeze after tutorial, upon first Loading screen for new area.
### Describe the bug

In Dragon Age Journey, the game works up until you complete the tutorial and advance to a new area, at which point you get a "Loading.." screen that doesn't progress.

Console output:

ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xa29d8d8 }) to handler FunctionObject(FunctionObject { ptr: 0x1148c348, name: Ok("packages.gui::LoadingScreen/onFrame()") }) : ReferenceError: Error #1056: Cannot create property map_family on packages.file.FMapData.

### Expected behavior

Expected to advance to the next area.

### Content Location

https://www.newgrounds.com/portal/view/592371/format/flash?emulate=flash

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome Version 119.0.6045.160 (Official Build) (64-bit)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Aaron1011**
Flash Player *traces* any errors that occur during setting properties on the newly-constructed object durting AMf deserialization, and continues deserializing.

Fixes #16718

### CODE REVIEW

File: core/src/avm2/amf.rs [hunk 1]
```diff
@@ -340,11 +340,23 @@ pub fn deserialize_value<'gc>(
...
-                obj.set_public_property(
+                // Flash player logs the error and continues deserializing the rest of the object,
+                // even when calling a customer setter
+                if let Err(e) = obj.set_public_property(
                     AvmString::new_utf8(activation.context.gc_context, entry.name()),
                     value,
                     activation,
-                )?;
+                ) {
+                    tracing::warn!("Ignoring error deserializing AMF property: {e:?}");
```
Comment (evilpie) [inline core/src/avm2/amf.rs:350]: Can we include the property name here?

**Review by evilpie — APPROVED** [review]
