### PR TITLE
avm2: Make use of handle_input_multiname in xml_descendants

### LINKED ISSUE #19237: Xenon Prime Racing: Can't start
### Describe the bug

Game works up to the screen where you pick your ship, pressing the play button does nothing.

### Expected behavior

Game should be playable

### Content Location

https://www.newgrounds.com/portal/view/471190?emulate=flash

### Affected platform

Browser's extension

### Operating system

Android 14

### Browser

Chrome 131

### Additional information

_No response_

### LINKED ISSUE #19895: abowman dog isn't working
### Describe the bug

Image

### Expected behavior

Image

### Content Location

https://test.abowman.com/widgets/dog/dog.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #19895
Fixes #19237

The .fla is removed because it's not what the swf is made from anymore, now it's from the .as file.

### CODE REVIEW

File: core/src/avm2/object/xml_object.rs [hunk 1]
```diff
@@ -688,7 +690,7 @@ impl<'gc> TObject<'gc> for XmlObject<'gc> {
     }
 }
 
-fn handle_input_multiname<'gc>(
+pub(super) fn handle_input_multiname<'gc>(
```
Comment (evilpie) [inline core/src/avm2/object/xml_object.rs]: Move this to e4x.rs

File: core/src/avm2/e4x.rs [hunk 2]
```diff
@@ -42,6 +43,50 @@ pub fn namespace_for_multiname<'gc>(
...
+    // Special case to handle code like: xml["@attr"]
+    // FIXME: Figure out the exact semantics.
+    // NOTE: It is very important the code within the if-statement is not run
+    // when the passed name has the Any namespace. Otherwise, we run the risk of
+    // creating a NamespaceSet::Multiple with an Any namespace in it.
+    if !name.has_explicit_namespace()
+        && !name.is_attribute()
+        && !name.is_any_name()
+        && !name.is_any_namespace()
+        && let Some(mut new_name) = name
```
Comment (SuchAFuriousDeath) [inline core/src/avm2/e4x.rs:59]: One additional tiny change: I added the let Some from the if body into the outer if, it is equivalent.
