### PR TITLE
avm1: Correct some properties in SWFv4

### LINKED ISSUE #7787: avm1: `_xscale` behaves differently in SWFv4
In _Houdini: The Vampire's Crypt_, the character doesn't face the correct direction when going to the left or right.

Steps to reproduce:
- [Open or download the game here.](https://s1.oyuncubey.com/swf/Houdinivampirekarsi.swf)
- Click "Clic to continue", "Skip" and "Play".
- Press the left, right, up and down arrows (in this order), and repeat this step a second time to free the character.
- Press the left and right arrows to notice the issue.

---

To flip the sprite, the game always uses `../Hood:_xscale = "-40";`. So this value is hardcoded and depends on a SWFv4 specific behavior: when the `_xscale` (or `_yscale`) property is set with a negative value, it is applied and then turned into a positive number.

[Here is a sample](https://github.com/ruffle-rs/ruffle/files/9440253/sample.zip) that reproduces the issue. Click on the text to see that the file behaves differently whether the SWF version is 4 or 5.

### PR DESCRIPTION
**Pull request by Toad06**
This PR changes the following properties in SWFv4:

- `_xscale` and `_yscale`: The behavior is different with negative values (see #7787). Values are also stored differently (for instance a value of -40 will return 39.9993896484375).

- `_droptarget`: When there is no clip, this property returns `undefined` rather than an empty string (also affects SWFv5).

- `_rotation`: This property stores its value differently but this unfortunately doesn't match Flash currently (a value of -40 should return -39.999755859375). I will need help here.

I will update [the existing getproperty_swf4 test](https://github.com/ruffle-rs/ruffle/tree/master/tests/tests/swfs/avm1/getproperty_swf4) with [this new one](https://github.com/ruffle-rs/ruffle/files/9440369/test_update.zip) but this requires `_rotation` to return precise values.

Fixes #7787.

### CODE REVIEW

File: core/src/avm1/object/stage_object.rs [hunk 1]
```diff
@@ -801,6 +828,10 @@ fn set_rotation<'gc>(
         } else if degrees > 180.0 {
             degrees -= 360.0
         }
+        if activation.swf_version() < 5 {
+            // TODO: We don't exactly match Flash here.
```
Comment (kmeisthax) [inline core/src/avm1/object/stage_object.rs:832]: In what way? Is it just floating point rounding or something more significant?

**Comment by Herschel** [comment]
My first instinct is that this involves the scale-rotation caching in some way (maybe SWF4 doesn't do this?) but I'll have to investigate a bit more!

**Comment by Herschel** [comment]
Yes, looks like SWFv4 didn't cache the scaling/rotation when you set it -- basically the `SCALE_ROTATION_CACHED` flag shouldn't be set in `DisplayObject::cache_scale_rotation`.

This causes the scale to be recalculated each time its accessed, and because this involves a sqrt it will return a positive value naturally (try flipping a clip horizontally in the Flash IDE and printing it's `_xscale`).

But good catch on the values being clamped to `Fixed16`! I think this should actually be done inside the `set_scale_x` etc., because this also needs to happen for AS3:
```
clip.scaleX = 0.0000152587890625; // 1 / 65536
trace(clip.transform.matrix);
clip.scaleX = 0.0000152587890624; // rounds down to 0
trace(clip.transform.matrix);
```

File: core/src/avm1/object/stage_object.rs [hunk 2]
```diff
@@ -681,15 +685,28 @@ fn set_x_scale<'gc>(
...
+        let val = if activation.swf_version() < 5 {
+            let v = if this.scale_x(activation.context.gc_context).into_fraction() < 0.0 {
+                -val
+            } else {
+                val
+            };
+            (Fixed16::from_f64(v / 100.0).to_f64()) * 100.0
+        } else {
+            val
+        };
```
Comment (Herschel) [inline core/src/avm1/object/stage_object.rs:697]: The behavior shouldn't change based on positive or negative -- instead, SWFv4 does not cache the value after its set `DisplayObjectFlags::SCALE_ROTATION_CACHED`. It will naturally return positive once its calculated again.

The clamping to `Fixed16` part should happen all the time, even in SWFv5+. So that part should probably move to `DisplayObject::set_scale_x`.

For example:
```
clip._xscale = 0.00152587890625; // 100/65536
trace(clip.transform.matrix);
clip._xscale = 0.00152587890624; // <100/65536, clamps to 0
trace(clip.transform.matrix);
```

**Comment by Toad06** [comment]
Sorry for the late reply. This is because I'm having some difficulties at implementing the requested changes.

https://github.com/ruffle-rs/ruffle/blob/3b752cc600297c101ce6abd768614c258e28317c/core/src/display_object.rs#L251
I suppose that we just need to check if the SWF version is >= 5 here. I tried to use `self.parent().swf_version()` but this didn't work when testing my sample ([here](https://github.com/ruffle-rs/ruffle/files/9440369/test_update.zip)) as it was returning the version of the player (32). Of course, passing the SWF version using the function parameters would work, but I feel like we don't want to do this.

---

About the clamping to `Fixed16`, I'm not getting the same result in SWFv5+ and ActionScript 3 when testing in JPEXS.

```
/:_xscale = 0.0000152587890624;
trace(/:_xscale);
```

SWFv4: 0 (unless the previous value was 0.00152587890625 - in this case it won't change)
SWFv5+: 0.00152587890624


```
this.scaleX = 0.0000152587890624;
trace(this.scaleX);
```

AS3: 0.0000152587890624


So it seems like I'm missing something again (unless the Flash IDE does some rounding/claming when compiling the SWF file?).

Here are [the files](https://github.com/ruffle-rs/ruffle/files/9483488/t_files.zip) I used.

**Comment by Herschel** [comment]
> Of course, passing the SWF version using the function parameters would work, but I feel like we don't want to do this.

I think we could change the params to `scale_x()` and `set_scale_x()` from `gc_context` to `context: &mut UpdateContext<'_, 'gc, '_>`, and then it can get `context.swf_version`. I'll think a little bit more about this!

> About the clamping to `Fixed16`, I'm not getting the same result in SWFv5+ and ActionScript 3 when testing in JPEXS.
> 
> ```
> /:_xscale = 0.00152587890624;
> trace(/:_xscale);
> ```
> 
> SWFv4: 0 (unless the previous value was 0.00152587890625 - in this case it won't change) SWFv5+: 0.00152587890624
> 
> ```
> this.scaleX = 0.0000152587890624;
> trace(this.scaleX);
> ```
> 
> AS3: 0.0000152587890624

Try looking directly at matrix.a values (SWF8+):
```
scaleX = 0.0000152587890625; // ==1/65536
trace(scaleX); // 0.0000152587890625
trace(transform.matrix); // a = 0.0000152587890625

scaleX = 0.0000152587890624; // < 1/65536
trace(scaleX); // 0.0000152587890624
trace(transform.matrix); // a = 0!
```

`matrix.a` is the actual internal scale value used for rendering, and these matrix values are what get clamped to Fixed16. But the `scaleX` still stores the original value that the user passed. This is the reason for the "scale cached" flag -- so that when the user does `_xscale = -100; trace(_xscale);`, they get the same -100 value back like they expect. Without this flag, when the user does `trace(_xscale);`, the scale gets recalculated from the matrix and they get a positive value.

**Comment by Herschel** [comment]
Oops, I realized `context.swf_version()` doesn't exist (it's on `activation` :-) )

Still trying to decide the best way to do this -- the simplest/cheesiest way might be adding something like:
`if activation.swf_version() <= 4 {
    this.clear_scale_rotation_cached();
}`  in `avm1::object::stage_object::scale_x`, `set_scale_x` etc. that clears the flag.

Let's limit this PR to that flag and keep the `Fixed16` for another PR, to keep things simple.

**Comment by Toad06** [comment]
Thank you for the explanations! I've updated the PR with something I tried yesterday (so before I read your last comment 😄 - but this only focuses on the flag and skips the `Fixed16` stuff).

**Comment by kmeisthax** [comment]
I read through the PR and the prior comments, but I'm not 100% sure if everything was resolved or not. @Toad06 is it OK to rebase and merge this?

**Comment by Toad06** [comment]
Thanks for reviving this PR. 😉

Yes, this is resolved: the `SCALE_ROTATION_CACHED` flag is no longer set for SWFv4.

However there were discussions about the  way to implement it: Mike suggested two possible implementations and I chose... the third one (see the two comments on September 6th). Does this implementation look correct to you?

**Comment by kmeisthax** [comment]
With the way you implemented it, all the properties calculate & cache normally; but on SWFv4 the cached flag is never set and thus they are always recalculated each time. This looks like it'll work, and it keeps a bit of complexity out of the basic parameter setters and getters. I'm going to merge what we have.
