### PR TITLE
avm2: Implement FLV Date to Avm2Value conversion

### LINKED ISSUE #16535: cant get a looksie at the reel plz help :[ http://www.stephaniemccrea.com/movs'/player.swf
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/flv.rs:67:17:
not implemented: FLV data to AVM2 data conversion unimplemented for Date { unix_time: 1216835036000.0, local_offset: -26370 }
Error stack:
```
Error: panicked at core/src/avm2/flv.rs:67:17:
not implemented: FLV data to AVM2 data conversion unimplemented for Date { unix_time: 1216835036000.0, local_offset: -26370 }
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/69.js:3399:21)
    at ruffle_web.wasm.js_sys::Error::new::h2234a378a3d95323 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[14081]:0xb180a9)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h14ffa3c2df79f491 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[11616]:0xac3a54)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[7050]:0x98229b)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[11319]:0xabbea9)
    at ruffle_web.wasm.<flv_rs::script::Value as ruffle_core::avm2::flv::FlvValueAvm2Ext>::to_avm2_value::h35eb282a05a929a2 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[6736]:0x96c0cc)
    at ruffle_web.wasm.<flv_rs::script::Value as ruffle_core::avm2::flv::FlvValueAvm2Ext>::to_avm2_value::h35eb282a05a929a2 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[6736]:0x96c68c)
    at ruffle_web.wasm.ruffle_core::player::Player::tick::h96bd2b253605d2a5 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[948]:0x28c7a0)
    at ruffle_web.wasm.ruffle_web::Ruffle::tick::h7606edafba7cafba (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[1136]:0x36d454)
    at ruffle_web.wasm.ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hec07d541e0b2af75 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[13995]:0xb1789e)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon RX 580 Series (0x000067DF) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/player.html#http://www.stephaniemccrea.com/movs'/player.swf?file=http%3A%2F%2Fwww.stephaniemccrea.com%2Fmovs%27%2Fdemoreelmp4_480.flv&skin=http%3A%2F%2Fwww.stephaniemccrea.com%2Fmovs%27%2Fsnel.swf&controlbar=over
SWF URL: http://www.stephaniemccrea.com/movs'/player.swf?file=http%3A%2F%2Fwww.stephaniemccrea.com%2Fmovs%27%2Fdemoreelmp4_480.flv&skin=http%3A%2F%2Fwww.stephaniemccrea.com%2Fmovs%27%2Fsnel.swf&controlbar=over

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-12
Channel: nightly
Built: 2024-05-12T00:05:54.705Z
Commit: 3d412c955ff2a84f02de7ef17be9eba70f3da5d2
Is extension: true

# Metadata
width: 400
height: 300
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 80780

### PR DESCRIPTION
**Pull request by evilpie**
Fixes #16535

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]

File: core/src/avm2/flv.rs [hunk 1]
```diff
@@ -45,6 +48,18 @@ fn avm2_array_from_flv_values<'gc>(
         .into()
 }
 
+fn avm2_date_from_flv_date<'gc>(
+    activation: &mut Activation<'_, 'gc>,
+    unix_time: f64,
+    _local_offset: i16,
```
Comment (adrian17) [inline core/src/avm2/flv.rs:54]: is `_local_offset` actually supposed to be ignored? If not, can you add a TODO or a stub warning?

Comment (evilpie) [reply core/src/avm2/flv.rs:54]: The DateObject only stores the datetime in UTC. The AVM1 implementation also seems to ignore it
