### PR TITLE
core: Store correct data for loaded images

### LINKED ISSUE #6552: avm1: `getBytesTotal` and `getBytesLoaded` incorrectly return 0 for images
Some files are using `getBytesTotal` and `getBytesLoaded` to detect if an image is loaded and then continue the execution. As both of these methods return 0 for images, the affected files softlock.

---

[Sample](https://github.com/ruffle-rs/ruffle/files/8362420/sample.zip)

```
// Frame 1:
_root.createEmptyMovieClip("water",2);
_root.water.loadMovie("water.jpg");

// Release button:
trace("getBytesTotal(): " + _root.water.getBytesTotal());
trace("getBytesLoaded(): " + _root.water.getBytesLoaded());
var loaded = _root.water.getBytesLoaded() / _root.water.getBytesTotal();
if(loaded >= 1 && _root.water.getBytesLoaded() > 0) {
   trace("LOADED!");
}
```

Flash Player traces:

> getBytesTotal(): 29665
> getBytesLoaded(): 29665
> LOADED!

Ruffle traces:

> getBytesTotal(): 0
> getBytesLoaded(): 0

### LINKED ISSUE #6616: Image loading progress animation fails on Graffiti Archaeology.
### Describe the bug

Hi all!  I'm trying to revive an old Flash project called Graffiti Archaeology (http://grafarc.org/flash/view.htm). We developed this in 2002, so I believe it's ActionScript 1.  The app shows a series of layers of high-res photos, clipped by vector outline shapes, in a time-lapse photomontage, with various UI controls to allow you to move around in space and time.

The bug: In the original Flash, there was animation that would show the progress as each layer was being downloaded, and the image and its corresponding UI elements would appear once loading was complete. In Ruffle, that doesn't happen.

In the ActionScript, we use `img.getBytesLoaded()` and `img.GetBytesTotal()` to calculate how much of each image has been loaded, and the images themselves are only revealed once BytesLoaded == BytesTotal.  I'm told those methods are not yet implemented in Ruffle, so I'm guessing that explains this bug.

### Expected behavior

Here's a video showing how the UI behaved in Flash: https://vimeo.com/695549918/744a0c6baa

Specifically:
(1) The little rhombuses in the timeline at bottom are buttons you can click on. (In Ruffle, they don't show up.) 
(2) The layers of photos all appear with a top-to-bottom grey fill effect, which behaves like a visual progress bar as the data gets downloaded. Once downloaded, the image appears. (In Ruffle, none of that happens.)

### Affected platform

Browser's extension

### Operating system

Mac OS 10.14.6 Mojave 

### Browser

Google Chrome 97

### Additional information

See also this related issue: https://github.com/ruffle-rs/ruffle/issues/6552

### LINKED ISSUE #9702: kuschnick.com: Images are not displayed
### Describe the bug

hubi

# Bug Report
Images (marked red in the screenshot) are not displayed.

# Bug Report
Images (marked red in the screenshot) are not displayed.

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 2560, height: 1297, depth_or_array_layers: 1 }
Player type: Object
SWF URL: gallery.swf
Param movie: gallery.swf
Param bgcolor: #000000
Param wmode: transparent
Param allowscriptaccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kuschnick.com/
SWF URL: https://kuschnick.com/gallery.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-24
Channel: nightly
Built: 2023-02-24T00:23:51.606Z
Commit: 5a7cd92bfed181aecb90f8bb631b8bbf5506d86f
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 40
numFrames: 37
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 150229

### Expected behavior

Images should be displayed

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Chrome

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Toad06**
Fixes #6552: `getBytesLoaded()` and `getBytesTotal()` now return correct values.

`getSWFVersion()` (implemented as part of this PR) and the `_url` property are also fixed.

Here's [a sample](https://github.com/ruffle-rs/ruffle/files/11009480/water.zip).

Other related issues:
Fixes #6616
Fixes #9702

### CODE REVIEW

**Review by Herschel — COMMENTED** [review]
Could we add a test for this? Thank you!

File: swf/src/types.rs [hunk 1]
```diff
@@ -110,6 +120,16 @@ impl HeaderExt {
         }
     }
 
+    /// Returns the header for a loaded image (JPEG, GIF or PNG).
+    pub fn default_with_uncompressed_len(length: u32) -> Self {
+        Self {
+            header: Header::default_for_loaded_image(),
```
Comment (Herschel) [inline swf/src/types.rs:126]: Small nit, but I think I'd prefer to construct `Header` directly here instead of adding `Header::default_for_loaded_image`, just to avoid adding another function to the public API (`swf` is the one crate we publish onto crates.io, so it's better to avoid Ruffle-specific stuff in there when possible).

Comment (Toad06) [reply swf/src/types.rs]: Makes sense! I did this change and also added a test.

**Review by Herschel — APPROVED** [review]
Thank you!

**Review by Dinnerbone — APPROVED** [review]

**Comment by otherthings** [comment]
This is so exciting to see!  How might I go about testing this fix?  (Should I just wait for the nightly build, i.e. try it tomorrow?)

**Comment by otherthings** [comment]
I just tested it, and it's working perfectly now!  Thank you so much for this fix!
