### PR TITLE
core: Support mixed AVM

### LINKED ISSUE #8941: fireboynwatergirl.com#
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018f1a9e:wasm-function[1098]:0x2a6c57)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f1a9e:wasm-function[1410]:0x3179d1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018f1a9e:wasm-function[5024]:0x4b2a83)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f1a9e:wasm-function[3750]:0x46e9f9)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f1a9e:wasm-function[5266]:0x4b78ce)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hc67b923d49e8c0d9 (wasm://wasm/018f1a9e:wasm-function[1765]:0x37297b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3cd7d535cbeb2028 (wasm://wasm/018f1a9e:wasm-function[484]:0x1762b5)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf9486ca25cc8f28c (wasm://wasm/018f1a9e:wasm-function[1332]:0x3038ed)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::hc56801695f86fd9f (wasm://wasm/018f1a9e:wasm-function[404]:0x11b51e)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.fireboynwatergirl.com/?p=game&id=310
SWF URL: https://www.fireboynwatergirl.com/swf/fireboy-racing.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-25
Channel: nightly
Built: 2022-12-25T00:15:38.799Z
Commit: 6dc628e49f7a1de9115a68eb99f0b8ce2e1f14a8
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: #003A5C
isActionScript3: true
uncompressedLength: 985404

### LINKED ISSUE #9330: Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bcc051e635a9e70a739a.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h7e6b96cea392c96b (wasm://wasm/027a46de:wasm-function[1590]:0x415453)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/027a46de:wasm-function[1995]:0x4a9f65)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd937bf3f89ff4f2e (wasm://wasm/027a46de:wasm-function[7150]:0x760542)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/027a46de:wasm-function[5077]:0x6bcf17)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/027a46de:wasm-function[7474]:0x76f008)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h2df5a1d0d3c08182 (wasm://wasm/027a46de:wasm-function[3504]:0x61ae23)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hb8c19b7e9235b97b (wasm://wasm/027a46de:wasm-function[2718]:0x5784e3)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd6643c768c414aa5 (wasm://wasm/027a46de:wasm-function[720]:0x2668f5)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h91a1ff81f06db07a (wasm://wasm/027a46de:wasm-function[1543]:0x407881)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1674747793%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F455000%2F455972_FINAL.swf%3F1258558009%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2221404455.4d1b88aa725d367d9e38e82befa7790f4189ac46093605%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263d527b4d6db9%22%2C%22NewgroundsAPI_SessionID%22%3A%22khI0aNLKhNB9vghVjNkZ1d07d6a8440480f7e8db8c23e9a21fa67d204134Yi6J%22%2C%22NewgroundsAPI_UserName%22%3A%22MohinathAnimations%22%2C%22NewgroundsAPI_UserID%22%3A7838139%2C%22ng_username%22%3A%22MohinathAnimations%22%7D%2C%22width%22%3A700%2C%22height%22%3A500%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F455000%2Fflash_455972.png%3Ff1364572399%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/455000/455972_FINAL.swf?1258558009

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.131.4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-26
Channel: nightly
Built: 2023-01-26T00:19:01.046Z
Commit: 56fd9adbf91c01440fae7dc1d2024aa297938b43
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2981191

### LINKED ISSUE #9437: Error on https://www.gameflare.com/embed/monkey-go-happy-mini-monkeys-3/
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.gameflare.com/emulators/ruffle/core.ruffle.2796ca293e6c92590943.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027c294e:wasm-function[1925]:0x4855e1)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027c294e:wasm-function[1857]:0x4758ab)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027c294e:wasm-function[7197]:0x769895)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027c294e:wasm-function[5104]:0x6c4a1f)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027c294e:wasm-function[7502]:0x7783f5)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::ha4a007830dee0088 (wasm://wasm/027c294e:wasm-function[3507]:0x61f1de)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h2852286861940ffb (wasm://wasm/027c294e:wasm-function[2708]:0x579fee)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3410c452b43fa93d (wasm://wasm/027c294e:wasm-function[729]:0x244a11)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf4339ba2de2ec1f6 (wasm://wasm/027c294e:wasm-function[1233]:0x365bcf)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/monkey-go-happy-mini-monkeys-3/
SWF URL: https://data.gameflare.com/games/3306/v6tsAwN4L7UeHF.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SM-X200) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-30
Channel: nightly
Built: 2023-01-30T00:19:04.244Z
Commit: 15c7b6520b525a67f5224855ec7e49eb0604aa07
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 47
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 4515078

### LINKED ISSUE #9666: Error on https://www.y8.com/games/feeding_frenzy_tuna
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0281efe2:wasm-function[1952]:0x4ae0c8)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0281efe2:wasm-function[1887]:0x49d0e1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0281efe2:wasm-function[7288]:0x779c54)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0281efe2:wasm-function[5177]:0x6d4322)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0281efe2:wasm-function[7597]:0x78899a)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h018b8055f2ca652f (wasm://wasm/0281efe2:wasm-function[3586]:0x62d202)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h619429c22793f41b (wasm://wasm/0281efe2:wasm-function[2744]:0x582f76)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h12667dcd5bc2c65d (wasm://wasm/0281efe2:wasm-function[721]:0x25d90c)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb3f7be01839936e4 (wasm://wasm/0281efe2:wasm-function[1463]:0x3e262f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.y8.com/games/feeding_frenzy_tuna
SWF URL: https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/93743/original/tuna_growing.swf?1522719061

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-20
Channel: nightly
Built: 2023-02-20T00:19:50.499Z
Commit: f7a12698b9a5dbfc39529ab5e4abd75880579b99
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1875930

### LINKED ISSUE #9724: Error on http://fancyplanet.org/game/tank-destroyer
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0283308a:wasm-function[1957]:0x4af4c6)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0283308a:wasm-function[1894]:0x49f690)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0283308a:wasm-function[7286]:0x77a6d9)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0283308a:wasm-function[5176]:0x6d48cf)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0283308a:wasm-function[7599]:0x78953b)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h018b8055f2ca652f (wasm://wasm/0283308a:wasm-function[3597]:0x62fded)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h619429c22793f41b (wasm://wasm/0283308a:wasm-function[2752]:0x5850f0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h12667dcd5bc2c65d (wasm://wasm/0283308a:wasm-function[722]:0x25be4a)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb3f7be01839936e4 (wasm://wasm/0283308a:wasm-function[1467]:0x3e590b)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /games/39.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: http://fancyplanet.org/game/tank-destroyer
SWF URL: http://fancyplanet.org/games/39.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-25
Channel: nightly
Built: 2023-02-25T00:19:43.168Z
Commit: 79cc42c739084c81f473d729d23b633c9f629dea
Is extension: true

# Metadata
width: 550
height: 550
frameRate: 31
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2274362

### LINKED ISSUE #9937: Error on https://game35214.konggames.com/games/Morpheme/more-blocks-with-letters-on/frame/f8a69434-df40-454c-a4ad-441f40a423a8/
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:373:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:373:18
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d47c1fc8f81804494577.js:1:46443)
    at std::sync::once::Once::call_once::{{closure}}::h232d3d481290a400 (wasm://wasm/0294c58a:wasm-function[2042]:0x4f326d)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294c58a:wasm-function[1977]:0x4e44a8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68563d86acb3fcd8 (wasm://wasm/0294c58a:wasm-function[7469]:0x7b4e11)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294c58a:wasm-function[5272]:0x70d90d)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294c58a:wasm-function[7799]:0x7c3ff2)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h3c6d3582d9901768 (wasm://wasm/0294c58a:wasm-function[3642]:0x6651d8)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h779e3e67d2cd5965 (wasm://wasm/0294c58a:wasm-function[2824]:0x5bfd24)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h39bf83e61704002e (wasm://wasm/0294c58a:wasm-function[708]:0x2696b5)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h1484c6181084f9d2 (wasm://wasm/0294c58a:wasm-function[1514]:0x4186e7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game35214.konggames.com/games/Morpheme/more-blocks-with-letters-on/frame/f8a69434-df40-454c-a4ad-441f40a423a8/?kongregate_host=www.kongregate.com
SWF URL: https://game35214.konggames.com/gamez/0003/5214/live/more-blocks-with-letters-on.swf?kongregate_game_version=1285675477

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-09
Channel: nightly
Built: 2023-03-09T00:20:13.637Z
Commit: fc223e959b1529b94a4276e2b08238f9e61197b1
Is extension: false

# Metadata
width: 768
height: 590
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2827954

### LINKED ISSUE #10002: Error on https://www.play-games.com/embed/4755.html
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.600a662204eb354628f4.js:1:5387)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0282d58e:wasm-function[1945]:0x4a67c7)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0282d58e:wasm-function[1882]:0x495e31)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0282d58e:wasm-function[7293]:0x77c499)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0282d58e:wasm-function[5182]:0x6d69e6)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0282d58e:wasm-function[7603]:0x78b226)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h018b8055f2ca652f (wasm://wasm/0282d58e:wasm-function[3588]:0x630afe)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h619429c22793f41b (wasm://wasm/0282d58e:wasm-function[2739]:0x581caa)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h12667dcd5bc2c65d (wasm://wasm/0282d58e:wasm-function[720]:0x254cb8)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb3f7be01839936e4 (wasm://wasm/0282d58e:wasm-function[1468]:0x3df1a2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.play-games.com/embed/4755.html
SWF URL: https://www.play-games.com/files/swf/Mine-Blocks_1434794853.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.35
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-23
Channel: nightly
Built: 2023-02-23T00:19:44.956Z
Commit: e17b154d47e2f20055770292f4c0a12c15e04efd
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 25
numFrames: 2
swfVersion: 10
backgroundColor: #000099
isActionScript3: true
uncompressedLength: 4257951

### LINKED ISSUE #10138: Error on http://www.juegosjuegos.com/embed/rebel-girl
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.16a8d4ce80a8ea8229a9.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90 (wasm://wasm/02a65c2a:wasm-function[8039]:0x7f123e)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a65c2a:wasm-function[5354]:0x72830e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a65c2a:wasm-function[7918]:0x7ec539)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9 (wasm://wasm/02a65c2a:wasm-function[3697]:0x67d13c)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h0bbcae0b3527237f (wasm://wasm/02a65c2a:wasm-function[3071]:0x6004c5)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a65c2a:wasm-function[770]:0x296f99)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd (wasm://wasm/02a65c2a:wasm-function[1556]:0x42bbcf)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1 (wasm://wasm/02a65c2a:wasm-function[785]:0x2a1941)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a65c2a:wasm-function[770]:0x296fd5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.juegosjuegos.com/embed/rebel-girl
SWF URL: https://cdn.pomu.com/files/game/content/9566/8946.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-17
Channel: nightly
Built: 2023-03-17T00:21:29.148Z
Commit: 32f8330199d6c244e41d15fcbb9a9d028fc83af8
Is extension: false

# Metadata
width: 1000
height: 850
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1272143

### LINKED ISSUE #10400: Error on https://www.glowmonkey.com/chooseyourweapon4.php
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
339/getImports/imports.wbg.__wbg_new_15d3966e9981a196@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:2200:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90@:wasm-function[8041]:0x7f70c8
std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8@:wasm-function[5353]:0x72d280
core::panicking::panic_fmt::h2a7f454a5f5da218@:wasm-function[7921]:0x7f23f2
ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9@:wasm-function[3706]:0x68392c
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he4a116ef9010da52@:wasm-function[3069]:0x604073
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42@:wasm-function[768]:0x28fda1
ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd@:wasm-function[1560]:0x4352bf
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29acd9
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29a484
<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::he06e52605ff8f9e8@:wasm-function[3074]:0x607a6c
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29a48e
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::hbd86c15abf8951d3@:wasm-function[1546]:0x43058b
ruffle_web::Ruffle::tick::hd363147e523d3ba1@:wasm-function[691]:0x2465cb
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h36472d83d0669f8c@:wasm-function[9645]:0x8304a6
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h678c9e4dc3beaab6@:wasm-function[8552]:0x802ee1
__wbg_adapter_56@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:282:10
real@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:259:20

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: games/chooseyourweapon4.swf
Param quality: high
Param wmode: opaque
Param swfversion: 6.0.65.0
Param expressinstall: Scripts/expressInstall.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.glowmonkey.com/chooseyourweapon4.php
SWF URL: https://www.glowmonkey.com/games/chooseyourweapon4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: true

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2546381

### LINKED ISSUE #10546: Anbot - Weird Loops everywhere
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.spiele-umsonst.de/ruffle/core.ruffle.d0557de10628cbe98f62.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (wasm://wasm/02a79bda:wasm-function[8163]:0x7ef5ba)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a79bda:wasm-function[5431]:0x71d11b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a79bda:wasm-function[8045]:0x7ea229)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hd3678225016fbaa9 (wasm://wasm/02a79bda:wasm-function[864]:0x2dab45)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hcd6dc3ef44c0642a (wasm://wasm/02a79bda:wasm-function[2817]:0x5b8648)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3e925d65c8f046f1 (wasm://wasm/02a79bda:wasm-function[775]:0x29027a)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h6857bb7c2b238038 (wasm://wasm/02a79bda:wasm-function[1565]:0x42345a)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hb8ef6c72ed998900 (wasm://wasm/02a79bda:wasm-function[785]:0x297979)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::hebf232eab80e2adf (wasm://wasm/02a79bda:wasm-function[3016]:0x5e5cdb)
```

# Player Info
Allows script access: false

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/Anbot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-03
Channel: nightly
Built: 2023-04-03T00:21:21.992Z
Commit: 9441182b7d70d334ea6a7921f9b5541246a5a447
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2366401

### LINKED ISSUE #10740: "Mad Karate Man" Crash on start (Build nightly 2023-04-19)
### Describe what you were doing

Attempting to play "Mad Karate Man" at: https://www.kongregate.com/games/ninjakiwi/mad-karate-man

### What does the crash message say?

# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a648731f80678e415588.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a7785a:wasm-function[8134]:0x7ee7f9)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a7785a:wasm-function[5462]:0x727498)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a7785a:wasm-function[8016]:0x7e9468)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h5e7c07cdf91e2471 (wasm://wasm/02a7785a:wasm-function[864]:0x2d1bb9)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h1dba24217afabf1d (wasm://wasm/02a7785a:wasm-function[2847]:0x5c2184)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd84fb6f602ec2e60 (wasm://wasm/02a7785a:wasm-function[777]:0x293b4b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h74a63696e0e4a88f (wasm://wasm/02a7785a:wasm-function[1563]:0x41dbe8)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h3c3024109b2e33ab (wasm://wasm/02a7785a:wasm-function[788]:0x29abfb)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd84fb6f602ec2e60 (wasm://wasm/02a7785a:wasm-function[777]:0x293b87)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game73259.konggames.com/games/Ninjakiwi/mad-karate-man/frame/368ea2e9-95f5-429c-b873-b50b95ec337d/?kongregate_host=www.kongregate.com
SWF URL: https://game73259.konggames.com/gamez/0007/3259/live/mkm_world.swf?kongregate_game_version=1267572991

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-19
Channel: nightly
Built: 2023-04-19T00:19:17.744Z
Commit: 4f4327b152087379bae0d566a5d80aa7c9b9c477
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1069870

### Ruffle Version

nightly 2023-04-19

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Additional information

_No response_

### LINKED ISSUE #11278: Error on https://flashmuseum.org/the-simpsons-slingshot-game/
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.5.29/core.ruffle.0ccbdb6b447da7749307.js:1:53590
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hf586b8fd5967b71f]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h7f7102b82d51338f]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::he4489d678d6570d5]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h4e7be8cc8b0c0348]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h52d358259042e16d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha0829c59c30d8e37]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::place_object::h50392e2011013550]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h90166a5a5f537fe5]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha0829c59c30d8e37]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::place_object::h50392e2011013550]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h90166a5a5f537fe5]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h7a3eaeb50654e7b2]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h90166a5a5f537fe5]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h7a3eaeb50654e7b2]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h90166a5a5f537fe5]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h44a69a10b9c99a23]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h4f57950e199331b7]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h22f48c5e8ccac896]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hf98bfdbd3031b9c5]@[wasm code]
wasm-stub@[native code]
E@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.5.29/core.ruffle.0ccbdb6b447da7749307.js:1:3309
f@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.5.29/core.ruffle.0ccbdb6b447da7749307.js:1:2761
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashmuseum.org/the-simpsons-slingshot-game/
SWF URL: https://flashmuseum.s3.amazonaws.com/892.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-29
Channel: nightly
Built: 2023-05-29T00:19:07.550Z
Commit: 0955ab40e67d4668f3ebd5fbdf3602750e35abb8
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 34
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2618938

### LINKED ISSUE #11570: http://www.onemorelevel.com/game/bloons_christmas
### Describe the bug

the game just starts freaking out when i try to play it 

### Expected behavior

to be able to play the game

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge  16

### Additional information

_No response_

### LINKED ISSUE #11668: Error on https://famitama.xyz/pc/index.html
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6a84e:wasm-function[8635]:0x83ec5c)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6a84e:wasm-function[5603]:0x766c3d)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6a84e:wasm-function[8499]:0x83a866)
    at core::panicking::panic::h2f041bf6aa990dfd (wasm://wasm/02c6a84e:wasm-function[7756]:0x809830)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hd423123fbfc4ea6b (wasm://wasm/02c6a84e:wasm-function[646]:0x1f2d10)
    at ruffle_core::loader::Loader::preload_tick::h34a49ba98b65c11c (wasm://wasm/02c6a84e:wasm-function[1665]:0x4862c4)
    at ruffle_core::loader::Loader::movie_loader_data::hb7fa154deb2c41c2 (wasm://wasm/02c6a84e:wasm-function[2555]:0x5a8bd4)
    at ruffle_core::loader::Loader::movie_loader::{{closure}}::h103be6e9de20330c (wasm://wasm/02c6a84e:wasm-function[718]:0x24de3c)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h4e80d7d8baa33206 (wasm://wasm/02c6a84e:wasm-function[1023]:0x35c95a)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://famitama.xyz/pc/index.html
SWF URL: https://famitama.xyz/pc/famitama_shell_patch.swf?init_site_lang=en

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-21
Channel: nightly
Built: 2023-06-21T00:19:43.730Z
Commit: b3c40ecda107ee33cbc44868fcd7dfdbdc634775
Is extension: true

# Metadata
width: 752
height: 564
frameRate: 12
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 1021590

### LINKED ISSUE #12005: Error on https://www.wowgame.jp/game_html/2762.html
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://www.wowgame.jp/script_sp/ruffle/ruffle-nightly-2023_06_24-web-selfhosted/core.ruffle.4aca22fbd1367f86fc4e.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02cafe5a:wasm-function[8726]:0x84d372)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cafe5a:wasm-function[5668]:0x766dff)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cafe5a:wasm-function[8589]:0x848eed)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hfa767080570162c4 (wasm://wasm/02cafe5a:wasm-function[3362]:0x64be4b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::ha7599e06ebfbe378 (wasm://wasm/02cafe5a:wasm-function[2920]:0x5f6bd3)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h93ae68f7244fa0b9 (wasm://wasm/02cafe5a:wasm-function[818]:0x2b750d)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb2bf6fcc9f70c38a (wasm://wasm/02cafe5a:wasm-function[1382]:0x40e739)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::he7b7d267973943c2 (wasm://wasm/02cafe5a:wasm-function[793]:0x2a443f)
    at ruffle_core::loader::Loader::movie_loader_complete::h6ef8580edbf9f84d (wasm://wasm/02cafe5a:wasm-function[752]:0x280b68)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.wowgame.jp/game_html/2762.html
SWF URL: https://www.wowgame.jp/game_files/2762/2762.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-24
Channel: nightly
Built: 2023-06-24T00:25:29.354Z
Commit: 6d77ff1fc41aa34848188aa79ddb8c283671df4a
Is extension: false

# Metadata
width: 700
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #0099CC
isActionScript3: true
uncompressedLength: 2656792

### LINKED ISSUE #12341: Garden raider - Fails to load title screen.
### Describe the bug

(minor epilepsy warning)

http://www.flashpacman.info/pacman-garden-raider.php

Game briefly shows loading screen, then attempts to load home screen. The only two things that appear are the background under the trees (which you normally do not see) and the logo flashing.

Stage Info shows that the World and Local Bounds' first value are rapidly switching between 0.00 and -0.10, third value switching between 640.95 and 641.05, and the fourth value switching between 480.95 and 482.05.

Within the children of Stage\MovieClip "root1"\Loader Display (really not sure how to describe these) there is a graphic and movieclip instance incrementing quickly.

ruffle_HFaM4iyvYI

### Expected behavior

This is what the title screen should look like:
image

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

_No response_

### Additional information

Occurs on both 2023-07-26 Nightly Standalone and Extension (Firefox 115.0.2) versions.

### LINKED ISSUE #12407: Traps and Sorcery ...can't play...STOP at Loading
### Describe the bug

Traps and Sorcery ...can't play...STOP at Loading

url:
https://www.kongregate.com/games/nowereginald/traps-and-sorcery

swf:
https://game112515.konggames.com/gamez/0011/2515/live/trapsandsorcery.swf?kongregate_game_version=1305142848

### Expected behavior

Traps and Sorcery ...can't play...STOP at Loading

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 115.0.5790.110 [64 bits]

### Additional information

_No response_

### LINKED ISSUE #12568: mario gh , just a blockscreen.
### Describe the bug

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-05
Channel: nightly
Built: 2023-08-05T00:19:09.531Z
Commit: f75b36a32a9cc1f1b99ed168107738218d7dabb3
Is extension: false

# Metadata
width: 624
height: 480
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 5560460

SWF:
[mario-gh.zip](https://github.com/ruffle-rs/ruffle/files/12266031/mario-gh.zip)

### Expected behavior

 just a blockscreen.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 115.0.5790.110 [64 bits]

### Additional information

_No response_

### LINKED ISSUE #13211: Error on https://web.archive.org/web/20170802031128/http://www.douchebaggames.com/Douchebag-Douchebags-Chick.html
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b0b313a9b2fe55f (wasm://wasm/02f98346:wasm-function[9186]:0x8e70a7)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f98346:wasm-function[6037]:0x7f89a0)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f98346:wasm-function[9022]:0x8e28db)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hbc601c520fca1d9a (wasm://wasm/02f98346:wasm-function[3798]:0x6d8470)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h915d8fe0eef04769 (wasm://wasm/02f98346:wasm-function[3233]:0x67b965)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hca2c85aaf6295955 (wasm://wasm/02f98346:wasm-function[1045]:0x3618ed)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h2a17ef3feef4597c (wasm://wasm/02f98346:wasm-function[1882]:0x50aedc)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hce8c2b09d85b3b06 (wasm://wasm/02f98346:wasm-function[817]:0x2aea27)
    at ruffle_core::loader::Loader::movie_loader_complete::h8e86b3398e62eee7 (wasm://wasm/02f98346:wasm-function[801]:0x29ddd7)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Vega 3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://web.archive.org/web/20170802031128/http://www.douchebaggames.com/Douchebag-Douchebags-Chick.html
SWF URL: http://www.gamesfree.ca/games/Douchebag_Chick.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-02
Channel: nightly
Built: 2023-08-02T00:22:54.390Z
Commit: 006393c5816e68b54c6720fcd8e657009cfb90d8
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 50
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5209123

### LINKED ISSUE #13371: Error on https://pelikone.fi/pelit/aivopahkinat/Monkey-Go-Happy-2/5819
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2414:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h327b73cb23b2fa83 (wasm://wasm/032916fa:wasm-function[9709]:0x98b9d0)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/032916fa:wasm-function[6338]:0x882c95)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/032916fa:wasm-function[9542]:0x986f14)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h6848b10fb58f5799 (wasm://wasm/032916fa:wasm-function[3318]:0x6d3891)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h5800325acd5f098e (wasm://wasm/032916fa:wasm-function[3227]:0x6bf8f7)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h26b33f7858119546 (wasm://wasm/032916fa:wasm-function[1075]:0x3966fe)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he2761d539d81ebd5 (wasm://wasm/032916fa:wasm-function[1931]:0x55d249)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h9da906cece72cf22 (wasm://wasm/032916fa:wasm-function[842]:0x2e30e1)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::hccce0e225c6ac94c (wasm://wasm/032916fa:wasm-function[2697]:0x638f23)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://pelikone.fi/games/files/gVnxWrFmzZ8-JhQ.swf
Param wmode: gpu
Param allowscriptaccess: always
Param bgcolor: 000000
Param base: https://pelikone.fi/games/files/5819/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://pelikone.fi/pelit/aivopahkinat/Monkey-Go-Happy-2/5819?archive=true
SWF URL: https://pelikone.fi/games/files/gVnxWrFmzZ8-JhQ.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-30
Channel: nightly
Built: 2023-09-30T00:20:30.366Z
Commit: f140e7a14b379993625b07524c4453ae98592384
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2347704

### LINKED ISSUE #13506: Error on https://game37877.konggames.com/games/Wackiedk/artificial-junk/frame/37dc6be0-4d7f-44f1-ab9f-53bc9107d7c9/
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6e4d2c1da0a3fd6f0339.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/032537fe:wasm-function[9643]:0x97dc8c)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032537fe:wasm-function[6308]:0x883a71)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032537fe:wasm-function[9448]:0x978b51)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::ha2518c284f462eb1 (wasm://wasm/032537fe:wasm-function[3420]:0x705ab4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h420c861e7db6aa46 (wasm://wasm/032537fe:wasm-function[5040]:0x810e39)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hf63bef5d8ef281d7 (wasm://wasm/032537fe:wasm-function[1120]:0x3dfc83)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hc07eb8ea60be21d5 (wasm://wasm/032537fe:wasm-function[1966]:0x57ac9f)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h9030ea5e67cd003b (wasm://wasm/032537fe:wasm-function[863]:0x31a680)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hf63bef5d8ef281d7 (wasm://wasm/032537fe:wasm-function[1120]:0x3dfcbf)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game37877.konggames.com/games/Wackiedk/artificial-junk/frame/37dc6be0-4d7f-44f1-ab9f-53bc9107d7c9/?kongregate_host=www.kongregate.com
SWF URL: https://game37877.konggames.com/gamez/0003/7877/live/Artificial_Junk_Reconstruct.swf?kongregate_game_version=1236022578

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-11
Channel: nightly
Built: 2023-10-11T00:22:14.322Z
Commit: 0ef28604b16bb9b27ee9291f527a1827d7713b7b
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 65
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 4564642

### LINKED ISSUE #13548: Error on https://f.kbhgames.com/RS/game.php
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
339/V/n.wbg.__wbg_new_d258248ed531ff54@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ba551adeafef75c8ec4f.js:1:51724
core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8@:wasm-function[9629]:0x98166d
std::panicking::rust_panic_with_hook::h3aa054d35a0817d7@:wasm-function[6300]:0x8856b5
core::panicking::panic_fmt::h3e1dd3d08288569e@:wasm-function[9434]:0x97c532
ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::ha2518c284f462eb1@:wasm-function[3327]:0x6e5560
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h420c861e7db6aa46@:wasm-function[4920]:0x807143
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hf63bef5d8ef281d7@:wasm-function[1099]:0x3ad40d
ruffle_core::display_object::movie_clip::MovieClip::place_object::hc07eb8ea60be21d5@:wasm-function[1936]:0x551282
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h9030ea5e67cd003b@:wasm-function[853]:0x2f9830
<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h8cc07b9ca089d50d@:wasm-function[2765]:0x655b7c
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h9030ea5e67cd003b@:wasm-function[853]:0x2f8f4c
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h9ca0685da9842905@:wasm-function[3735]:0x7331cb
ruffle_web::Ruffle::tick::he0dbb902f3ea146e@:wasm-function[790]:0x2b52b6
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h522a8ebb44b40f90@:wasm-function[11748]:0x9c9241
wasm_bindgen::convert::closures::invoke1_mut::h2cd3f494363c3f36@:wasm-function[10379]:0x99dbd9
S@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ba551adeafef75c8ec4f.js:1:2722
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ba551adeafef75c8ec4f.js:1:2511

```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/pistoltraining.swf&w=550&h=400&warnsupport=true
SWF URL: https://f.kbhgames.com/2018/swf/pistoltraining.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-14
Channel: nightly
Built: 2023-10-14T00:21:06.189Z
Commit: 93aa3a493ba4c42f80e5d5a17044702e4942f89d
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 31
numFrames: 2
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 493736

### LINKED ISSUE #13917: Error on https://funkypotato.com/must-pop-words/
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://funkypotato.com/ruffle/core.ruffle.bed09e6ad93ab0a6da18.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h04cf337995af4056 (wasm://wasm/0335c8f2:wasm-function[9871]:0x9ad267)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0335c8f2:wasm-function[6492]:0x8ae58a)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0335c8f2:wasm-function[9677]:0x9a8169)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h2cea184a669a9ac7 (wasm://wasm/0335c8f2:wasm-function[3461]:0x70cf6a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h866ccdb9a41a0274 (wasm://wasm/0335c8f2:wasm-function[4076]:0x778e40)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb5ce3aab5347667b (wasm://wasm/0335c8f2:wasm-function[1122]:0x3a9d37)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hcece344a0c6226ce (wasm://wasm/0335c8f2:wasm-function[2046]:0x575755)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h0938514aab36bf6c (wasm://wasm/0335c8f2:wasm-function[907]:0x307366)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb5ce3aab5347667b (wasm://wasm/0335c8f2:wasm-function[1122]:0x3a9d73)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 620 (0x00005916) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /gamez/must-pop-words.swf
Param movie: /gamez/must-pop-words.swf
Param quality: best
Param bgcolor: #000000
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://funkypotato.com/must-pop-words/?preview_id=11758&preview_nonce=f5c235c81e&_thumbnail_id=11762&preview=true
SWF URL: https://funkypotato.com/gamez/must-pop-words.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-08
Channel: nightly
Built: 2023-11-08T00:22:09.499Z
Commit: f334963b47bd89f29aedd19f832a61b3e1341132
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1159025

### LINKED ISSUE #14136: Error on https://funkypotato.com/classic-snakes/
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://funkypotato.com/ruffle/core.ruffle.5dcaa225af3bc049878c.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88ac)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h09dee5ef409c86e9 (wasm://wasm/033f8df2:wasm-function[3466]:0x726d3b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hac6bb5600d118aed (wasm://wasm/033f8df2:wasm-function[4083]:0x79385e)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h1de1c961276c9890 (wasm://wasm/033f8df2:wasm-function[1124]:0x3d108e)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb432e08fd90072de (wasm://wasm/033f8df2:wasm-function[2062]:0x5a58d2)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hfc9a9abcd1bab31c (wasm://wasm/033f8df2:wasm-function[918]:0x32ad8b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h1de1c961276c9890 (wasm://wasm/033f8df2:wasm-function[1124]:0x3d10ca)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /gamez/classic-snakes.swf
Param movie: /gamez/classic-snakes.swf
Param quality: best
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://funkypotato.com/classic-snakes/?preview_id=39492&preview_nonce=2a76eb29b6&_thumbnail_id=39496&preview=true
SWF URL: https://funkypotato.com/gamez/classic-snakes.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 OPR/103.0.0.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-14
Channel: nightly
Built: 2023-11-14T00:21:56.078Z
Commit: b196c8d1bcc2d691c61d8d78b17b5fd60e0234b8
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 12
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 69976

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
There are still some issues (see the unchecked checkbox), and I'm unsure about how accurate the mouse pick implementation is, but content should at least no longer panic.

Fixes #9330, fixes #9724, fixes #10400, fixes #8941, fixes #11668, fixes #10546, fixes #9937, fixes #12005, fixes #12568, fixes #10138, fixes #10740, fixes #12341, fixes #12407, fixes #11570, fixes #10002, fixes #9666, fixes #11278, fixes #14136, fixes #13917, fixes #13371, fixes #13548, fixes #13211, fixes #13506, fixes #9437, ...

The animation on #10175 plays correctly with this PR, though, as mentioned, it layers as a result of `Loader.unloadAndStop` being unimplemented.

KOF vs DNF (#9917) plays fine when this PR is combined with #12823, though it spews several harmless warnings and errors (a result of the obfuscation).

TODO/list of working mixed AVM games:

- [X] Anbot (#10546)
- [X] #9937
- [X] #8941
- [X] #9330
- [X] Tank Destroyer (#9724)
- [X] #10400
- [X] #11668
- [X] #12005
- [X] #12568
- [x] Mine Blocks (#10002)
- [x] Feeding Frenzy (#9666) (minor issue remaining- text that appears after eating a smaller fish isn't text, just a bar)
- [x] Christmas Bloons (#11570)
- [ ] Doodle Jump (#10759) (game over screen when touching an enemy is shifted (probably caused by `RemoveSprite: Source is not a display object` spam))
- [x] Mad Karate Man (#10740)
- [x] Traps and Sorcery (#12407)
- [x] Garden Raider (#12341)
- [x] Add test
- [ ] More tests? (not merge-blocking)

### CODE REVIEW

**Comment by danielhjacobs** [comment]
This PR does fix number 4 on #10175. If you go to a different slide and then back, the animation becomes duplicated. That may relate to Loader.unload or Loader.unloadAndStop rather than mixed-avm itself.

This is especially noticeable on http://new.weedtowonder.org/sequencing.html. If you click the second circle from the top, as you go through different animations, each becomes layered on top of the other.

**Comment by Lord-McSweeney** [comment]
The AVM1-in-AVM2 seems to be working mostly correctly, and AVM2-in-AVM1 should no longer panic, so I think this is ok for an initial attempt.

File: core/src/avm2/globals/flash/display/bitmap.rs [hunk 1]
```diff
@@ -87,8 +87,14 @@ pub fn init<'gc>(
...
                 .unwrap_or_else(|| BitmapDataWrapper::dummy(activation.context.gc_context));
 
-            let bitmap =
-                Bitmap::new_with_bitmap_data(&mut activation.context, 0, bitmap_data, smoothing);
+            let bitmap = Bitmap::new_with_bitmap_data(
+                activation.context.gc_context,
+                0,
+                bitmap_data,
+                smoothing,
+                activation.context.swf,
```
Comment (iwannabethedev) [inline core/src/avm2/globals/flash/display/bitmap.rs:95]: (Nit: Would it be cleaner or less clean to keep both of the "context" parameters at the start? Like, instead of:

```rust
Bitmap::new_with_bitmap_data(activation.context.gc_context, 0, bitmap_data, smoothing, activation.context.swf);
```

it would be:


```rust
Bitmap::new_with_bitmap_data(activation.context.gc_context, activation.context.swf, 0, bitmap_data, smoothing);
```

File: core/src/display_object/avm1_button.rs [hunk 2]
```diff
@@ -575,6 +579,15 @@ impl<'gc> TInteractiveObject<'gc> for Avm1Button<'gc> {
         None
     }
 
+    fn mouse_pick_avm2(
+        &self,
+        _context: &mut UpdateContext<'_, 'gc>,
+        _point: Point<Twips>,
+        _require_button_mode: bool,
+    ) -> Avm2MousePick<'gc> {
+        Avm2MousePick::NotAvm2
```
Comment (iwannabethedev) [inline core/src/display_object/avm1_button.rs:588]: Is this a stub-implementation? If so, might adding a `TODO` or `FIXME` comment be useful?

File: core/src/avm2/globals/flash/display/bitmap.rs (hunk 1 above)
Comment (iwannabethedev) [reply core/src/avm2/globals/flash/display/bitmap.rs:95]: (Never mind, I think I misunderstood the code).

File: core/src/display_object/avm1_button.rs (hunk 2 above)
Comment (Lord-McSweeney) [reply core/src/display_object/avm1_button.rs:588]: No, this is a correct implementation designed to return "This button was not AVM2" instead of "Missed".

File: core/src/display_object/loader_display.rs [hunk 3]
```diff
@@ -180,10 +180,24 @@ impl<'gc> TInteractiveObject<'gc> for LoaderDisplay<'gc> {
...
         for child in self.iter_render_list().rev() {
             if let Some(int) = child.as_interactive() {
                 if let Some(result) = int.mouse_pick_avm1(context, point, require_button_mode) {
-                    return Some(result);
+                    if int.as_displayobject().movie().is_action_script_3() {
+                        let avm2_result = int.mouse_pick_avm2(context, point, require_button_mode);
+                        if let Avm2MousePick::Hit(result) = avm2_result {
+                            return Some(result);
+                        } else {
+                            return None;
```
Comment (iwannabethedev) [inline core/src/display_object/loader_display.rs:196]: The old code in this block did not appear to ever return `None`. Is it correct to return `None` in this case?

**Comment by iwannabethedev** [comment]
I have made a superficial code review. I do not understand the codebase or Rust well enough for more than a superficial code review, and the PR will therefore still need to be reviewed by others. The code looked good at a superficial glance.

What I worry about more is whether the PR might break pure AVM1 and pure AVM2 games, and if there is a lot of breakage or critical breakage, how easy the PR will be to revert (or how it will be handled). On the other hand, I would guess that there is a large number of automated tests. A lot of the code was focused on interaction and input handling. How many automated tests are there that tests interactivity and input handling? Other thoughts on this topic?

File: core/src/display_object/interactive.rs [hunk 4]
```diff
@@ -475,6 +475,7 @@ pub trait TInteractiveObject<'gc>:
 pub enum Avm2MousePick<'gc> {
     Hit(InteractiveObject<'gc>),
     PropagateToParent,
+    NotAvm2,
     Miss,
```
Comment (Aaron1011) [inline core/src/display_object/interactive.rs:479]: It looks like this PR creates instances of this variant, but never explicitly tests against it. Can we just use `Miss` instead, or do you anticipate needing to know that a mouse pick failed specifically due to an avm1 target?

File: core/src/frame_lifecycle.rs [hunk 5]
```diff
@@ -112,9 +116,10 @@ pub fn run_all_phases_avm2(context: &mut UpdateContext<'_, '_>) {
 /// This is a no-op on AVM1, which has it's own catch-up logic.
 pub fn catchup_display_object_to_frame<'gc>(
     context: &mut UpdateContext<'_, 'gc>,
+    is_content_as3: bool,
     dobj: DisplayObject<'gc>,
 ) {
-    if !context.is_action_script_3() {
+    if !is_content_as3 {
```
Comment (Aaron1011) [inline core/src/frame_lifecycle.rs:122]: Can this just be `dobj.movie().is_action_script_3()`, like you do elsewhere in this PR?

Comment (Lord-McSweeney) [reply core/src/frame_lifecycle.rs:122]: I got borrow errors when doing that, so I left it as this.

File: core/src/display_object/interactive.rs (hunk 4 above)
Comment (Lord-McSweeney) [reply core/src/display_object/interactive.rs:479]: `Miss` and `NotAvm2` _should_ be the same thing, I was just trying to figure out how to differentiate between the two.

**Comment by iwannabethedev** [comment]
Is it possible to add tests for this functionality? Or would that be complicated and not worth the trouble? Or too early days?

**Comment by n0samu** [comment]
Fixes #10400, #10138

Testing this with Mine Blocks (#10002), there are some problems with the game not present when it's extracted from the MochiCrypt package:
- The text input box under "Type world name" is displayed incorrectly
- The "Create world" button does not work
image

Testing this with Feeding Frenzy (#9666), the game does not start correctly after clicking the Play button. This problem does not happen when the inner SWF is extracted and played by itself.

**Comment by Lord-McSweeney** [comment]
Also fixes #11278.

**Review by Dinnerbone — APPROVED** [review]

**Comment by Aaron1011** [comment]
This still needs the changes I requested

File: core/src/display_object/container.rs [hunk 6]
```diff
@@ -843,6 +844,14 @@ impl<'gc> ChildContainer<'gc> {
         self.mouse_children = mouse_children;
     }
 
+    pub fn movie(&self) -> Arc<SwfMovie> {
+        self.movie.clone()
+    }
+
+    pub fn set_movie(&mut self, movie: Arc<SwfMovie>) {
```
Comment (Aaron1011) [inline core/src/display_object/container.rs:851]: Is this unused?

File: core/src/display_object/edit_text.rs [hunk 7]
```diff
@@ -1954,6 +1954,11 @@ impl<'gc> TInteractiveObject<'gc> for EditText<'gc> {
         point: Point<Twips>,
         _require_button_mode: bool,
     ) -> Option<InteractiveObject<'gc>> {
+        // Don't do anything if run in an AVM2 context.
+        if self.as_displayobject().movie().is_action_script_3() {
```
Comment (Aaron1011) [inline core/src/display_object/edit_text.rs:1958]: Will this check ever pass? We should only be able to do an AVM2 -> AVM1 transition through a `LoaderDisplay`, which already checks the child movie type to decide whether to call `mouse_pick_avm1` or `mouse_pick_avm2`. I think this should be an assertion instead

File: core/src/display_object/container.rs (hunk 6 above)
Comment (Lord-McSweeney) [reply core/src/display_object/container.rs:851]: https://github.com/Lord-McSweeney/ruffle/blob/67cfc0e0dbff6c48b4fe2b13447ba715281848f6/core/src/display_object/stage.rs#L235

**Review by Aaron1011 — APPROVED** [review]
This has been open for a long time - let's get it in so that we have something to work with for debugging SWFs

File: core/src/avm2/globals/flash/display/display_object_container.rs [hunk 8]
```diff
@@ -141,7 +141,13 @@ pub fn get_child_at<'gc>(
     {
         let index = args.get_i32(activation, 0)?;
         return if let Some(child) = dobj.child_by_index(index as usize) {
-            Ok(child.object2())
+            // This is a hack to make AVM1Movie work- in Ruffle, Loader.content calls getChildAt.
```
Comment (adrian17) [inline core/src/avm2/globals/flash/display/display_object_container.rs:144]: non-blocking: can you expand on this comment a little bit? I'm not entirely sure what you meant here

File: core/src/display_object/movie_clip.rs [hunk 9]
```diff
@@ -163,6 +163,9 @@ pub struct MovieClipData<'gc> {
     has_focus: bool,
     avm2_enabled: bool,
 
+    /// The cached AVM2 class AVM1Movie corresponding to this MovieClip.
+    avm2_avm1movie: Option<Avm2Object<'gc>>,
```
Comment (adrian17) [inline core/src/display_object/movie_clip.rs:168]: also general question: should we maybe drop the `AvmObject` enum here and just split it into
```
// avm1 MC
object1: Option<Avm1Object<'gc>>,
// avm2 MC or AVM1Movie
object2: Option<Avm2Object<'gc>>,
```
?

File: core/src/display_object/movie_clip.rs [hunk 10]
```diff
@@ -2843,20 +2864,55 @@ impl<'gc> TDisplayObject<'gc> for MovieClip<'gc> {
             .unwrap_or(Avm2Value::Null)
     }
 
+    /// Returns object2()- however, if the MC was AVM1, creates and returns an AVM1Movie.
+    fn object2_possibly_avm1(&self, context: &mut UpdateContext<'_, 'gc>) -> Avm2Value<'gc> {
```
Comment (adrian17) [inline core/src/display_object/movie_clip.rs:2895]: does this need to be lazy? Something in line with the "normal" construction, like:
```diff
 fn construct_frame(&self, context: &mut UpdateContext<'_, 'gc>) {
    if self.movie().is_action_script_3() && self.frames_loaded() >= 1 {
        self.allocate_as_avm2_object(context, (*self).into());
+   } else if !self.movie().is_action_script_3() && context.stage.is_action_stage_3() && self.frames_loaded() >= 1 {
+       // self.object2 = new AVM1Movie();              
```

File: core/src/player.rs [hunk 11]
```diff
@@ -2606,8 +2608,10 @@ fn run_mouse_pick<'gc>(
                         res = Some(target);
                     }
                 }
+
                 res
             } else {
+                // Run AVM1 mouse pick
```
Comment (adrian17) [inline core/src/player.rs:2611]: not sure if this comment is useful ;D

File: core/src/player.rs [hunk 12]
```diff
@@ -1640,11 +1644,9 @@ impl Player {
...
 
         self.update(|context| {
-            if context.is_action_script_3() {
-                run_all_phases_avm2(context);
-            } else {
-                Avm1::run_frame(context);
-            }
+            // TODO: Is this order correct?
+            run_all_phases_avm2(context);
+            Avm1::run_frame(context);
```
Comment (adrian17) [inline core/src/player.rs:1649]: no specific comment here, I'm just... amazed this works as-is at all without major breakages or regressing perf 😅 
As for the order, could we test we somehow by loading a bunch of mixed versions in a chain and observing the order? Maybe it's still recursive in a way? Like, random guess: avm2 recursion executing avm1 exec list for the avm1movieclip when reaching it?

File: core/src/display_object/movie_clip.rs (hunk 10 above)
Comment (Lord-McSweeney) [reply core/src/display_object/movie_clip.rs:2895]: The problem is that a _ton_ of places check if `object2` is null to check if the SWF is AVM1. However, #12975 got merged so i need to rewrite this part anyway.

**Comment by Lord-McSweeney** [comment]
#12975 broke my hacky impl of AVM1Movie, so I need to fix this PR.

File: core/src/display_object/edit_text.rs (hunk 7 above)
Comment (Aaron1011) [reply core/src/display_object/edit_text.rs:2142]: Never mind - AVM1 can directly load an AVM2 movie into a MovieClip, which will trigger this code path

File: core/src/loader.rs [hunk 13]
```diff
@@ -1696,6 +1696,10 @@ impl<'gc> Loader<'gc> {
 
                     if let Some(domain) = domain {
                         library.set_avm2_domain(domain);
+                    } else {
+                        // This is in case the MovieLoaderData is AVM1, but loaded an AVM2 SWF (mixed AVM).
+                        let stage_domain = activation.context.avm2.stage_domain();
```
Comment (Aaron1011) [inline core/src/loader.rs:1701]: Can you move this to the `let domain = if let MovieLoaderVMData::Avm2 {` block above (the `else` case)?

File: core/src/loader.rs [hunk 14]
```diff
@@ -1928,6 +1951,7 @@ impl<'gc> Loader<'gc> {
                 // We call these methods after we initialize the `LoaderInfo`, but before
                 // we add the loaded clip as a child. The frame constructor should see
                 // 'this.parent == null' and 'this.stage == null'
+
```
Comment (Aaron1011) [inline core/src/loader.rs:1954]: This can be removed

**Comment by Aaron1011** [comment]
It would be good to have a test that does an AVM2 -> AVM1 load with `Loader`, but then moves the `AVM1Child` to a non-Loader parent (by calling `otherParent.addChild(avm1Movie)`). This could be done as a follow-up, though

**Review by Aaron1011 — APPROVED** [review]
Approved with a few nits

**Comment by Lord-McSweeney** [comment]
> It would be good to have a test that does an AVM2 -> AVM1 load with Loader, but then moves the AVM1Child to a non-Loader parent (by calling otherParent.addChild(avm1Movie)). This could be done as a follow-up, though

:sweat_smile: This...will currently fail with this PR. I was hoping to resolve it in a follow-up, since a little refactoring is necessary to correctly implement `AVM1Movie`.
