### PR TITLE
Make rendering raw bitmaps faster with the canvas backend

### LINKED ISSUE #5379: Some flash files temporarily shows a white screen with GPU disabled
### Describe the bug

When Chromium is launched without GPU acceleration (--disable-gpu), some flash files temporarily shows a white screen then recovers.

These shows a white screen but after sometime they recover:
https://z0r.de/L/z0r-de_3701.swf
https://z0r.de/L/z0r-de_3707.swf
https://z0r.de/L/z0r-de_5044.swf

### Expected behavior

All the flash files should display graphics like what it used to look like.

### Affected platform

Self-hosted version

### Operating system

Arch Linux

### Browser

Chromium 94.0.4606.61

### Additional information

During the white screen moments, browser console prints a bunch of these:

```
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 94ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 95ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 101ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 90ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 88ms
...
```

### PR DESCRIPTION
**Pull request by torokati44**
This is supposed to fix #5379, and make video playback in general much faster with the canvas backend.
By avoiding PNG and base64 compression and encoding (then decoding and decompression by the browser) every time a texture is updated.

I'm uncertain about the lazy caching of the `data_uri`, as the whole bitmap array needs to be `mut` for this;
perhaps simply computing it every time it is needed (which is, I have no idea how often) would be better.

### CODE REVIEW

**Comment by torokati44** [comment]
Using `ImageBitmap` would have been a bit nicer, as that can both decode compressed images, and be constructed from an `ImageData`, but alas, Safari doesn't have it...

**Comment by Danct12** [comment]
After I apply the patch, the SWFs I previously had the issue now play perfectly fine. Thanks! :+1:

File: render/canvas/src/lib.rs [hunk 1]
```diff
@@ -545,17 +626,54 @@ impl RenderBackend for WebCanvasRenderBackend {
...
+                    canvas.set_height(bitmap.height);
+
+                    let context: CanvasRenderingContext2d = canvas
+                        .get_context("2d")
+                        .unwrap()
+                        .unwrap()
+                        .dyn_into()
+                        .unwrap();
+
+                    let _ = context.put_image_data(data, 0.0, 0.0).unwrap();
```
Comment (Herschel) [inline render/canvas/src/lib.rs:670]: Could we perhaps cache this canvas with the image drawn as well, instead of re-creating on each render?

File: render/canvas/src/lib.rs [hunk 2]
```diff
@@ -104,12 +104,108 @@ impl CanvasFillStyle {
...
+
 #[allow(dead_code)]
 struct BitmapData {
-    image: HtmlImageElement,
+    image: BitmapDataStorage,
     width: u32,
     height: u32,
-    data: String,
+    /// Might be computed lazily if not available at creation.
+    data_uri: Option<String>,
```
Comment (Herschel) [inline render/canvas/src/lib.rs:125]: Could use `RefCell` here for interior mutability instead of changing the methods to `mut`. Don't think it's a big deal either way.

**Review by Herschel — COMMENTED** [review]
Possibly more for a future PR since this PR is improving the current-state-of-things, but we should try to use Blobs with [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL). This would let us feed the data directly to the browser and avoid the base64 encoding.

**Comment by Herschel** [comment]
Not sure offhand, but a likely candidate is Interactive Buddy, which draws quite a lot using the drawing API. (Not sure about bitmaps though). I can post a few test SWFs if you'd like.

**Comment by torokati44** [comment]
According to Discord user `@linzers`, this also fixes some bitmap rendering (repeated bitmapFill) in their WIP game in Safari 14.x.

File: render/canvas/src/lib.rs [hunk 3]
```diff
@@ -103,12 +107,145 @@ impl CanvasFillStyle {
...
+        let window = web_sys::window().unwrap();
+        let document = window.document().unwrap();
+
+        let canvas: HtmlCanvasElement = document
+            .create_element("canvas")
+            .unwrap()
+            .dyn_into()
+            .unwrap();
+
+        canvas
```
Comment (adrian17) [inline render/canvas/src/lib.rs:134]: the element isn't attached to the DOM, right? Does setting `display` do anything here?

**Review by adrian17 — APPROVED** [review]

File: render/canvas/src/lib.rs (hunk 3 above)
Comment (torokati44) [reply render/canvas/src/lib.rs:134]: Hmm, good catch, it most likely doesn't do a thing.
TBH I mostly just copied what's in `WebCanvasRenderBackend::push_render_target()`, not realizing that it also appends the canvas to the `root_canvas` - but... um... why exactly?
