### PR TITLE
avm1: Remove incorrect properties from display object prototypes (fix #768)

### LINKED ISSUE #768: _root, _parent, _global are not members of MovieClip.prototype
Currently we cheat by putting `_root`, `_parent`, and `_global` as properties on the prototype of MovieClip, Button, etc., but this isn't correct:
`trace(MovieClip.prototype.hasOwnProperty("_root")); // false in Flash, true in Ruffle`

Instead, these should be "special" properties inherent to `StageObject`, similar to `_x`, `_y`, and `_rotation`. The tricky part is that `_root`, `_parent`, and `_global` respect case-sensitivity, unlike the other special properties. That is, `_RoTaTiOn` works regardless of SWF version, but `_RoOt` only works in SWFv6 and below.

### PR DESCRIPTION
**Pull request by Herschel**
* Remove `_root`, `_global`, and `_parent` from `MovieClip.prototype` and others.
   *  Instead, these are magic properties now handled in `StageObject::resolve_path_property`.
   * Clean up `StageObject::get_local_stored` a bit.
 * Remove `toString` from `MovieClip.prototype` and others. StageObjects instead naturally use their path when coerced to string.
 * At this point, `avm1::globals::display_object` is mostly empty, so remove it. Move the items up one level into `globals`.
 * Remove incorrect `Video.getDepth` declaration.

Fixes #768.

### CODE REVIEW

**Review by relrelb — APPROVED** [review]

File: core/src/avm1/object/stage_object.rs [hunk 1]
```diff
@@ -177,29 +185,38 @@ impl<'gc> TObject<'gc> for StageObject<'gc> {
...
-            // 2) _levelN
-            Some(level)
-        } else if let Some(child) = obj
+        // 1) Actual properties on the underlying object
+        if let Some(value) = obj.base.get_local_stored(name, activation) {
+            return Some(value);
+        }
+
+        // 2) Path properties such as `_root`, `_parent`, `_levelN` (obeys case sensitivity)
+        let magic_property = name.starts_with(b'_');
```
Comment (relrelb) [inline core/src/avm1/object/stage_object.rs:196]: I guess this check if for performance only, since it doesn't affect the lookup logic at all.

File: core/src/avm1/value.rs [hunk 2]
```diff
@@ -428,13 +428,18 @@ impl<'gc> Value<'gc> {
...
             Value::Bool(false) if activation.swf_version() < 5 => "0".into(),
             Value::Object(object) => {
-                match object.call_method("toString".into(), &[], activation)? {
-                    Value::String(s) => s,
-                    _ => {
-                        if object.as_executable().is_some() {
-                            "[type Function]".into()
-                        } else {
-                            "[type Object]".into()
+                if let Some(object) = object.as_display_object() {
```
Comment (relrelb) [inline core/src/avm1/value.rs:431]: Another argument for https://github.com/ruffle-rs/ruffle/pull/6548#discussion_r836713330.

**Comment by Toad06** [comment]
LGTM, I haven't found any regression in my testings. 👍

Checking the other related issues:
- #5533 is now fixed.
- #5565 persists. It seems like the `target_clip()` call in `fn action_get_property` returns `None`, so `_root.Mechant2:_X` still returns undefined. Not sure if that's completely related to 768.
