### PR TITLE
core: Run scripts registered at frame script phase in a seperate pass

### LINKED ISSUE #10443: Flight: Upgrade screen invokes epilepsy
### Describe the bug
SWF: [https://www.gameszap.com/files/swf/flight-1509798285.swf](https://www.gameszap.com/files/swf/flight-1509798285.swf)
(also attached to issue at [flight-1509798285.zip](https://github.com/ruffle-rs/ruffle/files/11097249/flight-1509798285.zip))

At the plane upgrade screen, all the upgrade and achievements cycles between different images (sprites?) very fast.
[Error Log](https://gist.github.com/HeyBanditoz/f50bebed936ad2acf71f248da8073e9c)
(the mouseOver and click errors only seem to happen when moving mouse over an upgrade, or clicking one, maybe a different issue?)
https://user-images.githubusercontent.com/7574664/228444224-11be736a-b8ee-4db8-b5fb-f6c6193b9467.mp4

#### Reproduction Steps
1. Load the game.
2. Create a new save.
3. Fly the plane, try to crash it.
4. Click next to skip the after-flight stats.
5. Observe the bug.

### Expected behavior
For the upgrades screen to look like this instead:
image

### Affected platform
Linux build of [nightly-2023-03-29](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-03-29), but observed on web too.

### Operating system
Linux

### Additional information
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
```

### LINKED ISSUE #14629: ruffle executes wrong frame scripts on movieclips when registered within a frame script
### Describe the bug

it seems like when adding a child with its own children via `addChild` while in a frame, as opposed to it being part of the frame,
the frame scripts of the grandchildren can execute before the child finished its construction.

i made an SWF (attached below) based on the `button_nested_frame_simple` test which demonstrates this behavior.

when running the SWF with ruffle with the command line:
```
RUST_LOG=warn,ruffle_core=debug,avm_trace=trace ./ruffle_desktop -g gl test.swf
```

i get the following output:

```
2024-01-06T00:27:30.436544Z  WARN egui_wgpu::renderer: Detected a linear (sRGBA aware) framebuffer Rgba8UnormSrgb. egui prefers Rgba8Unorm or Bgra8Unorm    
2024-01-06T00:27:30.481086Z  INFO ruffle_core::library: Loaded new device font "Noto Sans" from swf tag
2024-01-06T00:27:30.495783Z  INFO ruffle_core::player: Loaded SWF version 16, resolution 550x400 @ 24 FPS
2024-01-06T00:27:30.647856Z  INFO run_frame:run_all_phases_avm2: avm_trace: Main Constructor
2024-01-06T00:27:30.647967Z  INFO run_frame:run_all_phases_avm2: avm_trace: Main addFrameScript
2024-01-06T00:27:30.647991Z  INFO run_frame:run_all_phases_avm2: avm_trace: Main frame1
2024-01-06T00:27:30.650296Z  INFO run_frame:run_all_phases_avm2: avm_trace: Main frame2
2024-01-06T00:27:30.650380Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyContainer Constructor
2024-01-06T00:27:30.650403Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild Constructor
2024-01-06T00:27:30.650416Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild addFrameScript
2024-01-06T00:27:30.650430Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild Constructor
2024-01-06T00:27:30.650442Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild addFrameScript
2024-01-06T00:27:30.650622Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyContainer addFrameScript
2024-01-06T00:27:30.650649Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyContainer frame1
2024-01-06T00:27:30.650657Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild frame1
2024-01-06T00:27:30.650663Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild frame1
2024-01-06T00:27:30.671357Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild frame2
2024-01-06T00:27:30.671384Z  INFO run_frame:run_all_phases_avm2: avm_trace: MyChild frame2
```

### Expected behavior

expected to get the same output as the flash player.

when running the same SWF with flash player (debug version), the contents of the log are:
```
Main Constructor
Main addFrameScript
Main frame1
Main frame2
MyContainer Constructor
MyChild Constructor
MyChild addFrameScript
MyChild Constructor
MyChild addFrameScript
MyChild frame1
MyChild frame1
MyContainer addFrameScript
MyChild frame2
MyChild frame2
```

### Content Location

here is the zip containing the SWF as `test.swf`, along with the scripts and `fla` file.

[test.zip](https://github.com/ruffle-rs/ruffle/files/13847717/test.zip)

### Affected platform

Desktop app

### Operating system

Fedora Linux 39.20240104.0 (Silverblue)

### Browser

_No response_

### Additional information
tested on:
```
ruffle 0a6a95e6f1bb9becd6dc97e590a06f90a75c083c
rustc 1.77.0-nightly (f688dd684 2024-01-04)
```

### PR DESCRIPTION
**Pull request by nivkner**
fixes #10443, and fixes #14629 for the version that does not include buttons.
when buttons are added to the dynamically constructed object, that is a separate issue of the frame script of the child happening *before the parent's constructor finishes*

im not sure i nailed down all the subtleties regarding the interaction between the cleanup pass and goto,
but the PR passes all the current tests on my machine, and the tests i made,
so i believe it is ready for review as is.

### CODE REVIEW

**Comment by nivkner** [comment]
an additional test, attached here:
[frame_script_test.zip](https://github.com/user-attachments/files/19513791/frame_script_test.zip)
suggests that rather than inserting to the queue and then ignoring the script while traversing the tree normally,
there is actually a deferred registration.
so if there is already a script in place, it gets executed during the traversal,
*and* the new one is executed during cleanup.

**Comment by nivkner** [comment]
this test 
[frame_script_test3.zip](https://github.com/user-attachments/files/19516627/frame_script_test3.zip)
complicates matters, because while the script on the already registered frame does occur during regular traversal,
as well as the cleanup, the new script is executed.
in other words, the scripts *are* modified in place.

previous tests shown that scripts introduced during cleanup are not executed during traversal, when there were no scripts before. so next guess is that scripts registered during frame-script phase are enqueued for execution separately.

**Comment by nivkner** [comment]
@Aaron1011 , is there a scenario where the `queued_script_frame` field of `MovieClip`, when it is populated, is different from `current_frame`?
i replaced all usage of it with `current_frame`, and all the tests pass.
it isn't modified by `goto` or something like that...

my current_plan is to replace it with `has_pending_script`, which depend on the existence of a frame_script in the current frame, and can be toggled by the cleanup pass.

**Comment by nivkner** [comment]
fixed the behavior for the new test cases.

separated `queued_script_frame` into a boolean and a number, but no information should be lost (any case where the flag would be false, the script would skip, regardless of the value of the `Option`).

there are 2 cases of frame script behavior that i haven't resolved.
one is the aforementioned dynamic construction with buttons,
and the other is 
[frame_script_test4.zip](https://github.com/user-attachments/files/19521614/frame_script_test4.zip)
where the frame script of `Spawn` seems to just disappear from the second cycle onward, (it doesn't reach the call to 'stop()').

since both are sufficiently different from the issue addressed by this PR, i will open a separate issue and leave them for another time.

**Comment by Lord-McSweeney** [comment]
#12942 might be fixed by this.

**Comment by nivkner** [comment]
the PR does not fix #12942, confirmed by running against commit [2f8f340](https://github.com/ruffle-rs/ruffle/pull/19941/commits/2f8f3405c22eb2285ca65323b0e0e8fe2586f3b8)

File: core/src/display_object/movie_clip.rs [hunk 1]
```diff
@@ -1035,6 +1041,10 @@ impl<'gc> MovieClip<'gc> {
             self.play();
         }
 
+        // When performing goto, frame scripts behave the same as when entering a new frame
+        // so no seperate cleaup is performed on ones registered during frame script phase
```
Comment (Molisson) [inline core/src/display_object/movie_clip.rs:1045]:
```suggestion
        // so no seperate cleanup is performed on ones registered during frame script phase
```

**Review by Molisson — APPROVED** [review]
Assuming we're fine with this PR with no objections, it is well detailed, good job.
I ignored test files.

File: core/src/display_object/movie_clip.rs (hunk 1 above)
Comment (torokati44) [reply core/src/display_object/movie_clip.rs]: (also, typo: "separate")

**Review by Molisson — APPROVED** [review]

**Review by Lord-McSweeney — APPROVED** [review]
