### PR TITLE
avm1: Fix `Number(String | Object)` in SWFv4

### LINKED ISSUE #6286: avm1: `Number(string)` in SWFv4 should never return NaN
[Sample](https://github.com/ruffle-rs/ruffle/files/8062056/sample.zip) (SWF)

```
// All of these cases incorrectly return NaN in Ruffle (this should only happen as of SWFv5).

trace(Number("12.34A")); // 12.34 in Flash
trace(Number("A12.34")); // 0
trace(Number("   12.34      ")); // 12.34
trace(Number("12.3 4")); // 12.3
trace(Number("12C34")); // 12
trace(Number("")); // 0
trace(Number("ABC")); // 0
```

The behaviour that Flash uses in SWFv4 or below seems to be the same as `parseFloat`, with the exception that NaN values are converted to 0.

### PR DESCRIPTION
**Pull request by Toad06**
Closes #6286.

This also fixes `int(String)` in SWFv4 when the string is something like "345ABC" (it now returns 345).

[Here is a test](https://github.com/ruffle-rs/ruffle/files/8446418/swf4_test.zip) made with JPEXS (includes the .swf, code as .txt and output) that could eventually be added (a .fla would be better but I don't know if the Flash editor would let you use `ToNumber` as this action code was only added in SWFv5).

### CODE REVIEW

File: core/src/avm1/value.rs [hunk 1]
```diff
@@ -149,6 +149,11 @@ impl<'gc> Value<'gc> {
         let v = match self {
             Value::Undefined if activation.swf_version() < 7 => return 0.0,
             Value::Null if activation.swf_version() < 7 => return 0.0,
+            Value::Object(_) if activation.swf_version() < 5 => return 0.0,
+            Value::String(v) if activation.swf_version() < 5 => {
+                use crate::avm1::globals::parse_float_impl;
+                return parse_float_impl(v.trim_start(), true, 0.0);
+            }
```
Comment (Herschel) [inline core/src/avm1/value.rs:156]: Instead of adding the `default_return_value` param to `parse_float`, could this case instead check if the return value of `parse_float_impl(val)` and return 0 in that case? That way the change stays local to only this function.

**Review by Herschel — APPROVED** [review]
Thank you!
