### PR TITLE
core: `URLLoader` should check the data format after loading finishes, not when starting a load

### LINKED ISSUE #10135: Incorrect type at URLLoader COMPLETE event
### Describe the bug

URLLoader COMPLETE event target.data is String type instead of ByteArray thus causing an error 
```
		private function init(e:Event = null):void 
		{
			removeEventListener(Event.ADDED_TO_STAGE, init);
			var request:URLRequest = new URLRequest("StringToByteArrayTest.swf");
			var urlLoader:URLLoader = new URLLoader(request);
			urlLoader.addEventListener(Event.COMPLETE, onZipLoad);
			urlLoader.dataFormat = URLLoaderDataFormat.BINARY;
			urlLoader.load(request);
		}
		
		protected function onZipLoad(e:Event):void 
		{
			var zipBytes:ByteArray = e.target.data;
			trace(zipBytes);
		}
```
[StringToByteArrayTest.zip](https://github.com/ruffle-rs/ruffle/files/10996051/StringToByteArrayTest.zip)

Discovered in the process of considering to make a web version for Shapik The Moon Quest. 
We use this code to load a zip file.  

### Expected behavior

e.target.data Should be ByteArray.
The swf should trace
```
CWS+1xmTáRÛF¾ÓI>ÛØ`01Á@b´)¶dӴÁRN2g0v:fðam¥²¤ú§üì[õ(̤¯Ð8O@ïdꦚÑÌi÷Ûo¿ݽÕ)ÀÌyBPüìA6^víL2ßrÍl!od3/·¢Ìlö+;áuüøÚÌv8÷JºÞï÷óýµ¼ËÚza}}]7z±æprsüG٭hF<KúMfy\ðØÌæ-wÂìÊlêԦ]êp_/ä
ÙøwXÇÏÓ=¦ù¦ÛՅC/â(SÍlZ.ë¾E<϶DæÔOs~ÇmþÔ'=kÙÄïlèwÀ@f,KسlÊ2éÒÍl¹)	júÌöȗ½kV1oÈvX¶¹]{öYÑXÏê£ÒuÙÁÕ.zDS·À¶rss3`¯{S®վ¯îW@%ñÚ¿ϾU]ÊÚÔ	 ¨ZÅÕoåD\çGËÛu9wtÔv¸{dҖt
¹Gj{Ès}ô¼øj³8çMË÷lr_ÿD6¹Ë>_+<ßÙ.Õ[¢~Ýcn®å´ëÄ_«³V˦Ôç~½ƙ0¸_qZfIsÝgÍ/¤Ð<ñ1£?#¤1j©²$£]·G¿îiïZ>§e1bÔ<pk´iô»ýÝýa\d¨ܡ|þåý~+"àC氜 M9Mº1þбåv5	';Á%Qm!F
@±a*ùjϵÌð/'òC)pUÆ͎u±4líʸ±2lqõø-mòmW,%ª{8zåpʈ¸]=:.ûÇH¾¡¸R Wú	ov(

ãgvĤÞ0«G8ݫdïGëz·2åښXãs]^X.®ÑíÔ&)N¸eûʨæË9Lý'[|LØôe¤Æü·ÕÏhÊ}%SÔlj)­¤³éGéôGéÇé'sXû8üIêS%D'bq49Ãba¤`5Ñ4֒XKat£4F
8´Ñ2e§b´Q£'8ǪU«M.
MÀß`,6%è|
EZR¡otj1Ԉ!J(¨bý ª4T4ápïÂx¿\CÁr

8Ôó«3
XՔÃÐ ½zïuÞâËÁÂkÏñWÅչR
+W¥Õy¹º<¨Fá7!¬áCþ<jÅ[çSïÁyY@Çxñ
4¦ə	á Y !áÁl "¬´Tda8{aPИ1I£1k4îÑP?¥àé $å¿FÞð¥8ü
`ÜÇå
```

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

```
INFO ruffle_core::player: Loaded SWF version 43, resolution 800x600 @ 120 FPS
2023-03-16T21:17:58.967783Z ERROR ruffle_core::avm2::activation: AVM2 error: Object(ErrorObject(ErrorObject { class: TypeError, ptr: 0x2dc99403260 }))
2023-03-16T21:17:58.967895Z ERROR ruffle_core::avm2::activation: TypeError: Type Coercion failed: cannot convert String("CWS+1\u{6}\0\0x\u{1}mTáRÛF\u{10}¾ÓI>ÛØ`01Á@b\u{1c}\u{9a}´)¶dӴÁ\u{1}R\u{17}\u{97}N2\u{14}g0\u{9d}v:fða\u{9d}m¥²¤\u{9e}\u{e}\u{1b}ú§üì[õ\u{15}(\u{324}¯Ð\u{7f}8O@ïd\u{17}ꦚÑÌi÷Ûo¿ݽÕ)À\u{17}\0Ìy\0\u{9c}BP\u{99}\u{9e}\u{7}\0ü\u{9a}ìA\06^\u{9e}víL\u{8f}2ßr\u{9d}Íl!od3/·¢\u{1b}Ìl\u{95}ö+;\u{19}áuü\u{92}øÚÌv8÷JºÞï÷óýµ¼ËÚza}}]7\u{8a}z±\u{98}\u{13}\u{88}\u{9c}\u{7f}æpr\u{9a}süG٭hF<\u{1}K\u{85}úMfy\\ð\u{8f}ØÌæ-\u{99}wÂì\u{80}ÊlêԦ]êp_/ä\u{b}Ù\u{11}\u{94}øwXÇÏ\u{13}Ó=¦ù¦ÛՅC/\u{1a}\u{85}â(S\u{90}Íl\u{96}Z.ë\u{12}¾E<϶\u{9a}DæÔOs~ÇmþÔ\'=\u{9a}kÙÄïlèwÀ@f\u{10},\u{8}K\u{82}سlÊ2\u{e}éÒÍl¹)\tj\u{81}úÌöȗ½kV1oÈv\u{1d}\u{9f}X¶¹\u{99}]{öYÑXÏê£ÒuÙÁ\u{7f}Õ.z\u{1a}\u{98}DS·À¶rss3\u{99}\0`¯\u{9a}{S®վ¯îW@%ñ\u{17}Ú\0¿ϾU\u{1}\u{10}\u{93}\u{1}]ÊÚÔ\u{4}\t\u{90}\u{17}\u{1f}\u{a0}¨Z\u{8e}ÅÕo\u{89}åD\\çGËÛu\u{89}9wtÔv\u{8f}¸{dҖt\u{b}¹G\u{1d}j{Ès}ô¼ø\u{c}\u{84}j\u{1e}³8\u{8d}\u{7}\u{85}çMË÷lr\u{86}\u{8a}_\u{18}\u{8b}ÿD6¹Ë>\u{8}_+<ßÙ.Õ[¢\u{19}~Ýcn\u{9b}\u{91}®å´ëÄ_«³\u{93}V˦\u{7}Ôç~½ƙ0\u{1f}¸_\u{9d}qZf\u{8c}\u{9c}IsÝgÍ\u{17}/¤Ð<ñ1£?\u{9f}\u{8}#¤\u{11}1j©\u{99}²$£]·G¿î\u{89}iïZ>§\u{e}e1b\u{9a}Ô<pk\u{9c}´iô»ýÝýa\\d¨ܡ|þ\u{7f}\u{93}åý~+\"àC氜\u{a0}M9M\u{8}º1þбå\u{10}v\u{16}5\t\';Á%Qm!F\u{b}@±a\u{12}*\u{5}ùjϵÌð/\u{96}\'\u{8b}òC\u{9c}\u{88})pUÆ\u{34e}u±4líʸ±2lqõø-mòmW,\u{84}%ª{8\u{e}zåpʈ¸]=:\u{4}.\u{8c}ûÇH\u{16}\u{87}¾¡¸R\u{a0}Wú\tov(\u{b}\rãgvĤÞ0«G8ݫ\u{95}dï\u{97}Gëz·2åښX\u{19}ãs]^X.®ÑíÔ&\u{86})N¸eû\u{1a}\u{17}ʨæË9Lý\'[|LØô\u{7}e¤Æü·ÕÏhÊ}%\u{85}S\u{91}Ôlj)\u{ad}¤³éGé\u{95}ôGéÇé\'sXû8üIêS%\u{e}\u{15}\u{1c}\u{8e}D\'bq49\u{95}\u{98}Ã\u{10}b\u{5}a¤`5\u{8c}Ñ4\u{592}XKat\u{1f}£4F\u{b}8´\u{88}Ñ\u{3}\u{8c}2\u{91}e\u{88}§\u{9f}b´\u{8a}Q\u{e}£\'8\u{94}Ǫ\u{8e}U\u{3}«\u{5}M.\r\u{8c}MÀß`,6%\u{e}è|\n\0EZ\u{1}R¡\u{16}\u{12}ot\u{2}j1\u{88}Ԉ\u{2}\u{90}\u{2}!\u{80}J\u{19}(\u{10}¨bý ª\u{8}4T4á\u{6}pïÂx\u{1f}¿\u{86}\u{93}\u{10}\\CÁr\r\u{13}\n8Ô\u{6}ó«3\rXՔÃÐ ½zïu\u{8}\u{9e}\u{87}Þ\u{1d}âËÁÂk\u{c}Ïñ\u{9f}W\u{83}Åչ\u{86}R\r+W\u{83}¥Õy\u{12}¹º\u{1c}<¨Fá7\u{82}\u{19}!\0\u{97}\u{87}¬\u{1}áC\u{8}þ\u{18}<jÅ[\u{93}çSï\u{1a}\u{89}Á\u{8a}yY\u{96}@\u{84}\u{84}\u{96}Ç\u{12}xñ\n4¦\u{7}ə\t\0\u{e}á Y\u{85} !\u{8f}áÁl\u{a0}\"¬\u{8}´T\u{e}d\u{18}\u{10}a8{aPИ1\u{1a}I£1k4î\u{19}\u{8d}\u{94}ÑP\u{9f}\u{1a}?\u{80}¥àé \u{81}\u{8c}$å¿FÞ\u{18}ð¥8ü\r`ÜÇå") to flash.utils.ByteArray.
2023-03-16T21:17:58.968352Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x2dc995f76e0 }) to handler FunctionObject(FunctionObject { ptr: 0x2dc99557520 }) : AvmError(Object(ErrorObject(ErrorObject { class: TypeError, ptr: 0x2dc99403260 })))
2023-03-16T21:17:58.968740Z  INFO avm_trace: CWS+1♠x☺mTáRÛF►¾ÓI>ÛØ`01Á@b∟´)¶dӴ☺R↨N2¶g0v:fðam¥²¤♫§üì[õ§(̤¯Ð⌂8O@ïd↨ꦚÑÌi÷Ûo¿ݽÕ)À↨ÌyBPüìA6^víL2ßrÍl!od3/·¢lö+;↓áuüøÚÌv8÷JºÞï÷óýµ¼ËÚza}}]7z±‼⌂æprsüG٭hF<☺KúMfy\ðØÌæ-wÂìÊlêԦ]êp_/ä♂Ù◄øwXÇÏ‼Ó=¦ù¦ÛՅC/→â(SÍlZ.ë↕¾E<϶DæÔOs~ÇmþÔ'=kÙÄïlèwÀ@f►KسlÊ2♫éÒÍl¹)  júÌöȗ½kV1oÈv↔X¶¹]{öYÑXÏê£ÒuÙÁ⌂Õ.z→DS·À¶rss3`¯{S®վ¯îW@%ñ↨Ú¿ϾU☺►☺]ÊÚÔ♦     ▼ ¨ZÅÕoåD\çGËÛu9wtÔv¸{dҖt♂¹G↔j{Ès}ô¼ø♀j▲³8çMË÷lr_↑ÿD6¹Ë_+<ßÙ.Õ[¢↓~Ýcn®å´ëÄ_«³V˦Ôç~½ƙ0▼¸_qZfIsÝgÍ↨/¤Ð<ñ1£?#¤◄1j©²$£]·G¿îiïZ>§♫e1bÔ<pk´iô»ýÝýa\d¨ܡ|þ⌂åý~+"àC氜 M9º1þбå►v▬5      ';Á%Qm!F♂@±a↕*♣ùjϵÌð/'òC)pUÆ͎u±4líʸ±2lqõø-mòmW,%ª{8♫zåpʈ¸]=:♦.ûÇH▬¾¡¸R Wú        ov(♂
ãgvĤÞ0«G8ݫdïGëz·2åښX↓ãs]^X.®ÑíÔ&)N¸eû→↨ʨæË9Lý'[|LØôe¤Æü·ÕÏhÊ}%SÔlj)­¤³éGéôGéÇé'sXû8üIêS%♫§∟D'bq49Ã►b♣a¤`5Ñ4֒XKat▼£4F♂8´Ñ♥2e§b´Q♫£'8ǪU♥«♣M.
MÀß`,6%♫è|
EZ☺R¡▬↕ot☻j1Ԉ☻☻!J↓(►¨bý 4T4á♠pïÂx▼¿►\CÁr
‼
8Ô♠ó«3
XՔÃÐ ½zïÞ↔âËÁÂk♀ÏñWÅչR
+W¥Õy↕¹º∟<¨Fá7↓!¬☺áþ↑<jÅ[çSï→ÁyY@Ç↕xñ
4¦ə     ♫á Y !áÁl "´T♫d↑►a8{aPИ1→I£1k4î↓ÑP→?¥àé $å¿FÞ↑ð¥8ü
`ÜÇå
```

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Improves the Kongregate version of #16635 (the play button shows up now).

Should fix #10135

### CODE REVIEW

**Comment by HaimZik** [comment]
You can use the code from [](https://github.com/ruffle-rs/ruffle/issues/10135) for the test

File: core/src/loader.rs [hunk 1]
```diff
@@ -1476,8 +1474,24 @@ impl<'gc> Loader<'gc> {
...
-                    data_format: DataFormat,
                 ) {
+                    let data_format = target
+                        .get_public_property("dataFormat", activation)
+                        .expect("The dataFormat field exists on URLLoaders")
+                        .coerce_to_string(activation)
+                        .expect("The dataFormat field is typed String");
+
+                    let data_format = if &data_format == b"binary" {
+                        DataFormat::Binary
```
Comment (evilpie) [inline core/src/loader.rs:1485]: Do we even need `DataFormat` now that everything is handled locally?

File: core/src/loader.rs [hunk 2]
```diff
@@ -1502,6 +1493,11 @@ impl<'gc> Loader<'gc> {
                                 .ok()
                                 .map(|o| o.into())
                         }
+                    } else {
+                        let string_value =
```
Comment (Aaron1011) [inline core/src/loader.rs:1497]: Can you log a warning when we get an unknown format?
