### PR TITLE
desktop: Add --letterbox option

### LINKED ISSUE #9492: Vectorpark Ball width error
### Describe the bug

image

Swf default is one pixel wide, somehow it works fine in abode flash but not in ruffle.

### Expected behavior

See right part of picture

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

### Browser

_No response_

### Additional information
(https://github.com/ruffle-rs/ruffle/files/10702672/Ball.swf.zip)

### PR DESCRIPTION
**Pull request by n0samu**
Closes #9492.

### CODE REVIEW

File: core/src/config.rs [hunk 1]
```diff
@@ -22,3 +24,19 @@ pub enum Letterbox {
...
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        if s == "off" {
+            Ok(Letterbox::Off)
+        } else if s == "fullscreen" {
+            Ok(Letterbox::Fullscreen)
+        } else if s == "on" {
+            Ok(Letterbox::On)
+        } else {
+            Err("Not a valid letterbox value")
+        }
```
Comment (Bale001) [inline core/src/config.rs:40]: Let's do a match statement here
```suggestion
        match s {
            "off" => Ok(Letterbox::Off),
            "fullscreen" => Ok(Letterbox::Fullscreen),
            "on" => Ok(Letterbox::On),
            _ => Err("Not a valid letterbox value")
        }
```

**Review by Bale001 — APPROVED** [review]
