### PR TITLE
wgpu: Fix drawing a transparent bitmap with MSAA

### LINKED ISSUE #10579: Visual regression in Hammerfest (wgpu)
### Describe the bug

- Download [the game here](https://github.com/ruffle-rs/ruffle/files/11170850/hammerfest.zip). The source code is also available: https://github.com/motion-twin/hammerfest
- Run `loader.swf` and click to start.
- Notice the visual issue (unexpected sprites on the stage) which I bisected to commit c85910b46d66dd621e0566c220690c952fd677e3.

got

### Expected behavior

Rendering from nightly-2023-02-24 (first release without the issue) to nightly-2023-03-31 (last good release):
expected

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 111

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dinnerbone**
This fixes #10579 and related issues

### CODE REVIEW

File: render/wgpu/src/surface/target.rs [hunk 1]
```diff
@@ -252,11 +252,18 @@ impl CommandTarget {
...
+                    texture.as_image_copy(),
+                    resolve_buffer.texture().as_image_copy(),
+                    size,
+                );
+            }
+
             if sample_count > 1 {
                 // Both our frame buffer and resolve buffer need to start out
                 // in the same state, so copy our existing texture to the freshly
-                // allocated frame buffer. We cannot use `copy_texture_to_texture`,
```
Comment (Aaron1011) [inline render/wgpu/src/surface/target.rs:258]: This comment is still accurate for the copy to the multisampled frame buffer.

Comment (Dinnerbone) [reply render/wgpu/src/surface/target.rs]: Undid that

**Review by Aaron1011 — APPROVED** [review]
