### PR TITLE
avm2: Optimizer improvements

### LINKED ISSUE #15227: Error on https://game251671.konggames.com/games/the_exp/destination-kepler/frame/af62058b-615a-45ca-bf0b-6974095d28f9/
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 7 but the index is 14
Error stack:
```
Error: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 7 but the index is 14
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/292.js:3369:21)
    at js_sys::Error::new::he329e38f5ae64355 (wasm://wasm/03915672:wasm-function[13733]:0xb05b80)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9929706439805e04 (wasm://wasm/03915672:wasm-function[11349]:0xaaffa6)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03915672:wasm-function[6918]:0x96ef84)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03915672:wasm-function[11065]:0xaa95b1)
    at core::panicking::panic_bounds_check::h29a91b9711c376af (wasm://wasm/03915672:wasm-function[8924]:0xa19a7e)
    at ruffle_core::avm2::activation::Activation::run_actions::h144da5a61d9035bb (wasm://wasm/03915672:wasm-function[736]:0x18e7e)
    at ruffle_core::avm2::function::Executable::exec::h31cee9bb27dd9513 (wasm://wasm/03915672:wasm-function[1068]:0x335a9d)
    at ruffle_core::avm2::object::TObject::call_property::h5f1a5f7ff2cecd27 (wasm://wasm/03915672:wasm-function[1532]:0x48e757)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::ha32196077085b659 (wasm://wasm/03915672:wasm-function[3087]:0x702aa0)
```
AVM2 stack:
```
    at exp::Debug$/log()
    at ApplicationLoader/connectedToServer()
    at ApplicationLoader/addedToStage()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Kepler438/preloaderCompleteHandler()
    at Kepler438/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, ANGLE Metal Renderer: AMD Radeon Pro 555X, Unspecified Version)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game251671.konggames.com/games/the_exp/destination-kepler/frame/af62058b-615a-45ca-bf0b-6974095d28f9/?kongregate_host=www.kongregate.com
SWF URL: https://game251671.konggames.com/gamez/0025/1671/live/Kepler438.swf?kongregate_game_version=1453215171

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-15
Channel: nightly
Built: 2024-02-15T00:15:18.016Z
Commit: 49b3b9d7dee7c830214aa5c40dce839abdcbe13a
Is extension: true

# Metadata
width: 960
height: 540
frameRate: 30
numFrames: 2
swfVersion: 30
backgroundColor: #121212
isActionScript3: true
uncompressedLength: 20264369

### LINKED ISSUE #15273: Error on https://www.minijuegos.com/helpers/game/sandbox.php
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 4 but the index is 6
Error stack:
```
Error: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 4 but the index is 6
    at J.n.wbg.__wbg_new_3a66822ed076951c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e2bc0ea2fd66f6d7cf8b.js:1:73766)
    at js_sys::Error::new::ha5dd10f8e82a8a15 (wasm://wasm/038efe72:wasm-function[13723]:0xafdd8a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hccc772acbf7079c6 (wasm://wasm/038efe72:wasm-function[11342]:0xaa85d8)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/038efe72:wasm-function[6910]:0x96a049)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/038efe72:wasm-function[11055]:0xaa1b3e)
    at core::panicking::panic_bounds_check::h29a91b9711c376af (wasm://wasm/038efe72:wasm-function[8907]:0xa11afd)
    at ruffle_core::avm2::activation::Activation::run_actions::ha8f0b67264a4895f (wasm://wasm/038efe72:wasm-function[736]:0x18e53)
    at ruffle_core::avm2::function::Executable::exec::h6882c0f8bf114ac9 (wasm://wasm/038efe72:wasm-function[1062]:0x32a9a0)
    at ruffle_core::avm2::object::TObject::call_property::h658fef5b3c0a0757 (wasm://wasm/038efe72:wasm-function[1524]:0x48374c)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hf7cc6da3036fe5bb (wasm://wasm/038efe72:wasm-function[3084]:0x6fc4d6)
```
AVM2 stack:
```
    at mvc.model.ash::EntityCreator/createFence()
    at mvc.controller::StartLevelCommand/execute()
    at org.puremvc.as3.core::Controller/executeCommand()
    at Function/apply()
    at org.puremvc.as3.patterns.observer::Observer/notifyObserver()
    at org.puremvc.as3.core::View/notifyObservers()
    at org.puremvc.as3.patterns.facade::Facade/notifyObservers()
    at org.puremvc.as3.patterns.facade::Facade/sendNotification()
    at org.puremvc.as3.patterns.observer::Notifier/sendNotification()
    at mvc.controller::LoadLevelXmlCommand/execute()
    at org.puremvc.as3.core::Controller/executeCommand()
    at Function/apply()
    at org.puremvc.as3.patterns.observer::Observer/notifyObserver()
    at org.puremvc.as3.core::View/notifyObservers()
    at org.puremvc.as3.patterns.facade::Facade/notifyObservers()
    at org.puremvc.as3.patterns.facade::Facade/sendNotification()
    at org.puremvc.as3.patterns.observer::Notifier/sendNotification()
    at Function/MainMenuMediator.as$0:anonymous()
    at mvc.view::ScreenTransitionMediator/onTransitionComplete()
    at Function/apply()
    at com.greensock::TweenLite/render()
    at com.greensock.core::SimpleTimeline/render()
    at com.greensock.core::Animation$/_updateRoot()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (800, 600, 1)

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=216151&mp_game_uid=shoot-out-in-the-west&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fshoot-out-in-the-west&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMTYxNTEvc2hvb3RvdXRpbnRoZXdlc3Quc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FSao_Paulo&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/216151/shootoutinthewest.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-19
Channel: nightly
Built: 2024-02-19T00:06:25.813Z
Commit: 8d9b50d4f459da54568de4ddcc81d61d3cc8dd07
Is extension: false

# Metadata
width: 690
height: 480
frameRate: 60
numFrames: 2
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20914988

### LINKED ISSUE #15309: Error panic - Bad Ice-Cream 2
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 2 but the index is 3
Error stack:
```
Error: panicked at core/src/avm2/verify.rs:667:52:
index out of bounds: the len is 2 but the index is 3
    at J.n.wbg.__wbg_new_3a66822ed076951c (https://www.cooljuegos.com/emulators/ruffle/core.ruffle.fd33cb0fe8f4e9efa38c.js:1:73764)
    at js_sys::Error::new::h2769242d8c3f742e (wasm://wasm/038f7e42:wasm-function[13718]:0xb003dc)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h99a1c47956a3ff11 (wasm://wasm/038f7e42:wasm-function[11338]:0xaaacb4)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/038f7e42:wasm-function[6911]:0x96b075)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/038f7e42:wasm-function[11044]:0xaa40c5)
    at core::panicking::panic_bounds_check::h29a91b9711c376af (wasm://wasm/038f7e42:wasm-function[8900]:0xa14413)
    at ruffle_core::avm2::activation::Activation::run_actions::h1576ef6a7121b6d4 (wasm://wasm/038f7e42:wasm-function[736]:0x18ea1)
    at ruffle_core::avm2::function::Executable::exec::hf878e476ee6bfefc (wasm://wasm/038f7e42:wasm-function[1062]:0x329473)
    at ruffle_core::avm2::object::TObject::call_property::h0e38d10e9bbd0b10 (wasm://wasm/038f7e42:wasm-function[1522]:0x481b90)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h4f37d59014b9ac74 (wasm://wasm/038f7e42:wasm-function[3087]:0x6fc3ef)
```
AVM2 stack:
```
    at com.nitrome.util::Lock$/isGood()
    at com.nitrome.util::Lock$/to()
    at Touchy/frame32()
    at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
    at MethodInfo-2580()
    at com.nitrome.game::Transition/doNextFrame()
    at com.nitrome.game::Transition/enterFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F08) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.cooljuegos.com/juego-en-linea/bad-ice-cream-2/
SWF URL: https://data.gameflare.com/games/3701/wkhgwXAkAkTrTS.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-20
Channel: nightly
Built: 2024-02-20T00:05:35.428Z
Commit: 30a08643296d3910593ec92d082118a5edf2269e
Is extension: false

# Metadata
width: 550
height: 550
frameRate: 30
numFrames: 121
swfVersion: 10
backgroundColor: #666666
isActionScript3: true
uncompressedLength: 3667852

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Based off @adrian17's `abstract-optimizer` branch.

Testing on the Box2D demo SWF shows that:
55% of `GetProperty` calls are converted to `GetSlot` or `CallMethod` calls
36% of `SetProperty` calls are converted to `SetSlot` calls
74% of `InitProperty` calls are converted to `SetSlot` calls
25% of `CallProperty` calls are converted to `CallMethod` calls

Testing on Sniper Team shows that `PropertyMap::get_for_multiname` is pushed down significantly. However `Activation::run_actions` is still too high for it to make a noticeable difference.

Fixes #15227
Fixes #15273
Fixes #15309

TODO:
- [ ] <s>[Constant pooling fixes](https://github.com/ruffle-rs/ruffle/pull/14631#discussion_r1453622327)</s> For later
- [x] Optimize `CallProperty` to `CallMethod`
- [ ] <s>Also support setters for `SetProperty` and `InitProperty`</s> For later
- [ ] <s>Remove `Nop`s (requires recalculating branch and jump targets)</s> For later
- [x] Resolve parameter types (#11954)
- [x] Maintain scope stack, at least topmost level
    - [ ] <s>Use it for determining type returned by `findproperty`/`findpropstrict`</s> For later
- [ ] <s>Implement more ops</s> For later

### CODE REVIEW

File: core/src/avm2/verify.rs [hunk 1]
```diff
@@ -517,6 +521,109 @@ fn verify_code_starting_from<'gc>(
...
+
+    fn set_any(&mut self, index: usize) {
+        self.0[index] = ValueType::Any;
+    }
+
+    fn set(&mut self, index: usize, value: ValueType<'gc>) {
+        self.0[index] = value;
+    }
+
+    fn at(&self, index: usize) -> Option<ValueType<'gc>> {
```
Comment (adrian17) [inline core/src/avm2/verify.rs:556]: Since the earlier verifier step checked the index, I think it should be either non-Option, or - if we intend to merge the abstract interpreter with the verifier (as the verifier also checks for type merging and stack state, which come from the abstract interpreter) - directly throw a VerifyError from here?

File: core/src/avm2/verify.rs [hunk 2]
```diff
@@ -561,279 +670,607 @@ fn optimize<'gc>(
...
+            }
+            Op::PushUndefined => {
+                stack.push_any();
+            }
+            Op::PushNaN => {
+                stack.push_number();
+            }
+            Op::PushByte { value } => {
+                if *value >= 0 {
+                    stack.push_uint();
```
Comment (adrian17) [inline core/src/avm2/verify.rs:766]: Fwiw, I'm not really sure if this matters. I think numeric types can almost freely swap with each other at runtime, so the difference between int and uint is mostly irrelevant for both the verifier and optimizer and we can't really freely optimize on them.

(Actually, this is super important in a completely different place - since a `Number`-typed value can be an `int`, we need to make sure that all three numeric types have identical disp_id->method binding, otherwise optimizing say `.toExponential()` can call a wrong method depending on runtime type.)

File: core/src/avm2/verify.rs [hunk 3]
```diff
@@ -561,279 +670,607 @@ fn optimize<'gc>(
...
+                stack.pop();
+                stack.push_any();
+            }
+            Op::Multiply => {
+                stack.pop();
+                stack.pop();
+
+                // NOTE: In our current implementation, this is guaranteed,
+                // but it may not be after correctness fixes to match avmplus
+                stack.push_number();
```
Comment (adrian17) [inline core/src/avm2/verify.rs:852]: same as above: the fact that runtime value can be an int or float, doesn't mean that we can't still set it as being number-like.

File: core/src/avm2/verify.rs [hunk 4]
```diff
@@ -561,279 +670,607 @@ fn optimize<'gc>(
...
+            }
+            Op::DecLocalI { index } => {
+                if (*index as usize) < local_types.len() {
+                    // This doesn't give any Number-int guarantees
+                    local_types.set_any(*index as usize);
+                }
+            }
+            Op::IncLocalI { index } => {
+                if (*index as usize) < local_types.len() {
+                    // This doesn't give any Number-int guarantees
```
Comment (adrian17) [inline core/src/avm2/verify.rs:805]: same as above: the fact that runtime value can be an int or float, doesn't mean that we can't still set it as being int-like.

File: core/src/avm2/verify.rs [hunk 5]
```diff
@@ -561,279 +670,607 @@ fn optimize<'gc>(
...
+
+                // Avoid checking return value for now
+                stack.push_any();
+            }
+            Op::CallProperty {
+                index: name_index,
+                num_args,
+            } => {
+                // Arguments
+                for _ in 0..*num_args {
```
Comment (adrian17) [inline core/src/avm2/verify.rs:1215]: `popn(*num_args)`? :D

File: core/src/avm2/verify.rs [hunk 6]
```diff
@@ -561,279 +670,607 @@ fn optimize<'gc>(
...
+            }
+            Op::Si8 => {
+                stack.pop();
+                stack.pop();
+            }
+            Op::Li8 => {
+                stack.pop();
+                stack.push_int();
+            }
+            _ => {
```
Comment (adrian17) [inline core/src/avm2/verify.rs:1269]: as mentioned on discord, I think we should just have all of these checked in one go - otherwise this can't be used for verification, and can randomly inhibit optimizations.

File: core/src/avm2/verify.rs (hunk 2 above)
Comment (Lord-McSweeney) [reply core/src/avm2/verify.rs:766]: This matters for `coerce_u`/`coerce_i`

File: core/src/avm2/verify.rs (hunk 1 above)
Comment (Lord-McSweeney) [reply core/src/avm2/verify.rs:556]: Since we aren't merging verifier and optimizer yet, and the optimizer goes through bytecode unaware of control flow layout, it can hit unreachable code that the verifier ignored

File: core/src/avm2/verify.rs [hunk 7]
```diff
@@ -545,6 +545,17 @@ impl<'gc> Locals<'gc> {
         self.0[index] = ValueType::Class(class);
     }
 
+    fn set_class(&mut self, index: usize, class: GcCell<'gc, Class<'gc>>) {
+        // FIXME: Getting the ClassObject this way should be unnecessary
+        // after the ClassObject refactor
+        self.0[index] = class
+            .read()
+            .class_objects()
+            .get(0)
```
Comment (Aaron1011) [inline core/src/avm2/verify.rs:554]: I'm not sure what the behavior of Flash is when multiple `ClassObjects` have been created. To be safe, we should do nothing in this method when that occurs (and also log a warning).

Comment (Lord-McSweeney) [reply core/src/avm2/verify.rs:554]: The `VTable`s should be the same, though, no?

Comment (Aaron1011) [reply core/src/avm2/verify.rs]: I'm not certain - as long as we're using `ClassObject`, I would prefer to avoid making assumptions about when distinct `ClassObjects` can be freely intermixed

File: core/src/avm2/activation.rs [hunk 8]
```diff
@@ -2243,23 +2249,23 @@ impl<'a, 'gc> Activation<'a, 'gc> {
         let value2 = self.pop_stack().coerce_to_i32(self)?;
         let value1 = self.pop_stack().coerce_to_i32(self)?;
 
-        self.push_stack(value1.wrapping_mul(value2));
+        self.push_raw(value1.wrapping_mul(value2));
```
Comment (adrian17) [inline core/src/avm2/activation.rs:2252]: I think this could also be applied to some more ops: `add`, `subtract`, `swap`, `astype`, `astypelate`? For the last three, since other ops guarantee that stack never has PrimitiveObject, then they can also never encounter a PrimitiveObject.

File: core/src/avm2/optimize.rs [hunk 9]
```diff
@@ -0,0 +1,893 @@
...
+    }
+
+    fn popn(&mut self, count: u32) {
+        for _ in 0..count {
+            self.pop();
+        }
+    }
+
+    fn clear(&mut self) {
+        self.0 = Vec::new();
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:136]: Let's just call `self.0.clear()`? This way we don't alloc-free the stack repeatedly.

File: core/src/avm2/optimize.rs [hunk 10]
```diff
@@ -0,0 +1,893 @@
...
+        argument_types.push(argument_type);
+    }
+
+    // Initial set of local types
+    let mut initial_local_types = Locals::new(method_body.num_locals as usize);
+    if let Some(this_class) = this_class {
+        initial_local_types.set_class_object(0, this_class);
+    }
+
+    let mut i = 1;
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:191]: how about `enumerate()` (and adding 1 inside the loop)? One less mutable var.

File: core/src/avm2/optimize.rs [hunk 11]
```diff
@@ -0,0 +1,893 @@
...
+            if let Ok(multiname) = multiname {
+                stack.pop_for_multiname(multiname);
+                Some(multiname)
+            } else {
+                None
+            }
+        }};
+    }
+
+    let mut scope_stack = Stack::new();
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:248]: Doesn't appear to actually be used yet for anything yet - do we need this?

File: core/src/avm2/optimize.rs [hunk 12]
```diff
@@ -0,0 +1,893 @@
...
+            Op::CoerceU => {
+                let stack_value = stack.pop();
+                if matches!(stack_value, Some(ValueType::Uint)) {
+                    *op = Op::Nop;
+                }
+                stack.push_uint();
+            }
+            Op::CoerceA => {
+                stack.pop();
+                stack.push_any();
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:291]: Can we document that this appears to inhibit optimizations in FP? In case someone decides to change this blindly in the future.

File: core/src/avm2/optimize.rs [hunk 13]
```diff
@@ -0,0 +1,893 @@
...
+                            }
+                        }
+                    }
+                    // `stack_pop_multiname` handled lazy
+                }
+
+                // Avoid checking return value for now
+                stack.push_any();
+            }
+            Op::CallPropVoid { .. } => {
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:830]: IIRC, `CallPropVoid` is identical, except it doesn't push at the end?
How about having the code above match both and just check at the end?

(AFAIK `CallPropLex` is also conceptually very similar to `CallProperty` - I think it just doesn't set `this` on the called function...?)

File: core/src/avm2/optimize.rs [hunk 14]
```diff
@@ -0,0 +1,893 @@
...
+            }
+            Op::Si8 => {
+                stack.pop();
+                stack.pop();
+            }
+            Op::Li8 => {
+                stack.pop();
+                stack.push_int();
+            }
+            Op::ReturnVoid | Op::ReturnValue | Op::Jump { .. } | Op::LookupSwitch(_) => {
```
Comment (adrian17) [inline core/src/avm2/optimize.rs:881]: note: `throw` also should terminate the block (both here and in the future refactors)

**Review by adrian17 — APPROVED** [review]

File: core/src/avm2/optimize.rs (hunk 13 above)
Comment (Lord-McSweeney) [reply core/src/avm2/optimize.rs:830]: There's no `CallMethodVoid`, so the optimization would also have to be disabled. I think this can wait until later- I don't think any compiler would emit a `CallPropVoid` with values still on the stack.

File: core/src/avm2/optimize.rs (hunk 11 above)
Comment (Lord-McSweeney) [reply core/src/avm2/optimize.rs:248]: No, but there's only three ops using it and this will come in useful for optimizing traits found by `findproperty` and `findpropstrict`

File: core/src/avm2/optimize.rs [hunk 15]
```diff
@@ -0,0 +1,898 @@
...
+use crate::avm2::op::Op;
+use crate::avm2::property::Property;
+
+use gc_arena::{Gc, GcCell};
+use std::collections::HashSet;
+use swf::avm2::types::Index;
+
+#[derive(Clone, Copy, Debug)]
+enum ValueType<'gc> {
+    // Either a class, or null.
```
Comment (evilpie) [inline core/src/avm2/optimize.rs:15]: Is this comment outdated?

File: core/src/avm2/optimize.rs [hunk 16]
```diff
@@ -0,0 +1,898 @@
...
+        if multiname.has_lazy_name() {
+            self.0.pop();
+        }
+        if multiname.has_lazy_ns() {
+            self.0.pop();
+        }
+    }
+
+    fn popn(&mut self, count: u32) {
+        for _ in 0..count {
```
Comment (evilpie) [inline core/src/avm2/optimize.rs:130]: I wonder if something like `self.0.truncate(self.0.len() - count)` would be more efficient?

File: core/src/avm2/optimize.rs [hunk 17]
```diff
@@ -0,0 +1,898 @@
...
+            Op::CoerceD => {
+                let stack_value = stack.pop();
+                if matches!(stack_value, Some(ValueType::Number)) {
+                    *op = Op::Nop;
+                }
+                stack.push_number();
+            }
+            Op::CoerceI => {
+                let stack_value = stack.pop();
+                if matches!(stack_value, Some(ValueType::Int))
```
Comment (evilpie) [inline core/src/avm2/optimize.rs:274]: nit: `matches!(stack_value, Some(ValueType::Int | ValueType::Uint))`

File: core/src/avm2/optimize.rs (hunk 15 above)
Comment (Lord-McSweeney) [reply core/src/avm2/optimize.rs:15]: No

File: core/src/avm2/optimize.rs (hunk 16 above)
Comment (Lord-McSweeney) [reply core/src/avm2/optimize.rs:130]: I don't think we need to be too worried about performance here
