### PR TITLE
core: Non-root movies that AVM1 loads should always be considered AVM1

### LINKED ISSUE #21007: Issue with mixed avm
### Describe the bug

To my understanding, ActionScript 3 movies being loaded inside of an ActionScript 2 movie doesn't get you very far. However, if said AS3 movie had *no scripts inside of it*, then you should still be able to do some stuff with it from the AS2 movie. Hence this issue.

In this test that I made, `main.swf` (an AS2 movie) will load `item.swf` (an AS3 movie with no scripts). There is also a button in main.swf for stopping the looping animation of item.swf and going to a random frame.

In Ruffle, the animation of item.swf, when loaded into main.swf, does not play at all. Nor does the button work.

### Expected behavior

The animation of item.swf should play, and the button to go to a random frame should be functional.

### Content Location

[as3_inside_as2.zip](https://github.com/user-attachments/files/21225739/as3_inside_as2.zip)

### Affected platform

Desktop app

### Operating system

macOS 15.5

### Browser

_No response_

### Additional information

I first noticed this issue in https://newcp.net/game#/login, where one of the clothing item sprites (an AS3 movie) kept looping infinitely, unaffected by the gotoAndStop calls. I suspect the reason why it doesn't stay at frame 1 the entire time like in this test is because of the root movie being AS3 instead of AS2, but I haven't tested that.

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Closes #21007

### CODE REVIEW

**Comment by kjarosh** [comment]
What if AVM2 loads AVM1, which loads AVM2?

**Comment by Lord-McSweeney** [comment]
Good point, I'll add test coverage for that too

File: core/common/src/tag_utils.rs [hunk 1]
```diff
@@ -263,10 +277,18 @@ impl SwfMovie {
...
 
-    pub fn is_action_script_3(&self) -> bool {
+    /// Whether the SWF's FileAttributes tag declares the SWF to be AS3 (rather
+    /// than AS2).
+    pub fn is_declared_action_script_3(&self) -> bool {
         self.header.is_action_script_3()
     }
 
+    /// Whether the SWF's FileAttributes tag declares the SWF to be AS3 (rather
+    /// than AS2), and `set_force_avm1` hasn't been called on this `SwfMovie`.
```
Comment (kjarosh) [inline core/common/src/tag_utils.rs]: Nit: instead of summarizing what's the implementation of the method (which everyone can see), you can add more context, e.g.:

> Whether the movie should be interpreted as AS3.
>
> This usually is the same as `is_declared_action_script_3`, but can differ in case AVM1 loads AVM2.

File: core/src/display_object/movie_clip.rs [hunk 2]
```diff
@@ -4116,6 +4112,16 @@ impl<'gc, 'a> MovieClipShared<'gc> {
         tag_code: TagCode,
         reader: &mut SwfStream<'a>,
     ) -> Result<(), Error> {
+        if !self.movie().is_action_script_3() {
+            match tag_code {
+                TagCode::DoAbc => tracing::warn!("DoABC tag in AVM1 movie"),
+                TagCode::DoAbc2 => tracing::warn!("DoABC2 tag in AVM1 movie"),
```
Comment (kjarosh) [inline core/src/display_object/movie_clip.rs:4118]: Should we warn when `!is_action_script_3` or `!is_declared_action_script_3`?

**Review by kjarosh — APPROVED** [review]

**Comment by kjarosh** [comment]
Just to make sure: when AVM1 loads AVM2, the AVM2 cannot load anything as tags are not executed, right?

File: core/src/display_object/movie_clip.rs (hunk 2 above)
Comment (Lord-McSweeney) [reply core/src/display_object/movie_clip.rs:4118]: I would go with `!is_action_script_3`, as if AVM1 loads an AVM2 movie the tags will possibly unexpectedly not be executed

Comment (kjarosh) [reply core/src/display_object/movie_clip.rs:4118]: Sure, but then the warnings are a bit misleading? They suggest it's an AVM1 movie despite the fact it's declared as AVM2.
