### PR TITLE
desktop: Change fullscreen fscommand to use event loop events

### LINKED ISSUE #17617: can't exit fullscreen with ESC in desktop app
### Describe the bug

can't exit fullscreen with ESC in some games that enter fullscreen at launch

### Expected behavior

exit fullscreen when pressing ESC

### Content Location

[pong.zip](https://github.com/user-attachments/files/16730534/pong.zip)
[china-checkers.zip](https://github.com/ruffle-rs/ruffle/files/12286235/china-checkers.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sleepycatcoding**
Previously the fullscreen state was set on the window directly causing a desync with the rest of the player code.

Fixes #17617

### CODE REVIEW

**Comment by kjarosh** [comment]
We should be able to write a quick test for that right? fscommand + get display state from stage?

**Comment by sleepycatcoding** [comment]
> We should be able to write a quick test for that right? fscommand + get display state from stage?

The test harness and desktop do not share the fscommand backend so I am not sure how useful such a test would be.

**Comment by kjarosh** [comment]
Oh you're right, no easy way to write a test then :(

File: desktop/src/custom_event.rs [hunk 1]
```diff
@@ -19,6 +19,9 @@ pub enum RuffleEvent {
     /// The user requested to close the current SWF.
     CloseFile,
 
+    /// The user requrested to enter full screen.
+    EnterFullscreen,
+
     /// The user requested to exit full screen.
     ExitFullScreen,
```
Comment (kjarosh) [inline desktop/src/custom_event.rs:26]: There is an inconsistency here: `EnterFullscreen` vs `ExitFullScreen`.

**Review by kjarosh — APPROVED** [review]

File: desktop/src/custom_event.rs (hunk 1 above)
Comment (sleepycatcoding) [reply desktop/src/custom_event.rs]: Fixed.

**Review by Dinnerbone — APPROVED** [review]
