### PR TITLE
avm1: Stub `bufferLength` and `bufferTime` on `NetStream`

### LINKED ISSUE #12934: A sign appears every 10 - 15 sec (Neave.TV 2006)
### Describe the bug

Hi everyone. There is no steps to reproduce the bug. Just launch the SWF, click on the sign in the center and it would appear. Here is the screenshot of it: 
image

The sign appears every 10 - 15 seconds, and after it appears it switches the video. If I press on "Continue watching anyway" a new video starts playing. I am sure the bug is in the SWF, but in the original Flash Player the sign does not appear. If I have any more info, I will edit the issue or post it in the comments.
Edit: The files are here: #11821 

### Expected behavior

The sign not appearing and not switching videos, as the videos play fine actually.

### Affected platform

Self-hosted version

### Operating system

Android 12

### Browser

Opera 76.2.4027.73374

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
This should fully fix #12934.

`bufferLength` always reports that the buffer is fully filled, while `bufferTime` can be set but has no effect.

### CODE REVIEW

File: core/src/streams.rs [hunk 1]
```diff
@@ -218,6 +218,8 @@ pub struct NetStreamData<'gc> {
     /// Seeks are only executed on the next stream tick.
     queued_seek_time: Option<f64>,
 
+    buffer_time: f64,
```
Comment (adrian17) [inline core/src/streams.rs:221]: can you also document it as todo-currently-unused?

**Review by adrian17 — APPROVED** [review]

File: core/src/streams.rs (hunk 1 above)
Comment (TemaisgameNoobas) [reply core/src/streams.rs:221]: > can you also document it as todo-currently-unused?

I think it requires buffer_time

**Comment by TemaisgameNoobas** [comment]
should fix #13290
